'use strict';
const $=id=>document.getElementById(id),KEY='psychology-combined-bank-v1';
let subject='all';
let bank,byId,records,state={answers:{},wrong:[],last:null},chapter=0,mode='all',kind='all',order='ordered',queue=[],pos=0,selected=[],submitted=false,storageOK=true;
let loadFailed=false;
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function toast(s){$('toast').textContent=s;$('toast').hidden=false;clearTimeout(toast.timer);toast.timer=setTimeout(()=>$('toast').hidden=true,3500)}
function save(){try{localStorage.setItem(KEY,JSON.stringify(state))}catch{storageOK=false;$('storageNote').textContent='当前浏览器无法保存记录。请在离开前导出学习记录。'}}
function restore(){try{const parsed=JSON.parse(localStorage.getItem(KEY)||localStorage.getItem('puxin-memory-bank-v1')||'null');if(parsed)state=validateState(parsed)}catch{toast('旧记录无法读取，已保留本次空白练习状态。')}}
function validateState(v){if(!v||typeof v!=='object'||!v.answers||typeof v.answers!=='object'||!Array.isArray(v.wrong))throw Error('记录格式不正确');const answers={};for(const [id,a]of Object.entries(v.answers)){if(!byId.has(id)||!a||typeof a.correct!=='boolean'||!Number.isInteger(a.attempts)||a.attempts<1)continue;answers[id]={correct:a.correct,firstCorrect:typeof a.firstCorrect==='boolean'?a.firstCorrect:a.correct,attempts:a.attempts,selected:Array.isArray(a.selected)?a.selected.filter(n=>Number.isInteger(n)&&n>=0&&n<4):[],time:typeof a.time==='string'?a.time:''}}return {answers,wrong:[...new Set(v.wrong.filter(id=>byId.has(id)))],last:v.last&&byId.has(v.last.id)?{id:v.last.id,chapter:Number(v.last.chapter)||0}:null}}
function shuffle(a){a=[...a];for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a}
function matches(q){if(subject!=='all'&&q.subject!==subject)return false;if(chapter&&q.chapter!==chapter)return false;if(mode==='review')return !q.scored;if(!q.scored)return false;if(mode==='wrong'&&!state.wrong.includes(q.id))return false;if(mode==='unseen'&&state.answers[q.id])return false;if(kind==='source'&&!['表述记忆','条目关联'].includes(q.kind))return false;if(!['all','source'].includes(kind)&&q.kind!==kind)return false;return true}
function rebuild(target){queue=bank.questions.filter(matches);if(order==='random')queue=shuffle(queue);pos=target?Math.max(0,queue.findIndex(q=>q.id===target)):0;render();stats()}
function current(){return queue[pos]}
function stats(){const qs=bank.questions.filter(q=>q.scored&&(!chapter||q.chapter===chapter)&&(subject==='all'||q.subject===subject));const done=qs.filter(q=>state.answers[q.id]);const right=done.filter(q=>state.answers[q.id].firstCorrect);const wrong=qs.filter(q=>state.wrong.includes(q.id));$('answeredCount').textContent=done.length;$('wrongCount').textContent=wrong.length;$('wrongBadge').textContent=wrong.length;$('accuracy').textContent=done.length?Math.round(right.length/done.length*100)+'%':'—';for(const btn of document.querySelectorAll('.chapter'))btn.classList.toggle('active',Number(btn.dataset.chapter)===chapter);$('chapterSelect').value=chapter;$('chapterTitle').textContent=chapter?bank.chapters.find(c=>c.id===chapter).title:(subject==='all'?'全部内容':bank.subjects.find(s=>s.id===subject).title);$('subjectSelect').value=subject;for(const btn of document.querySelectorAll('[data-mode]'))btn.classList.toggle('active',btn.dataset.mode===mode)}
function setChapter(n){if(!Number.isInteger(n)||n<0||n>bank.chapters.length)throw Error('章节不存在');chapter=n;if(n){subject=bank.chapters.find(c=>c.id===n).subject;subjectControls()}rebuild()}
function render(){selected=[];submitted=false;$('feedback').hidden=true;$('nextBtn').hidden=true;$('submitBtn').hidden=false;$('submitBtn').disabled=true;$('prevBtn').disabled=pos<=0;$('flagBtn').disabled=!current();$('jumpInput').max=queue.length;$('jumpInput').value=queue.length?pos+1:'';$('sessionProgress').value=queue.length?pos/queue.length*100:0;$('sessionInfo').textContent=queue.length?`本组 ${pos+1} / ${queue.length} 题`:'本组暂无题目';$('resumeBtn').hidden=!state.last||state.last.id===current()?.id;
 if(!current()){const title=mode==='wrong'?'本章暂无待复习的错题':mode==='unseen'?'当前范围已全部练过':mode==='review'?'当前范围没有待核对条目':'没有符合条件的题目';$('questionCard').innerHTML=`<div class="empty"><h2>${title}</h2><p>可以更换章节或练习范围。</p><button id="backAll">返回全部练习</button></div>`;$('backAll').onclick=()=>{mode='all';kind='all';$('kindSelect').value='all';rebuild()};return}
 const q=current();if(q.reviewOnly){submitted=true;$('submitBtn').hidden=true;$('nextBtn').hidden=false;$('nextBtn').textContent=pos+1<queue.length?'下一条':'完成本组';$('flagBtn').disabled=true;$('questionCard').innerHTML='<div class="q-meta"><span>第 '+q.number+' 条 · '+esc(bank.chapters[q.chapter-1].title)+'</span><span class="q-label">'+esc(q.kind)+' · 不计分</span></div><div class="question-text">'+esc(q.prompt)+'</div><div class="review-note">'+esc(q.explanation)+'</div><details><summary>查看原文定位</summary>'+q.refs.map(id=>sourceHTML(records.get(id))).join('')+'</details>';state.last={id:q.id,chapter};save();return}const kindLabel=q.kind==='关键词'?'关键词记忆':q.kind;const prompts=esc(q.prompt).replaceAll('【　　】','<span class="blank">　　</span>');$('questionCard').innerHTML=`<div class="q-meta"><span>第 ${q.number} 题 · ${esc(bank.chapters[q.chapter-1].title.replace(/^第.+?章\s*/,''))}</span><span class="q-label">${esc(kindLabel)} · ${q.scored?(q.answer.length>1?'多选':'单选'):'不计分'}</span></div><div class="question-text" id="qprompt">${prompts}</div><div class="options" role="${q.answer.length>1?'group':'radiogroup'}" aria-labelledby="qprompt">${q.options.map((o,i)=>`<button class="option" data-option="${i}" role="${q.answer.length>1?'checkbox':'radio'}" aria-checked="false"><span class="letter">${String.fromCharCode(65+i)}</span><span>${esc(o)}</span></button>`).join('')}</div>`;
 for(const b of document.querySelectorAll('[data-option]'))b.onclick=()=>choose(Number(b.dataset.option));updateFlag();state.last={id:q.id,chapter};save();}
function choose(i){const q=current();if(!q||submitted||!Number.isInteger(i)||i<0||i>=q.options.length)return;if(q.answer.length===1)selected=[i];else selected=selected.includes(i)?selected.filter(n=>n!==i):[...selected,i];for(const b of document.querySelectorAll('[data-option]')){const active=selected.includes(Number(b.dataset.option));b.classList.toggle('selected',active);b.setAttribute('aria-checked',active)}$('submitBtn').disabled=!selected.length}
function updateFlag(){if(!current())return;$('flagBtn').textContent=state.wrong.includes(current().id)?'移出错题本':'加入错题本';$('flagBtn').disabled=!current().scored}
function sourceHTML(r){if(!r)return'';if(r.table)return `<div class="source-item"><small>${esc(r.id)} · 原表（保留原始内容，疑误请以题目解析为准）</small><div class="source-table-wrap"><table class="source-table">${r.table.map(row=>'<tr>'+row.map(c=>'<td>'+esc(c)+'</td>').join('')+'</tr>').join('')}</table></div></div>`;return `<div class="source-item ${r.heading?'heading':''}"><small>${esc(r.id)} · ${esc(r.path.join(' / '))}</small><p>${esc(r.raw)}</p>${r.correction?`<p class="note">纠错：${esc(r.text)}<br>${esc(r.correction)}</p>`:''}${r.caution?`<p class="note">核对提示：${esc(r.caution)}</p>`:''}</div>`}
function submit(){const q=current();if(!q||submitted||!selected.length)return;const correct=selected.length===q.answer.length&&selected.every(n=>q.answer.includes(n));submitted=true;
 if(q.scored){const prev=state.answers[q.id];state.answers[q.id]={correct,firstCorrect:prev?prev.firstCorrect:correct,attempts:(prev?.attempts||0)+1,selected:[...selected],time:new Date().toISOString()};if(!correct&&!state.wrong.includes(q.id))state.wrong.push(q.id);save()}
 for(const b of document.querySelectorAll('[data-option]')){const i=Number(b.dataset.option);b.disabled=true;b.classList.toggle('correct',q.answer.includes(i));b.classList.toggle('incorrect',selected.includes(i)&&!q.answer.includes(i))}
 const sources=[...new Set(q.refs.map(ref=>ref.split('-R')[0]))].map(id=>sourceHTML(records.get(id))).join('');$('feedback').className='feedback '+(!q.scored?'review':correct?'':'wrong');$('feedback').innerHTML=`<h2>${!q.scored?'这条不计成绩':correct?'回答正确':'这一题再记一下'}</h2><p class="answer">${q.scored?'正确答案':'建议处理'}：${q.answer.map(i=>String.fromCharCode(65+i)).join('、')} · ${q.answer.map(i=>esc(q.options[i])).join('；')}</p><p class="topic">知识点：${esc(q.topic)}</p><p>${esc(q.explanation)}</p>${q.note?`<p class="note">纠错或限定：${esc(q.note)}</p>`:''}<details><summary>查看对应原文 · ${q.refs.map(esc).join('、')}</summary>${sources||'<p>见本章相关内容。</p>'}</details>`;$('feedback').hidden=false;$('submitBtn').hidden=true;$('nextBtn').hidden=false;$('nextBtn').textContent=pos+1<queue.length?'下一题':'完成本组';updateFlag();stats();$('sessionProgress').value=(pos+1)/queue.length*100}
function next(){if(!current())return;if(pos+1<queue.length){pos++;render();$('questionCard').scrollIntoView({behavior:'smooth',block:'start'})}else{const completed=queue.filter(q=>state.answers[q.id]).length;toast(`本组浏览完毕，已作答 ${completed} 题。可重新抽练或切换范围。`);rebuild()}}
function showSources(ch){$('sourceList').innerHTML=bank.records.filter(r=>r.chapter===ch).map(sourceHTML).join('');const refset=new Set(bank.records.filter(r=>r.chapter===ch).map(r=>r.id));const linked=bank.coverage.filter(c=>refset.has(c.ref)&&c.status==='已关联练习').length;const total=bank.questions.filter(q=>q.chapter===ch).length;const review=bank.questions.filter(q=>q.chapter===ch&&!q.scored).length;$('coverageSummary').textContent=`本章 ${total-review} 道练习，${review} 条待核对或补充；${linked} 个原文条目已关联练习。其余为结构标题、口诀或提示。`}
function exportState(){const payload={format:'psychology-combined-study-record',version:1,exportedAt:new Date().toISOString(),...state};const url=URL.createObjectURL(new Blob([JSON.stringify(payload,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='心理学综合学习记录-'+new Date().toISOString().slice(0,10)+'.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),30000);toast('已导出学习记录，可在其他设备导入。')}
async function importState(file){if(!file)return;if(file.size>20*1024*1024)throw Error('文件太大，请选择本题库导出的记录');const raw=JSON.parse(await file.text());if(!['puxin-study-record','psychology-combined-study-record'].includes(raw.format)||raw.version!==1)throw Error('请使用本题库导出的学习记录');const incoming=validateState(raw);for(const [id,a]of Object.entries(incoming.answers)){const old=state.answers[id];if(!old||a.time>old.time)state.answers[id]=a}state.wrong=[...new Set([...state.wrong,...incoming.wrong])];if(incoming.last)state.last=incoming.last;save();rebuild();toast('记录已合并导入；原有错题保留。')}
function registerAgentTools(){const mc=document.modelContext;if(!mc?.registerTool)return;const controller=new AbortController();for(const tool of [{name:'get_practice_state',title:'查看当前练习',description:'读取当前章节、题目和本机进度，不提交答案。',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute(){return{chapter,mode,question:current()?{id:current().id,prompt:current().prompt,options:current().options}:null,submitted,answered:Object.keys(state.answers).length,wrong:state.wrong.length}}},{name:'start_chapter_practice',title:'切换章节练习',description:'切换到指定章节的全部练习，0表示全部章节；会改变当前页面位置但不提交答案。',inputSchema:{type:'object',properties:{chapter:{type:'integer',minimum:0,maximum:bank.chapters.length}},required:['chapter'],additionalProperties:false},annotations:{readOnlyHint:false},execute(input){if(!input||!Number.isInteger(input.chapter)||input.chapter<0||input.chapter>bank.chapters.length)throw Error('章节编号超出题库范围');mode='all';setChapter(input.chapter);return{chapter,questionCount:queue.length,currentQuestion:current()?.id||null}}}]){try{Promise.resolve(mc.registerTool(tool,{signal:controller.signal})).catch(()=>{})}catch{}}window.addEventListener('pagehide',()=>controller.abort(),{once:true})}
async function init(){try{bank=window.QUIZ_BANK||JSON.parse(document.getElementById('bankData').textContent);byId=new Map(bank.questions.map(q=>[q.id,q]));records=new Map(bank.records.map(r=>[r.id,r]));restore();const scored=bank.questions.filter(q=>q.scored).length,review=bank.questions.length-scored;$('totalCount').textContent=scored+'题';$('chapterCount').textContent=bank.subjects.length+'科';$('bankSummary').textContent=`${scored} 道练习 · ${review} 条待核对或补充`;$('contentMethod').textContent='来源为8份上传笔记。原有普心题目保留；新增题目以关键词填空和原文表述记忆为主。已发现的错误列出纠错，无法确认的内容不计分。本版本不是全部笔记的专业终审版，不保证每条原文都正确。统计笔记的空白标题未擅自补造正文。';
 $('chapters').innerHTML=bank.chapters.map(c=>`<button class="chapter" data-chapter="${c.id}"><span>${esc(c.title.replace(/^第(.+?)章\s*/,'$1 · '))}</span><small>${bank.questions.filter(q=>q.chapter===c.id&&q.scored).length}</small></button>`).join('');const opts=bank.chapters.map(c=>`<option value="${c.id}">${esc(c.title)}</option>`).join('');$('chapterSelect').innerHTML+='<optgroup label="章节">'+opts+'</optgroup>';$('sourceChapter').innerHTML=opts;$('sourceLinks').innerHTML=bank.sources.map(s=>`<a href="${esc(s.url)}" target="_blank" rel="noopener noreferrer">${esc(s.title)}</a>`).join('');
 subjectControls();$('subjectSelect').onchange=e=>{subject=e.target.value;chapter=0;subjectControls();if(!bank.questions.some(q=>q.scored&&(subject==='all'||q.subject===subject)))mode='review';else mode='all';rebuild()};document.querySelectorAll('[data-chapter]').forEach(b=>b.onclick=()=>setChapter(Number(b.dataset.chapter)));document.querySelectorAll('[data-mode]').forEach(b=>b.onclick=()=>{mode=b.dataset.mode;rebuild()});$('chapterSelect').onchange=e=>setChapter(Number(e.target.value));$('kindSelect').onchange=e=>{kind=e.target.value;rebuild()};$('orderSelect').onchange=e=>{order=e.target.value;rebuild()};$('submitBtn').onclick=submit;$('nextBtn').onclick=next;$('prevBtn').onclick=()=>{if(pos>0){pos--;render()}};$('flagBtn').onclick=()=>{const q=current();if(!q?.scored)return;if(state.wrong.includes(q.id)){state.wrong=state.wrong.filter(id=>id!==q.id);toast('已移出错题本')}else{state.wrong.push(q.id);toast('已加入错题本')}save();stats();updateFlag()};$('jumpBtn').onclick=()=>{const n=Number($('jumpInput').value);if(!Number.isInteger(n)||n<1||n>queue.length){toast('请输入本组范围内的题号');return}pos=n-1;render()};$('resumeBtn').onclick=()=>{const last=state.last;if(!last)return;chapter=last.chapter;subject=byId.get(last.id).subject;subjectControls();mode=byId.get(last.id).scored?'all':'review';kind='all';$('kindSelect').value='all';rebuild(last.id)};
 $('notesBtn').onclick=()=>{const ch=chapter||current()?.chapter||1;$('sourceChapter').value=ch;showSources(ch);$('notesDialog').showModal()};$('sourceChapter').onchange=e=>showSources(Number(e.target.value));$('helpBtn').onclick=()=>$('helpDialog').showModal();document.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>$(b.dataset.close).close());$('exportBtn').onclick=exportState;$('importFile').onchange=async e=>{try{await importState(e.target.files[0])}catch(err){toast(err.message||'记录导入失败')}e.target.value=''};
 document.addEventListener('keydown',e=>{if(document.querySelector('dialog[open]')||/INPUT|SELECT|TEXTAREA/.test(e.target.tagName)||e.ctrlKey||e.metaKey||e.altKey)return;if(/^[1-4]$/.test(e.key)){e.preventDefault();choose(Number(e.key)-1)}if(e.key==='Enter'){e.preventDefault();submitted?next():submit()}});
 if(state.last){chapter=state.last.chapter;subject=byId.get(state.last.id).subject;subjectControls();mode=byId.get(state.last.id).scored?'all':'review';rebuild(state.last.id)}else rebuild();registerAgentTools();
 }catch(err){loadFailed=true;$('questionCard').innerHTML='<div class="empty"><h2>题库暂未加载成功</h2><p>请检查网页文件是否完整，或重新下载单文件版。</p><button id="reloadBtn">重新加载</button></div>';$('reloadBtn').onclick=()=>location.reload();$('sessionInfo').textContent='加载失败'}}
function subjectControls(){
 const cs=bank.chapters.filter(c=>subject==='all'||c.subject===subject);
 document.querySelectorAll('[data-chapter]').forEach(b=>{const n=Number(b.dataset.chapter);b.hidden=Boolean(n&&!cs.some(c=>c.id===n))});
 const opts=cs.map(c=>'<option value="'+c.id+'">'+esc(c.title)+'</option>').join('');
 $('chapterSelect').innerHTML='<option value="0">当前学科全部章节</option>'+opts;$('sourceChapter').innerHTML=opts;
}
init();
