/* Authored synthetic protocol fixture. Contains no uploaded/exam source text. */
const crypto=require('node:crypto'),SubjectPackage=require('../learning/subject-package.js'),EnglishGroups=require('../learning/english-groups.js');
const checks=keys=>Object.fromEntries(keys.map(k=>[k,{status:'passed',evidence:'Synthetic protocol assertion for '+k+'; not a review of real exam content.'}]));
async function createEnglishFixture({version='synthetic-english-v1',held=false,omitReading=false}={}){
 const source={id:'synthetic-english-source',title:'Synthetic interface material, not exam content',url:'https://example.invalid/synthetic-english'},bank={version,subject:'english',render_layout:'passage-group-single-page',subjects:[{id:'english',title:'英语合成测试'}],sources:[source],knowledgePoints:[],memoryQuestions:[],predictions:[],groups:[],groupReviews:[],questionReviews:[],synthetic:true};
 let next=1;
 function add(type,count,order,title){const gid='synthetic-english-'+type+'-'+order,group={id:gid,subject:'english',paper_type:'english-ii',year:2000,type,order,title,original_text:Array.from({length:type==='cloze'?20:12},(_,i)=>'Synthetic paragraph '+(i+1)+'. This original fixture exists only to exercise a complete material layout, scrolling, answer controls and account boundaries. '+(type==='cloze'?'Blank ['+(i+1)+'] is shown with every other blank.':'No statement in this paragraph is an actual exam quotation.')).join('\n\n'),source_refs:[{id:source.id,locator:'Synthetic locally authored fixture'}],question_ids:[],completeness_status:'complete'};if(type==='reading-b')group.shared_options=Array.from({length:7},(_,i)=>({label:String.fromCharCode(65+i),text:'Shared synthetic option '+String.fromCharCode(65+i)}));
  for(let j=0;j<count;j++){const number=next++,qid=gid+'-q'+number,q={id:qid,subject:'english',paper_type:'english-ii',year:2000,group_id:gid,original_number:number,prompt:'Synthetic task '+number+': exercise the controls without any real exam source.',source_ids:[source.id],note_refs:[],plain_explanation:'Locally authored synthetic UI explanation; no real English content approval.',variants:[{prompt:'Synthetic variant only',answer_delta:'Exercise option persistence under a different synthetic label.'}]};if(type==='translation'||type==='writing'){q.answer_points=[{point:'Synthetic task guidance used only for the interface test.',marks:1}];bank.predictions.push(q)}else{q.options=type==='reading-b'?group.shared_options.map(x=>x.text):['Fixture A has enough words to wrap on a narrow phone without truncating any option text.','Fixture B stays fully visible in the same task page.','Fixture C uses no real uploaded passage.','Fixture D is synthetic and tests only the program.'];q.answer=[0];bank.memoryQuestions.push(q)}group.question_ids.push(qid)}
  bank.groups.push(group);return group;
 }
 add('cloze',20,0,'Synthetic cloze, all20 blanks');for(let i=0;i<4;i++)add('reading-a',5,i+1,'Synthetic complete reading '+(i+1));const matching=add('reading-b',5,5,'Synthetic matching material');add('translation',1,6,'Synthetic complete translation');add('writing',1,7,'Synthetic short writing');add('writing',1,8,'Synthetic long writing');
 if(omitReading){const omitted=bank.groups.find(g=>g.type==='reading-a');bank.groups=bank.groups.filter(g=>g!==omitted);bank.memoryQuestions=bank.memoryQuestions.filter(q=>q.group_id!==omitted.id)}
 if(held){matching.completeness_status='incomplete';matching.disabled_reason='Synthetic missing material corresponding to tasks43–45; the whole group is disabled.';matching.practice_enabled=false;for(const q of bank.memoryQuestions.filter(q=>q.group_id===matching.id)){q.practice_enabled=false;q.disabled_reason=matching.disabled_reason}}
 const sourceSHA=await SubjectPackage.reviewHash(source);let active=0;
 for(const [kind,qs] of [['memoryQuestions',bank.memoryQuestions],['predictions',bank.predictions]])for(const q of qs){if(q.practice_enabled===false)continue;active++;bank.questionReviews.push({id:q.id,kind,binding_algorithm:'typed-tree-ieee754-v1',scope:'whole-question',decision:'passed',author:'synthetic-fixture-author',reviewer:'synthetic-fixture-protocol-reviewer',completed_at:'2000-01-01T00:00:00Z',evidence_artifact_sha256:crypto.createHash('sha256').update('Synthetic-only fixture evidence').digest('hex'),checks:checks(['prompt','answer','explanation','scoring','variants','note_provenance','source_support','original_claim_limits']),question_sha256:await SubjectPackage.reviewHash(q),source_sha256:{[source.id]:sourceSHA},note_record_sha256:{},document_sha256:{},note_basis:'external-source-only'})}
 bank.practiceRelease={format:'question-release-gate-v1',passed:true,active_questions:active,current_bound_reviews:active,disabled_questions:bank.memoryQuestions.length+bank.predictions.length-active,review_index_sha256:crypto.createHash('sha256').update('Synthetic question index').digest('hex')};const qm=new Map([...bank.memoryQuestions,...bank.predictions].map(q=>[q.id,q]));
 for(const g of bank.groups){if(g.completeness_status!=='complete')continue;bank.groupReviews.push({group_id:g.id,binding_algorithm:'typed-tree-ieee754-v1',scope:'whole-material-group',decision:'passed',author:'synthetic-group-author',reviewer:'synthetic-group-protocol-reviewer',completed_at:'2000-01-01T00:00:00Z',evidence_artifact_sha256:crypto.createHash('sha256').update('Synthetic-only group evidence').digest('hex'),checks:checks(EnglishGroups.CHECKS),group_sha256:await SubjectPackage.reviewHash(g),question_sha256:Object.fromEntries(await Promise.all(g.question_ids.map(async id=>[id,await SubjectPackage.reviewHash(qm.get(id))]))),source_sha256:{[source.id]:sourceSHA}})}
 return bank;
}
module.exports={createEnglishFixture};
