/* Purely synthetic three-subject protocol fixtures; no exam/uploaded content. */
const crypto=require('crypto'),P=require('../learning/subject-package.js'),G=require('../learning/english-groups.js'),{createEnglishFixture}=require('./english_test_fixture.cjs');
const check=keys=>Object.fromEntries(keys.map(k=>[k,{status:'passed',evidence:'Synthetic protocol check '+k+'; no real source/content is approved.'}]));
async function make(subject,version=subject+'-room-fixture-v1'){
 let bank;
 if(subject==='english'){bank=await createEnglishFixture({version});const q=bank.memoryQuestions[0],prior=q.id;q.id='common-choice-1';bank.groups.find(g=>g.question_ids.includes(prior)).question_ids[0]=q.id}
 else{const source={id:'room-source',title:'Synthetic '+subject+' source',url:'https://example.invalid/room-'+subject};bank={subject,exam_scope:subject==='politics'?'graduate-politics':'psychology',version,subjects:[{id:subject,title:'Synthetic '+subject}],sources:[source],knowledgePoints:[],memoryQuestions:Array.from({length:6},(_,i)=>({id:'common-choice-'+(i+1),subject,prompt:'Synthetic '+subject+' question '+(i+1),options:['Synthetic A','Synthetic B','Synthetic C','Synthetic D'],answer:[0],plain_explanation:'Synthetic protocol explanation, not real learning content.',variants:['Synthetic variation with answer A.'],source_ids:[source.id],note_refs:[]})),predictions:[{id:'common-essay-1',subject,prompt:'Synthetic '+subject+' complete subjective task',answer_points:[{point:'Synthetic answer point.',marks:1}],training_marks:1,plain_explanation:'Synthetic task guidance.',variants:['Synthetic task variation and answer.'],source_ids:[source.id],note_refs:[]}],frameworks:[],corrections:[],predictionCoverage:[],trend:{notice:'Synthetic fixture only'}}}
 bank.frameworks=[{id:'synthetic-framework',title:'Synthetic '+subject+' framework',body:'Locally authored synthetic structure for UI protocol tests only.',review_status:'synthetic-protocol-only'}];
 if(subject==='english'){const writing=bank.groups.filter(g=>g.type==='writing');writing.forEach((g,i)=>g.writing_type=i?'large':'small');}
 if(subject!=='psychology')bank.trend={title:'Synthetic '+subject+' trend',scope:'Only synthetic locally authored observations; no exam frequency claims.',findings:[{id:subject+'-finding',title:subject+' synthetic observation',text:'Synthetic '+subject+' trend evidence only.',evidence:'Fictional source locator for UI checks.',uncertainty:'No real exam study has been performed.',source_refs:[{id:bank.sources[0].id,locator:'Synthetic '+subject+' section 1'}]}],limitations:['Synthetic only']};
 bank.questionReviews=[];const sources=new Map(await Promise.all(bank.sources.map(async s=>[s.id,await P.reviewHash(s)])));
 for(const [kind,qs] of [['memoryQuestions',bank.memoryQuestions],['predictions',bank.predictions]])for(const q of qs)bank.questionReviews.push({id:q.id,kind,binding_algorithm:'typed-tree-ieee754-v1',scope:'whole-question',decision:'passed',author:'synthetic-protocol-author',reviewer:'synthetic-protocol-reviewer',completed_at:'2000-01-01T00:00:00Z',evidence_artifact_sha256:crypto.createHash('sha256').update('Synthetic room fixture').digest('hex'),checks:check(['prompt','answer','explanation','scoring','variants','note_provenance','source_support','original_claim_limits']),question_sha256:await P.reviewHash(q),source_sha256:Object.fromEntries(q.source_ids.map(id=>[id,sources.get(id)])),note_record_sha256:{},document_sha256:{},note_basis:'external-source-only'});
 const count=bank.memoryQuestions.length+bank.predictions.length;bank.practiceRelease={format:'question-release-gate-v1',passed:true,active_questions:count,current_bound_reviews:count,disabled_questions:0,review_index_sha256:'a'.repeat(64)};
 if(subject==='english'){const qm=new Map([...bank.memoryQuestions,...bank.predictions].map(q=>[q.id,q]));bank.groupReviews=[];for(const g of bank.groups)bank.groupReviews.push({group_id:g.id,binding_algorithm:'typed-tree-ieee754-v1',scope:'whole-material-group',decision:'passed',author:'synthetic-group-author',reviewer:'synthetic-group-reviewer',completed_at:'2000-01-01T00:00:00Z',evidence_artifact_sha256:'b'.repeat(64),checks:check(G.CHECKS),group_sha256:await P.reviewHash(g),question_sha256:Object.fromEntries(await Promise.all(g.question_ids.map(async id=>[id,await P.reviewHash(qm.get(id))]))),source_sha256:Object.fromEntries(g.source_refs.map(r=>[r.id,sources.get(r.id)]))})}
 return bank;
}
module.exports={make};
