/* Pure synthetic regression of the real shared classifier and framework catalog. */
const assert=require('node:assert/strict'),fs=require('fs'),vm=require('vm'),G=require('../learning/english-groups.js'),P=require('../learning/subject-package.js'),{createEnglishFixture}=require('./english_test_fixture.cjs');
const context={window:{EnglishGroups:G}};const source=fs.readFileSync(require.resolve('../learning/subject-room.js'),'utf8').replace('root.SubjectRoom={','root.FrameworkTest={render:englishFrameworks};root.SubjectRoom={');vm.runInNewContext(source,context);const render=context.window.FrameworkTest.render;
(async()=>{
 const bank=await createEnglishFixture({frameworkGroups:true}),qa=await P.auditQuestionReviews(bank),ga=await G.audit(bank,qa,P),frameworks=ga.groups.filter(g=>G.writingType(bank,g,ga.byQuestion)==='framework');assert.equal(frameworks.length,2);assert.equal(bank.frameworks,undefined);let html=render(bank,qa,ga);assert.equal((html.match(/data-english-framework-group=/g)||[]).length,2);assert(!html.includes('尚未导入'));for(const g of frameworks){assert(html.includes(g.id));assert(html.includes(g.question_ids[0]));assert(html.includes('Synthetic functional framework reference'));assert(html.includes('完整材料组与子题审校均通过'))}
 // Actual writing tasks never become framework documents by title, year, or mere existence.
 const ordinary={...bank,writingClassification:[]};html=render(ordinary,qa,ga);assert(html.includes('尚未导入'));assert(!html.includes('data-english-framework-group='));ordinary.frameworks=[{id:'translation-only',module:'translation',title:'Translation framework',body:'TRANSLATION MUST NOT APPEAR'}];assert(!render(ordinary,qa,ga).includes('TRANSLATION MUST NOT APPEAR'));
 // Native documents retain priority and stable-ID deduplication; training material is not a passed question.
 const native={...bank,frameworks:[{id:frameworks[0].id,title:'Native document',body:'NATIVE PRIORITY <script>unsafe</script>'},{id:'native-alias',group_id:frameworks[0].id,title:'Duplicate alias',body:'DUPLICATE MUST NOT APPEAR'},{id:'translation',module:'translation',title:'Excluded',body:'TRANSLATION MUST NOT APPEAR'}]};html=render(native,qa,ga);assert(html.includes('NATIVE PRIORITY &lt;script&gt;unsafe&lt;/script&gt;'));assert(!html.includes('DUPLICATE MUST NOT APPEAR'));assert(!html.includes('TRANSLATION MUST NOT APPEAR'));assert.equal((html.match(/data-english-framework-native=/g)||[]).length,1);assert.equal((html.match(/data-english-framework-group=/g)||[]).length,1);assert(html.includes('不代替逐题门禁'));
 // Stale group proof must not expose the newly edited task body or reference; honest unavailable state replaces false empty.
 const stale=structuredClone(bank),group=stale.groups.find(g=>g.id===frameworks[0].id);group.original_text='STALE UNREVIEWED FRAMEWORK BODY';const staleQ=await P.auditQuestionReviews(stale),staleG=await G.audit(stale,staleQ,P);html=render(stale,staleQ,staleG);assert(html.includes('框架任务暂不可用'));assert(!html.includes('STALE UNREVIEWED FRAMEWORK BODY'));assert(!html.includes('尚未导入'));assert(!html.includes('data-framework-task-open="'+group.id+'"'));
 const noProof=structuredClone(bank);noProof.groupReviews=[];const npQ=await P.auditQuestionReviews(noProof),npG=await G.audit(noProof,npQ,P);html=render(noProof,npQ,npG);assert.equal((html.match(/data-framework-unavailable=/g)||[]).length,2);assert(!html.includes('Synthetic functional framework reference'));assert(!html.includes('data-framework-task-open='));assert(!html.includes('尚未导入'));
 const disabled=structuredClone(bank),held=disabled.groups.find(g=>g.id===frameworks[0].id);held.practice_enabled=false;held.original_text='DISABLED MATERIAL MUST NOT APPEAR';disabled.frameworks=[{id:held.id,title:'Native linked to disabled group',body:'NATIVE BYPASS MUST NOT APPEAR'}];const dQ=await P.auditQuestionReviews(disabled),dG=await G.audit(disabled,dQ,P);html=render(disabled,dQ,dG);assert(html.includes('框架任务暂不可用'));assert(!html.includes('DISABLED MATERIAL MUST NOT APPEAR'));assert(!html.includes('NATIVE BYPASS MUST NOT APPEAR'));assert(!html.includes('尚未导入'));
 const disabledQ=structuredClone(bank);disabledQ.predictions.find(q=>q.id===frameworks[0].question_ids[0]).practice_enabled=false;const dq=await P.auditQuestionReviews(disabledQ),dg=await G.audit(disabledQ,dq,P);html=render(disabledQ,dq,dg);assert(html.includes('框架任务暂不可用'));assert(!html.includes('data-framework-task-open="'+frameworks[0].id+'"'));
 console.log('PASS: classified framework projection, complete content/provenance/task links, native precedence/dedup, honest absence, current dual gates, stale/missing/disabled proof protection and safe text');
})().catch(e=>{console.error(e);process.exitCode=1});
