/* Isolated development Chrome, production UI/app/sync, synthetic RPC. No owner profile. */
const {chromium}=require(process.env.PLAYWRIGHT_MODULE_PATH||'playwright');
const fs=require('node:fs'),path=require('node:path'),os=require('node:os'),cp=require('node:child_process'),http=require('node:http'),assert=require('node:assert/strict'),{createHash}=require('node:crypto');
const root=path.resolve(__dirname,'..'),out=path.join(root,'private/subject-package-browser-check'),temp=fs.mkdtempSync(path.join(os.tmpdir(),'subject-package-browser-'));
const project='https://fixture-project.supabase.co',uid='10000000-0000-4000-8000-000000000001',accountKey='psychology-learning-v2-user-'+uid;
const answer={correct:false,firstCorrect:false,attempts:1,selected:[1],time:'2026-10-03T00:00:00Z'},seed={version:2,answers:{'fixture-Q':answer,'CL-SUBJ-0120':{...answer,score:9,max_score:12,content_version:'v13'},'CL-SUBJ-0129':{...answer,score:6,max_score:12,content_version:'v13'}},wrong:['fixture-Q'],favorites:['fixture-Q'],notes:{'fixture-E':{text:'保留合成主观题草稿',time:'2026-10-03T00:00:00Z'}},legacyRecords:{unknown:{kept:true}},updatedAt:'2026-10-03T00:00:00Z'};
const old={version:'legacy-fixture-v0',subjects:[{id:'fixture',title:'合成学科'}],sources:[],knowledgePoints:[],memoryQuestions:[{id:'fixture-Q',subject:'fixture',prompt:'合成旧版选择题',options:['甲','乙'],answer:[0],review_status:'verified'}],predictions:[{id:'fixture-E',subject:'fixture',prompt:'合成旧版主观题',answer_points:['合成要点'],review_status:'needs-review'}]};
const generate=`import sys,json,base64,hashlib\nsys.path.insert(0,sys.argv[1]);from build_subject_package import build\nfrom pathlib import Path\np=Path(sys.argv[2]);raw=b'PK\\x03\\x04'+b'synthetic-word'*30000\nfor subject,version in [('psychology','v1'),('psychology','v2'),('psychology','v3'),('psychology','v4'),('psychology','v5'),('politics','v1'),('english','v1')]:\n bank={'version':subject+'-'+version,'subjects':[{'id':'fixture','title':'合成学科'}],'sources':[],'knowledgePoints':[],'memoryQuestions':[{'id':'fixture-Q' if i==0 else 'fixture-Q'+str(i),'subject':'fixture','prompt':'合成新版选择题 '+str(i),'options':['甲','乙'],'answer':[0],'review_status':'verified','plain_explanation':'合成工程填充'*300} for i in range(30)],'predictions':[{'id':'fixture-E','subject':'fixture','prompt':'合成新版主观题','answer_points':['合成要点'],'review_status':'needs-review'}],'trend':{'notice':'工程fixture'}}\n build(subject,subject+'-'+version,bank,{'records':[{'id':'fixture-note','text':version}]},{'version':1,'documents':[{'file_name':'fixture.docx','sha256':hashlib.sha256(raw).hexdigest(),'base64':base64.b64encode(raw).decode()}]},{'status':'incomplete','scope':'仅合成工程fixture','limitations':['不是最终题库']},p/(subject+'-'+version+'.zip'))\n`;
cp.execFileSync('python3',['-c',generate,path.join(root,'scripts'),temp]);
const harness=`<!doctype html><html><head><meta name="viewport" content="width=device-width, initial-scale=1"><link rel="stylesheet" href="/learning/style.css"></head><body><button id="saveStatus"></button><section id="managePanel"><div id="managerBankSection"><div id="managerVersionSection"></div><div id="contentImportCards" class="import-grid"></div><button id="refreshPrivate">加载已导入内容</button><p id="importOverview"></p></div></section><section id="privateApp"></section><script src="/learning/shell.js"></script><script>document.getElementById('privateApp').innerHTML=window.STUDY_SHELL;window.PSYCH_SYNC_CONFIG={url:'${project}',publishableKey:'sb_publishable_fixture'};</script><script src="/learning/subject-package.js"></script><script src="/learning/sync.js"></script><script src="/learning/manager.js"></script><script>window.PsychSync.getStatus().then(()=>window.PrivateContentManager.initialize(window.PsychSync,()=>true));</script><script src="/learning/native-subjective-view.js"></script><script src="/learning/app.js"></script></body></html>`;
const server=http.createServer((req,res)=>{const name=new URL(req.url,'http://local').pathname;if(name==='/'){res.setHeader('Content-Type','text/html; charset=utf-8');return res.end(harness)}if(!/^\/learning\/(app|style|shell|sync|manager|subject-package|native-subjective-view)\.(js|css)$/.test(name)){res.statusCode=404;return res.end()}res.setHeader('Content-Type',name.endsWith('.css')?'text/css':'text/javascript; charset=utf-8');res.end(fs.readFileSync(path.join(root,name)))});
(async()=>{await new Promise(r=>server.listen(0,'127.0.0.1',r));const base='http://127.0.0.1:'+server.address().port;let browser;const uploads=new Map(),active=new Map(),calls=[],checks=[],errors=[];let failPut=false,timeoutCommit=false,lostCommit=false,delayPut=0,tamperRead=false,unavailable=false,offline=false,revoked=false;
const studyRemote={revision:1,state:structuredClone({answers:seed.answers,wrong:seed.wrong,favorites:seed.favorites}),ids:new Set()};
const manifest=subject=>{const u=active.get(subject);return u?{package_id:u.id,sha256:u.sha,manifest_text:u.text,baseline:'package:'+u.sha}:{available:false,subject,baseline:'legacy:'+subject}};
try{browser=await chromium.launch({headless:true,...(process.env.CHROME_BINARY?{executablePath:process.env.CHROME_BINARY}:{})});const context=await browser.newContext({viewport:{width:390,height:844}});
await context.addInitScript(({project,uid,accountKey,seed})=>{if(localStorage.getItem('fixture-initialized'))return;localStorage.setItem('fixture-initialized','yes');localStorage.setItem('psychology-sync-session-v1:'+project,JSON.stringify({access_token:'synthetic-not-real',refresh_token:'synthetic-not-real',expires_at:Date.now()/1000+3600,user:{id:uid,email:'fixture@example.invalid'}}));localStorage.setItem(accountKey,JSON.stringify(seed))},{project,uid,accountKey,seed});
await context.route('**/*',async route=>{const url=new URL(route.request().url());if(url.origin===base)return route.continue();if(url.origin!==project)return route.abort();let body=route.request().postDataJSON(),result,status=200;calls.push({rpc:url.pathname,index:body.p_index,subject:body.p_subject});
if(offline)return route.abort('failed');if(revoked&&url.pathname.endsWith('get_study_state'))return route.fulfill({status:403,contentType:'application/json',body:JSON.stringify({code:'42501',message:'synthetic revoked'})});
if(url.pathname.endsWith('get_study_state'))result={user_id:uid,revision:studyRemote.revision,state:structuredClone(studyRemote.state)};
else if(url.pathname.endsWith('submit_study_batch')){const accepted=body.operations.filter(op=>studyRemote.ids.has(op.id)).map(op=>op.id),fresh=body.operations.filter(op=>!studyRemote.ids.has(op.id));if(fresh.length&&body.expected_revision!==studyRemote.revision)result={status:'conflict',revision:studyRemote.revision,state:structuredClone(studyRemote.state),accepted};else{for(const op of fresh){studyRemote.ids.add(op.id);accepted.push(op.id);studyRemote.revision++;if(op.kind==='answer'||op.kind==='import_answer')studyRemote.state.answers[op.target]={...op.payload,attempts:op.kind==='import_answer'?op.payload.attempts:(studyRemote.state.answers[op.target]?.attempts||0)+1,time:op.payload.time||'2026-10-03T00:00:00Z'};else{const key=op.kind==='favorite'?'favorites':'wrong';studyRemote.state[key]=studyRemote.state[key].filter(id=>id!==op.target);if(op.payload.value)studyRemote.state[key].push(op.target)}}result={status:'ok',revision:studyRemote.revision,state:structuredClone(studyRemote.state),accepted}}}
else if(url.pathname.endsWith('study_get_subject_package')){if(unavailable){result={code:'PGRST202',message:'synthetic missing migration'};status=404}else result=manifest(body.p_subject)}
else if(url.pathname.endsWith('study_get_content_manifest')){result={code:'P0002'};status=404}
else if(url.pathname.endsWith('study_get_private_content'))result=old;
else if(url.pathname.endsWith('study_begin_subject_package')){const m=JSON.parse(body.p_manifest),sha=createHash('sha256').update(body.p_manifest).digest('hex');let u=uploads.get(sha);if(!u){u={id:sha,sha,m,text:body.p_manifest,baseline:body.p_expected_baseline,parts:new Map()};uploads.set(sha,u)}result={package_id:u.id,sha256:sha,received:[...u.parts.keys()]}}
else if(url.pathname.endsWith('study_put_subject_object')){const u=uploads.get(body.p_package),o=u.m.objects[body.p_index],bytes=Buffer.from(body.p_base64,'base64');assert.equal(createHash('sha256').update(bytes).digest('hex'),o.sha256);assert.equal(bytes.length,o.bytes);u.parts.set(o.index,bytes);if(delayPut)await new Promise(r=>setTimeout(r,delayPut));if(failPut&&o.index===3){failPut=false;return route.abort('failed')}result={received:true,index:o.index,sha256:o.sha256}}
else if(url.pathname.endsWith('study_verify_subject_asset')){const u=uploads.get(body.p_package),parts=u.m.objects.filter(o=>o.role==='asset'&&o.field===body.p_field),raw=Buffer.concat(parts.map(o=>u.parts.get(o.index)));result={verified:true,field:body.p_field,sha256:createHash('sha256').update(raw).digest('hex')}}
else if(url.pathname.endsWith('study_commit_subject_package')){const u=uploads.get(body.p_package);assert.equal(u.parts.size,u.m.objects.length);if(timeoutCommit){timeoutCommit=false;result={code:'57014',message:'synthetic timeout'};status=500}else if(manifest(u.m.subject).baseline!==u.baseline){result={code:'40001',message:'synthetic stale baseline'};status=400}else{active.set(u.m.subject,u);if(lostCommit){lostCommit=false;return route.abort('failed')}result={saved:true,subject:u.m.subject,sha256:u.sha}}}
else if(url.pathname.endsWith('study_get_subject_object')){const u=uploads.get(body.p_package),o=u.m.objects[body.p_index];result={index:o.index,sha256:o.sha256,base64:(tamperRead?Buffer.from('altered'):u.parts.get(o.index)).toString('base64')}}
else throw Error('Unexpected synthetic endpoint '+url.pathname);
try{await route.fulfill({status,contentType:'application/json',body:JSON.stringify(result)})}catch(error){if(!/closed|disposed|cancel|Invalid Interception/i.test(error.message))throw error}
});
let page=await context.newPage();page.on('pageerror',e=>errors.push(e.message));await page.goto(base+'/#memory');await page.waitForSelector('[data-choice]');await page.waitForSelector('#subjectPackageFile',{state:'attached'});
const status=()=>page.locator('#subjectPackageStatus'),send=()=>page.locator('#uploadSubjectPackage'),pick=async(subject,v)=>{await page.locator('#subjectPackageFile').setInputFiles(path.join(temp,subject+'-'+v+'.zip'));await send().waitFor({state:'visible'});await page.waitForFunction(()=>!document.getElementById('uploadSubjectPackage').disabled)},saved=async()=>page.waitForFunction(()=>document.getElementById('subjectPackageStatus').textContent.includes('服务端已确认本科完整版本'));
const record=()=>page.evaluate(k=>JSON.parse(localStorage.getItem(k)),accountKey);const preTentativeRecord=await record();assert((await page.locator('#content article.card').first().textContent()).includes('当前整题独立审核证据待补'));await page.locator('[data-choice]').first().click();await page.locator('[data-submit]').first().click();assert.deepEqual(await record(),preTentativeRecord);assert((await page.locator('#metrics').textContent()).includes('整题审核通过'));checks.push('historical verified label without current whole-question proof remains tentative and cannot create practice results');await page.locator('[data-retry]').first().click();await page.locator('[data-view="predictions"]').click();await page.locator('details:has([data-note]) summary').click();await page.locator('[data-note="fixture-E"]').fill('刚输入的合成主观题草稿');await page.locator('[data-view="memory"]').click();await page.locator('[data-choice="fixture-Q"][data-index="1"]').click();const baselineRecord=await record();assert.equal(await page.locator('[data-choice="fixture-Q"][data-index="1"]').getAttribute('aria-pressed'),'true');assert.equal(await page.locator('#legacyContentImport').getAttribute('open'),null);checks.push('one primary complete-package card; legacy imports collapsed; freshly typed draft saved before update');
await page.waitForTimeout(1300);if(process.env.PRIVATE_SUBJECT_PACKAGE_TEST_FILE){const beforeSelection=calls.length;await page.locator('#subjectPackageFile').setInputFiles(process.env.PRIVATE_SUBJECT_PACKAGE_TEST_FILE);await pick('english','v1');await page.waitForTimeout(2200);assert((await status().textContent()).includes('科目：英语'));assert.equal(calls.length,beforeSelection);checks.push('late validation of replaced file cannot overwrite the newly selected subject');}
let count=calls.length;await pick('psychology','v1');assert.equal(calls.length,count,'file selection performed network request');assert((await status().textContent()).includes('尚未完成'));checks.push('file selection local-only; file integrity distinct from incomplete semantic review');
failPut=true;await send().click();await page.waitForFunction(()=>document.getElementById('subjectPackageStatus').textContent.includes('导入失败'));assert.equal(active.size,0);assert((await page.locator('#version').textContent()).includes('legacy-fixture-v0'));assert.equal(await page.locator('[data-choice="fixture-Q"][data-index="1"]').getAttribute('aria-pressed'),'true');checks.push('interrupted object upload leaves legacy bank and unsubmitted selection active');
count=calls.length;await send().click();await saved();assert(!calls.slice(count).some(c=>c.rpc.endsWith('study_put_subject_object')&&c.index<=3));assert((await page.locator('#version').textContent()).includes('legacy-fixture-v0'));checks.push('retry resumes server receipts; success waits for manual content switch');
await page.locator('#refreshPrivate').click();await page.waitForFunction(()=>document.getElementById('version').textContent.includes('psychology-v1'));assert.equal(await page.locator('[data-choice="fixture-Q"][data-index="1"]').getAttribute('aria-pressed'),'false');assert.equal((await page.evaluate(()=>window.PsychSync.getPrivateContent('notes'))).records[0].text,'v1');const docs=await page.evaluate(()=>window.PsychSync.getPrivateContent('documents'));assert.equal(Buffer.from(docs.documents[0].base64,'base64').length,420004);checks.push('single-file import and manual switch read exact bank, notes and split Word');
count=calls.length;await page.reload();await page.waitForFunction(()=>document.getElementById('version').textContent.includes('psychology-v1'));await page.waitForSelector('#subjectPackageFile',{state:'attached'});assert.equal(calls.slice(count).filter(c=>c.rpc.endsWith('study_get_subject_object')).length,0);assert(calls.slice(count).some(c=>c.rpc.endsWith('get_study_state')));checks.push('real Chrome IndexedDB warm refresh: zero object RPCs after authenticated owner check; notes/Word stay lazy');
count=calls.length;await page.evaluate(async()=>{await window.PsychSync.getPrivateContent('notes');await window.PsychSync.getPrivateContent('documents')});assert.equal(calls.slice(count).filter(c=>c.rpc.endsWith('study_get_subject_object')).length,0);checks.push('previously requested lazy notes/Word reuse verified object cache');

await pick('psychology','v2');timeoutCommit=true;await send().click();await page.waitForFunction(()=>document.getElementById('subjectPackageStatus').textContent.includes('导入失败'));assert.equal(active.get('psychology').m.package_version,'psychology-v1');assert((await page.locator('#version').textContent()).includes('psychology-v1'));count=calls.length;await send().click();await saved();assert(!calls.slice(count).some(c=>c.rpc.endsWith('study_put_subject_object')));assert.equal((await page.evaluate(()=>window.PsychSync.getPrivateContent('notes'))).records[0].text,'v1');checks.push('57014 final commit failure keeps old pointer; zero-reupload retry; selected notes remain pinned');
await page.locator('#checkContentVersion').click();await page.waitForSelector('#switchContentVersion');await page.evaluate(async({project,uid,sha})=>{const db=await new Promise((resolve,reject)=>{const r=indexedDB.open('psychology-private-content-v1:'+JSON.stringify([project,uid]));r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error)});await new Promise((resolve,reject)=>{const tx=db.transaction('entries','readwrite'),req=tx.objectStore('entries').openCursor();req.onsuccess=()=>{const c=req.result;if(!c)return;const e=c.value;if(e.kind==='package-object'&&e.package_sha256===sha&&e.component==='bank'){e.body=new Uint8Array([0]);c.update(e)}c.continue()};tx.oncomplete=resolve;tx.onerror=()=>reject(tx.error)});db.close()},{project,uid,sha:active.get('psychology').sha});tamperRead=true;await page.locator('#switchContentVersion').click();await page.waitForFunction(()=>document.getElementById('privateReadStatus')?.textContent.includes('题库读取未完成'));assert((await page.locator('#version').textContent()).includes('psychology-v1'));tamperRead=false;await page.evaluate(()=>window.reloadPrivateStudy({preferLatest:true}));assert((await page.locator('#version').textContent()).includes('psychology-v2'));checks.push('tampered download refuses switch and preserves prior bank; verified retry succeeds');
await pick('psychology','v3');delayPut=30;count=calls.filter(c=>c.rpc.endsWith('study_begin_subject_package')).length;await page.evaluate(()=>{const b=document.getElementById('uploadSubjectPackage');b.click();b.click()});await saved();assert.equal(calls.filter(c=>c.rpc.endsWith('study_begin_subject_package')).length-count,1);delayPut=0;checks.push('duplicate click starts one upload');
await pick('psychology','v4');delayPut=100;const interruptStart=calls.length;await send().click();for(let i=0;i<100&&!calls.slice(interruptStart).some(c=>c.rpc.endsWith('study_put_subject_object')&&c.index===3);i++)await page.waitForTimeout(20);await page.reload();delayPut=0;await page.waitForSelector('[data-choice]');await page.waitForSelector('#subjectPackageFile',{state:'attached'});await pick('psychology','v4');count=calls.length;await send().click();await saved();assert.equal(active.get('psychology').m.package_version,'psychology-v4');checks.push('refresh during upload and file reselection resume immutable server draft');
await pick('psychology','v5');lostCommit=true;await send().click();await saved();assert.equal(active.get('psychology').m.package_version,'psychology-v5');checks.push('lost activation response resolved using authoritative subject pointer');
const psychSHA=active.get('psychology').sha;for(const subject of ['politics','english']){await pick(subject,'v1');await send().click();await saved();assert.equal(active.get('psychology').sha,psychSHA)}checks.push('politics and English independently activated without overwriting psychology');
const after=await record();for(const field of ['answers','wrong','favorites','notes','legacyRecords'])assert.deepEqual(after[field],baselineRecord[field]);checks.push('answers, favorites, wrong list, unmatched history and subjective drafts preserved');assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth+1),false);checks.push('390px mobile import and learning layout have no horizontal overflow');
if(process.env.PRIVATE_SUBJECT_PACKAGE_TEST_FILE){
 const fixture=path.resolve(process.env.PRIVATE_SUBJECT_PACKAGE_TEST_FILE);await page.locator('#subjectPackageFile').setInputFiles(fixture);await page.waitForFunction(()=>!document.getElementById('uploadSubjectPackage').disabled);const before=calls.length;await send().click();await saved();await page.locator('#refreshPrivate').click();await page.waitForFunction(()=>document.getElementById('version').textContent.includes('内容版本')&&!document.getElementById('privateReadStatus')?.textContent.includes('未完成'));const actual=await page.evaluate(async()=>{await window.reloadPrivateStudy({preferLatest:true});const bank=await window.PsychSync.getPrivateContent('psychology');window.validatePrivateStudyPayload(bank);const notes=await window.PsychSync.getPrivateContent('notes'),docs=await window.PsychSync.getPrivateContent('documents');return {mc:bank.memoryQuestions.length,essay:bank.predictions.length,notes:notes.records.length,words:docs.documents.length}});if(actual.mc!==3024){fs.mkdirSync(out,{recursive:true});fs.writeFileSync(path.join(out,'final-read-failure.json'),JSON.stringify({actual,ui:await page.locator('#privateReadStatus').textContent(),packageStatus:await page.locator('#subjectPackageStatus').textContent(),version:await page.locator('#version').textContent(),active_manifest_sha:active.get('psychology')?.sha,errors},null,2));}assert.deepEqual(actual,{mc:3024,essay:895,notes:8876,words:8});const warmStart=calls.length;await page.reload();await page.waitForSelector('#content [data-choice]',{timeout:180000});assert.equal(calls.slice(warmStart).filter(c=>c.rpc.endsWith('study_get_subject_object')).length,0);assert(calls.slice(warmStart).some(c=>c.rpc.endsWith('get_study_state')));checks.push('full private bank warm reload: zero bank/notes/Word object requests; authenticated owner and manifest still checked');const afterReal=await record();for(const field of ['answers','wrong','favorites','notes','legacyRecords'])assert.deepEqual(afterReal[field],baselineRecord[field]);assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth+1),false);checks.push('real-sized private package: 3024 MC / 895 essays / 8876 notes / 8 Word, production browser reads and validates all components; record/draft/mobile preservation');let formalReview=null;if(process.env.REQUIRE_FORMAL_REVIEW==='true'){
 await page.locator('[data-view="memory"]').click();await page.waitForSelector('#content [data-choice]');
 const qid=await page.locator('#content [data-choice]').first().getAttribute('data-choice');
 const audited=await page.evaluate(async id=>{const b=await window.PsychSync.getPrivateContent('psychology'),n=await window.PsychSync.getPrivateContent('notes'),d=await window.PsychSync.getPrivateContent('documents');const r=await window.SubjectPackage.auditQuestionReviews(b,{notes:n,documents:d});const q=b.memoryQuestions.find(x=>x.id===id);return {complete:r.complete,passed:r.passed,answer:q.answer,question_id:q.id}},qid);
 assert.equal(audited.complete,true);assert.equal(audited.passed,3918);for(const index of audited.answer)await page.locator(`[data-choice="${qid}"][data-index="${index}"]`).click();await page.locator(`[data-submit="${qid}"]`).click();const graded=await record();assert.equal(graded.answers[qid].correct,true);assert.equal(graded.answers[qid].attempts,1);for(const [id,value] of Object.entries(baselineRecord.answers))assert.deepEqual(graded.answers[id],value);assert.deepEqual(graded.notes,baselineRecord.notes);const scoreHistory=graded.legacyRecords.score_history_v1||[];for(const id of ['CL-SUBJ-0120','CL-SUBJ-0129']){const historical=scoreHistory.find(r=>r.question_id===id&&r.record_kind==='answers');assert(historical);assert.equal(historical.record.max_score,12);assert.equal(historical.record.content_version,'v13');const currentMarks=await page.evaluate(async id=>(await window.PsychSync.getPrivateContent('psychology')).predictions.find(q=>q.id===id).training_marks,id);assert.equal(currentMarks,15);}formalReview={complete:true,clinical_v13_max12_history_preserved_under_v14_max15:true,current_bound_reviews:audited.passed,real_question_correct_answer_saved:true,unmatched_history_and_drafts_preserved:true};checks.push('final-input whole-question release gate: 3918 active reviews bound to all current questions, sources, notes and Word versions; genuine current question answer saved while history/drafts retained');
 }
 fs.mkdirSync(out,{recursive:true});fs.writeFileSync(path.join(out,'real-sized-result.json'),JSON.stringify({passed:true,counts:actual,object_upload_requests:calls.slice(before).filter(c=>c.rpc.endsWith('study_put_subject_object')).length,warm_refresh_object_requests:0,warm_refresh_object_response_bytes:0,authenticated_manifest_checks:true,lazy_notes_words:true,real_remote:false,technical_fixture_only:!formalReview,formal_review:formalReview},null,2));
}
unavailable=true;await pick('psychology','v1');count=calls.length;await send().click();await page.waitForFunction(()=>document.getElementById('subjectPackageStatus').textContent.includes('尚未安装'));assert(!calls.slice(count).some(c=>/study_commit_(content|subjective)_upload/.test(c.rpc)));unavailable=false;checks.push('missing migration explicitly refuses import without old-commit fallback');

if(!process.env.PRIVATE_SUBJECT_PACKAGE_TEST_FILE){
const oldSelected=await page.evaluate(()=>window.PsychSync.getPrivateContent('psychology').then(b=>b.version));
const rejected=await page.evaluate(async()=>{try{await window.PsychSync.getPrivateContent('psychology',()=>{},{preferLatest:true,validatePayload:()=>{throw Error('synthetic validator refused')}});return false}catch(e){return e.message.includes('synthetic validator refused')}});assert(rejected);await page.reload();await page.waitForSelector('[data-choice]');assert((await page.locator('#version').textContent()).includes(oldSelected));checks.push('rejected new-version validator never commits selected pointer; cold reload retains prior version');
// Remove one verified object only: repair must fetch exactly one object.
await page.evaluate(async({project,uid})=>{const db=await new Promise(r=>{const q=indexedDB.open('psychology-private-content-v1:'+JSON.stringify([project,uid]));q.onsuccess=()=>r(q.result)});await new Promise(r=>{const tx=db.transaction(['selected','entries'],'readwrite'),q=tx.objectStore('selected').get('package:psychology');q.onsuccess=()=>{let changed=false;const c=tx.objectStore('entries').openCursor();c.onsuccess=()=>{const x=c.result;if(!x)return;const e=x.value;if(!changed&&e.kind==='package-object'&&e.package_sha256===q.result.sha256&&e.component==='bank'){e.body=new Uint8Array([0]);x.update(e);changed=true}x.continue()}};tx.oncomplete=r});db.close()},{project,uid});count=calls.length;const repaired=await page.evaluate(async()=>{let progress;await window.PsychSync.getPrivateContent('psychology',p=>progress=p);return progress});assert.equal(repaired.downloadedObjects,1);assert.equal(calls.slice(count).filter(c=>c.rpc.endsWith('study_get_subject_object')).length,1);checks.push('one corrupt cached object refetches exactly one object and repairs its SHA');
await page.evaluate(()=>{window.fixtureTransaction=IDBDatabase.prototype.transaction;IDBDatabase.prototype.transaction=function(stores,mode,...args){if(mode==='readwrite')throw new DOMException('synthetic quota','QuotaExceededError');return window.fixtureTransaction.call(this,stores,mode,...args)}});const quota=await page.evaluate(async()=>{let p;const value=await window.PsychSync.getPrivateContent('psychology',x=>p=x,{preferLatest:true});return {version:value.version,progress:p}});assert.equal(quota.progress.cacheStored,false);assert(quota.progress.cacheWarning.includes('空间不足'));await page.evaluate(()=>{IDBDatabase.prototype.transaction=window.fixtureTransaction});await page.reload();await page.waitForSelector('[data-choice]');assert((await page.locator('#version').textContent()).includes(oldSelected));checks.push('quota failure leaves validated content usable with explicit warning and old persistent selected version');
const onlineVersion=await page.locator('#version').textContent();offline=true;count=calls.length;assert(await page.evaluate(async()=>{try{await window.PsychSync.getPrivateContent('psychology');return false}catch{return true}}));assert.equal(await page.locator('#version').textContent(),onlineVersion);assert.equal(calls.slice(count).filter(c=>c.rpc.endsWith('study_get_subject_object')).length,0);await page.reload();await page.waitForTimeout(500);assert.equal(await page.locator('[data-choice]').count(),0);offline=false;await page.reload();await page.waitForSelector('[data-choice]');checks.push('offline existing display retained; cold offline start refuses private cache without live authorization; reconnect reuses cache');
revoked=true;assert(await page.evaluate(async()=>{try{await window.PsychSync.getPrivateContent('psychology');return false}catch{return true}}));assert.equal((await page.evaluate(()=>window.PsychSync.getStatus())).authenticated,false);assert.equal(await page.evaluate(async({project,uid})=>(await indexedDB.databases()).some(x=>x.name==='psychology-private-content-v1:'+JSON.stringify([project,uid])),{project,uid}),false);assert.deepEqual((await record()).notes,baselineRecord.notes);checks.push('server permission revocation rejects cache, drops session and deletes owner DB while preserving drafts');
}
assert.deepEqual(errors,[]);fs.mkdirSync(out,{recursive:true});await page.screenshot({path:path.join(out,'mobile-complete-package.png'),fullPage:false});fs.writeFileSync(path.join(out,'result.json'),JSON.stringify({passed:true,production_ui_app_sync:true,mocked_transport:true,real_owner_or_remote:false,viewport:{width:390,height:844},checks},null,2));console.log('PASS: '+checks.join('; '));await context.close();
}finally{if(browser)await browser.close();await new Promise(r=>server.close(r));fs.rmSync(temp,{recursive:true,force:true})}})().catch(e=>{console.error(e);process.exitCode=1});
