// Local synthetic bank only. No live accounts, network services or private content.
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),http=require('node:http');
const {chromium}=require(process.env.PLAYWRIGHT_MODULE_PATH||'playwright');
const root=path.resolve(__dirname,'..'),out=process.env.QUESTION_NUMBER_EVIDENCE_DIR||path.join(root,'private/question-number-check');
const target='fixture-choice-014',essay='fixture-essay-002',longId='fixture-choice-'+ 'long-stable-id-'.repeat(9);
const fixture={version:'synthetic-v1',build:'local question number test',subjects:[{id:'alpha',title:'测试甲科'},{id:'beta',title:'测试乙科'}],sources:[],knowledgePoints:[],corrections:[],predictionCoverage:[],trend:{},memoryQuestions:Array.from({length:15},(_,i)=>({id:i===14?longId:i===0?'fixture-escape-<>&\"\'':`fixture-choice-${String(i+1).padStart(3,'0')}`,subject:i%2?'beta':'alpha',prompt:`合成选择题 ${i+1}`,options:['测试甲','测试乙'],answer:[0],review_status:i%2?'verified':'needs-review',option_explanations:['解释甲','解释乙']})),predictions:Array.from({length:3},(_,i)=>({id:`fixture-essay-${String(i+1).padStart(3,'0')}`,subject:i%2?'beta':'alpha',prompt:`合成主观题 ${i+1}`,answer_points:['合成要点'],review_status:'verified',forecast:{knowledge_point_range:[40,60]}}))};
const harness=`<!doctype html><html><head><meta name="viewport" content="width=device-width,initial-scale=1"><link rel="stylesheet" href="/learning/style.css"></head><body><button id="saveStatus"></button><script src="/learning/shell.js"></script><script>document.body.insertAdjacentHTML('beforeend',window.STUDY_SHELL);window.fixture=${JSON.stringify(fixture)};window.PsychSync={getStatus:async()=>({authenticated:true,user_id:'synthetic-test',readOnly:true,message:'本地合成验证'}),getAccountState:async()=>null,getPrivateContent:async(key,progress,options)=>{const bank=JSON.parse(JSON.stringify(window.fixture));if(options.preferLatest){bank.version='synthetic-v2';bank.memoryQuestions.reverse();bank.predictions.reverse()}return bank}};</script><script src="/learning/app.js"></script></body></html>`;
const server=http.createServer((req,res)=>{const filename=new URL(req.url,'http://local').pathname;if(filename==='/'){res.setHeader('Content-Type','text/html; charset=utf-8');res.end(harness);return}if(!['/learning/app.js','/learning/shell.js','/learning/style.css'].includes(filename)){res.statusCode=404;res.end();return}res.setHeader('Content-Type',filename.endsWith('.css')?'text/css':'application/javascript; charset=utf-8');res.end(fs.readFileSync(path.join(root,filename)))});
(async()=>{await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));const base=`http://127.0.0.1:${server.address().port}`;let browser;
try{browser=await chromium.launch({headless:true,...(process.env.CHROME_BINARY?{executablePath:process.env.CHROME_BINARY}:{})});const context=await browser.newContext({viewport:{width:1440,height:1000}}),errors=[];await context.route('**/*',route=>new URL(route.request().url()).origin===base?route.continue():route.abort());await context.addInitScript(({target,essay})=>localStorage.setItem('psychology-learning-v2-user-synthetic-test',JSON.stringify({answers:{},wrong:[target,essay],favorites:[target,essay],notes:{}})),{target,essay});const page=await context.newPage();page.on('pageerror',e=>errors.push(e.message));
const read=()=>page.locator('.card[data-id] .question-number').evaluateAll(elements=>elements.map(el=>({id:el.closest('[data-id]').dataset.id,text:el.textContent})));
const verify=async()=>{const rows=await read();assert(rows.length);for(const row of rows)assert.equal(row.text,`题号：${row.id}`);return rows};
await page.goto(base+'/#memory');await page.waitForSelector('.question-number');const before=await verify();assert.equal(before.length,12);assert.equal(await page.locator('.question-number *').count(),0,'question ID created HTML');await page.locator('#next').click();assert((await verify()).some(q=>q.id===target));await page.locator('#search').fill(target);assert.deepEqual(await verify(),[{id:target,text:`题号：${target}`}]);await page.locator('#search').fill('');await page.locator('#subject').selectOption('beta');assert((await verify()).some(q=>q.id===target));await page.locator('#review').selectOption('verified');assert((await verify()).some(q=>q.id===target));for(const range of ['wrong','favorites']){await page.locator('#practice').selectOption(range);assert.deepEqual(await verify(),[{id:target,text:`题号：${target}`}])}
await page.reload();await page.waitForSelector('.question-number');await page.locator('#search').fill(target);assert.deepEqual(await verify(),[{id:target,text:`题号：${target}`}]);await page.locator('[data-view="predictions"]').click();await page.locator('#search').fill(essay);assert.deepEqual(await verify(),[{id:essay,text:`题号：${essay}`}]);await page.locator('#examProbability').selectOption('30-60');assert.deepEqual(await verify(),[{id:essay,text:`题号：${essay}`}]);
await page.evaluate(()=>window.reloadPrivateStudy({preferLatest:true}));assert((await page.locator('#version').innerText()).includes('synthetic-v2'));assert.deepEqual(await verify(),[{id:essay,text:`题号：${essay}`}]);await page.locator('[data-view="memory"]').click();await page.locator('#search').fill(target);assert.deepEqual(await verify(),[{id:target,text:`题号：${target}`}]);
fs.mkdirSync(out,{recursive:true});await page.screenshot({path:path.join(out,'question-number-desktop.png'),fullPage:false});await page.setViewportSize({width:390,height:844});await page.locator('#search').fill(longId);await verify();await page.locator('.question-number').scrollIntoViewIfNeeded();const geometry=await page.locator('.question-number').evaluate(el=>{const r=el.getBoundingClientRect(),heading=el.closest('.card').querySelector('h2').getBoundingClientRect(),style=getComputedStyle(el);return {left:r.left,right:r.right,bottom:r.bottom,headingTop:heading.top,viewport:innerWidth,overflow:document.documentElement.scrollWidth>innerWidth+1,fontSize:style.fontSize,fontWeight:style.fontWeight,height:r.height,visible:r.top>=0&&r.bottom<=innerHeight}});assert(!geometry.overflow);assert(geometry.left>=0&&geometry.right<=geometry.viewport);assert(geometry.bottom<=geometry.headingTop);assert(geometry.visible);assert(geometry.height>30,'long ID did not wrap');assert.equal(geometry.fontSize,'14px');assert.equal(geometry.fontWeight,'700');await page.screenshot({path:path.join(out,'question-number-mobile-long.png'),fullPage:false});await page.locator('[data-view="predictions"]').click();await page.locator('#search').fill(essay);await verify();await page.locator('.question-number').scrollIntoViewIfNeeded();assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth+1),false);await page.screenshot({path:path.join(out,'question-number-mobile-essay.png'),fullPage:false});assert.deepEqual(errors,[]);fs.writeFileSync(path.join(out,'result.json'),JSON.stringify({passed:true,synthetic:true,checks:['q.id exact display for choice and essay','pagination, subject, review, wrong and favorite filters','search by original ID','browser reload','version refresh reversing bank order','390px choice/essay layout and long ID wrapping'],mobileGeometry:geometry},null,2));console.log('PASS: stable visible q.id labels across choice/essay, filters, pagination, reload, version reorder and 390px mobile layout.');
}finally{if(browser)await browser.close();await new Promise(resolve=>server.close(resolve))}})().catch(e=>{console.error(e);process.exitCode=1});
