// Synthetic fixture only. All remote requests are intercepted; no real account is used.
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm');
const {chromium}=require(process.env.PLAYWRIGHT_MODULE_PATH||'playwright');
const root=path.resolve(__dirname,'..'),base=process.env.STUDY_PREVIEW_URL||'http://127.0.0.1:8769';
const fixture={format:'teacher-interview-private-v1',subject:'teacher-interview',version:'synthetic-v1',metadata:{status:'fixture only'},limitations:['界面验证用合成数据'],examRules:{summary:'合成准备清单'},knowledgeTree:[{id:'TI-K-M',title:'测试模块',level:'module',parent_id:null,module:'测试模块',source_ids:['fixture-source']},{id:'TI-K-U',title:'测试单元',parent_id:'TI-K-M',level:'unit'},{id:'TI-K-P',title:'没有历史考次的测试知识点',parent_id:'TI-K-U',level:'point',locator:'合成章节',frequency:{direct_count:0,teaching_count:1,years:[2025],limitations:['仅合成样本']}}],frequency:{sample_summary:'去重样本界面验证',limitations:['非真实全国考频']},predictions:Array.from({length:100},(_,i)=>({id:'TI-P-'+String(i+1).padStart(3,'0'),type:i<10?'structured':'subject',title:(i<10?'结构化':'学科')+'合成题 '+(i+1),prompt:'仅测试：第 '+(i+1)+' 道合成题，不是备考内容。',requirements:['合成抽题要求'],textbook:{module:'测试模块',locator:'测试章节 '+i},competencies:['合成素养'],objectives:['合成目标'],key_points:['合成重点'],difficult_points:['合成难点'],answer_points:['第 '+i+' 项合成参考要点'],lesson_plan:{steps:['合成步骤 '+i]},transcript:'合成逐字稿 '+i+'。\n\n'+('长材料换行测试，不是真实答案。'.repeat(30))+'\n\n第三段合成话语。',board_plan:['合成板书 '+i],defense:[{question:'合成答辩问题 '+i,answer:'合成答辩回答 '+i}],source_ids:['fixture-source'],forecast:{reason:'合成预测理由 '+i,priority:i<30?'高':'中',confidence:'低',evidence:{historical_evidence:'去重合成样本',hotspot_evidence:'合成链接仅用于UI测试',counterevidence:'缺乏抽题母体'},probability:{status:'not_estimable',event:'相关主题是否出现',reason:'合成样本不允许估计概率'},limitations:['非真实备考资料']}})),templates:[{id:'TI-T-1',title:'合成议题模板',steps:['合成导入','合成讨论'],source_ids:['fixture-source']}],intros:[{id:'TI-I-1',title:'合成无设备导入',materials:'合成场景',duration:'1分钟',fallback:'口述即可',source_ids:['fixture-source']}],sources:[{id:'fixture-source',title:'合成官方来源链接',url:'https://example.invalid/fixture',accessed_at:'2026-10-07',limitations:'仅用于验证界面'}]};
fixture.knowledgeTree[0].module='B1';
Object.assign(fixture.knowledgeTree[2],{description:'合成教材语义要点',textbook_knowledge:true,scope_type:'user_textbook',locations:[{source_id:'fixture-source',pdf_pages:[5],printed_pages:[3],precision:'reviewed_semantic_pages',support_kind:'body',support_note:'合成具体页支持说明'}]});
fixture.knowledgeTree.push({id:'TI-K-X',title:'合成教学拓展',level:'knowledge',parent_id:'TI-K-U',textbook_knowledge:false,scope_type:'teaching_extension',description:'合成拓展，不当作教材目录',source_ids:['fixture-source']});
fixture.sources.push({id:'fixture-source-2',title:'第二合成来源',url:'https://example.invalid/fixture2'},{id:'fixture-source-3',title:'第三合成来源',url:'https://example.invalid/fixture3'});fixture.predictions[10].source_ids=['fixture-source','fixture-source-2','fixture-source-3'];
const psychology={version:'synthetic',subjects:[],sources:[],knowledgePoints:[],memoryQuestions:[],predictions:[]};
const clone=v=>JSON.parse(JSON.stringify(v));
const sandbox={window:{},URL};vm.runInNewContext(fs.readFileSync(path.join(root,'learning/teacher-interview.js'),'utf8'),sandbox);const validate=sandbox.window.TeacherInterview.validate;
validate(fixture);
const migration=fs.readFileSync(path.join(root,'backend/teacher-interview-review.sql'),'utf8');
const oldKeys="('psychology','politics','english','notes','documents')",newKeys="('psychology','politics','english','teacher-interview','notes','documents')";
// Catalog-pinned dynamic SQL contract only; no PostgreSQL connection or execution.
const md5=v=>require('node:crypto').createHash('md5').update(v).digest('hex');
const beginOriginal=fs.readFileSync(path.join(root,'backend/private-content-chunks.sql'),'utf8').match(/create or replace function public\.study_begin_content_upload\([\s\S]*?as \$\$([\s\S]*?)\$\$;/i)[1];
const tagged=name=>migration.split('$'+name+'$')[1];
assert.equal(tagged('old_keys'),oldKeys);assert.equal(tagged('new_keys'),newKeys);
const oldCleanup=" delete from public.study_content_uploads where user_id=uid and not complete and created_at<now()-interval '7 days';";
const newCleanup=" if p_key <> 'teacher-interview' then\n"+oldCleanup+"\n end if;";
assert.equal(tagged('old_cleanup'),oldCleanup);assert.equal(tagged('new_cleanup'),newCleanup);
assert.equal(beginOriginal.split(oldKeys).length,2);assert.equal(beginOriginal.split(oldCleanup).length,2);
const beginPatched=beginOriginal.replace(oldKeys,newKeys).replace(oldCleanup,newCleanup);
assert.equal(md5(beginOriginal),'d8b1fbfe7ddc3c113b8ab7171d5c5553');assert.equal(md5(beginPatched),'17290689c5385bf43e63de0926b0b1f4');
assert.equal(beginPatched.replace(newKeys,oldKeys).replace(newCleanup,oldCleanup),beginOriginal);
for(const required of ['REVIEW ONLY','obj_description','expected_acl','has_any_column_privilege','has_function_privilege','original_definition_md5','execute patched_definition','d8b1fbfe7ddc3c113b8ab7171d5c5553','17290689c5385bf43e63de0926b0b1f4','d1fba81054033ed76873ce79cff42f75','ebe0a28229fb747a86a850aeb1bcde15','check ((%s) or document_key=%L)'])assert(migration.includes(required),'SQL contract missing '+required);
assert(migration.includes('"service_role","EXECUTE",false')&&migration.includes('proc_row.proacl::text is distinct from original_acl'),'ACL must be preserved and verified');
assert(!/\b(grant|revoke)\s+(execute|all)\b/i.test(migration),'migration must not change roles');
assert(!migration.includes('alter table public.study_private_content'),'legacy content table must stay unchanged');
assert(!migration.includes('create or replace function public.study_set_private_content')&&!migration.includes('create or replace function public.study_commit_content_upload'),'deployed later functions must not be replaced');
if(process.argv.includes('--sql-only')){console.log('PASS: narrow SQL static contract, exact reversible body transform, CHECK/ACL/drift guards. No PostgreSQL parse or execution.');process.exit(0)}

for(const [name,mutate] of [['count',f=>f.predictions.pop()],['duplicate',f=>f.predictions[1].id=f.predictions[0].id],['missing-script',f=>delete f.predictions[5].transcript],['cycle',f=>f.knowledgeTree[0].parent_id='TI-K-P'],['invented-probability',f=>f.predictions[0].forecast.probability.range=[.6,.8]],['unknown-source',f=>f.predictions[0].source_ids=['missing']]]){const bad=clone(fixture);mutate(bad);assert.throws(()=>validate(bad),undefined,name)}
(async()=>{
 const browser=await chromium.launch({headless:true,...(process.env.CHROME_BINARY?{executablePath:process.env.CHROME_BINARY}:{})});
 try{
 const context=await browser.newContext({viewport:{width:1440,height:1000}}),calls=[],errors=[];const uploads=new Map();let allowed=true,current='10000000-0000-4000-8000-000000000001',bank=fixture,delay=0;
 await context.route('**/*',async route=>{const u=new URL(route.request().url());if(u.origin===new URL(base).origin)return route.continue();if(u.origin!=='https://fdpofmiuprjtvjbtnrku.supabase.co')return route.abort();const body=route.request().postDataJSON();calls.push({path:u.pathname,body});let response={},status=200;
  if(u.pathname.includes('/auth/v1/token'))response={access_token:'synthetic-token',refresh_token:'synthetic-refresh',expires_in:3600,user:{id:current,email:'fixture@example.invalid'}};
  else if(u.pathname.endsWith('get_study_state')){response=allowed?{user_id:current,revision:0,state:{answers:{},wrong:[],favorites:[]}}:{code:'42501',message:'synthetic access denied'};status=allowed?200:403}
  else if(u.pathname.endsWith('study_get_subject_package')){response={code:'P0002'};status=404}
  else if(u.pathname.endsWith('study_get_content_manifest')){response={code:'P0002'};status=404}
  else if(u.pathname.endsWith('study_get_private_content')){if(delay)await new Promise(r=>setTimeout(r,delay));response=allowed?(body.p_key==='teacher-interview'?bank:psychology):{code:'42501'};status=allowed?200:403}
  else if(u.pathname.endsWith('study_begin_content_upload')){assert.equal(body.p_key,'teacher-interview');const upload={key:body.p_key,hash:body.p_sha256,count:body.p_chunks,chunks:new Map()};uploads.set('synthetic-teacher-upload',upload);response={upload_id:'synthetic-teacher-upload',received:[],complete:false}}
  else if(u.pathname.endsWith('study_put_content_chunk')){const upload=uploads.get(body.p_upload);upload.chunks.set(body.p_index,body.p_text);response={received:true,chunk_index:body.p_index}}
  else if(u.pathname.endsWith('study_commit_content_upload')){const upload=uploads.get(body.p_upload);assert.equal(upload.chunks.size,upload.count);const text=[...upload.chunks.entries()].sort((a,b)=>a[0]-b[0]).map(x=>x[1]).join('');assert.equal(require('node:crypto').createHash('sha256').update(text).digest('hex'),upload.hash);bank=JSON.parse(text);response={saved:true,document_key:upload.key,sha256:upload.hash}}
  else if(u.pathname.includes('/logout'))response={};
  else if(u.pathname.endsWith('submit_study_batch'))throw Error('interview must not auto-score or write learning records');
  else throw Error('unexpected synthetic request '+u.pathname);
  await route.fulfill({status,contentType:'application/json',body:JSON.stringify(response)});
 });
 const page=await context.newPage();page.on('pageerror',e=>errors.push(e.message));await page.goto(base+'/#teacher-interview/predictions');
 assert.equal(await page.locator('#privateApp').isVisible(),false);assert.equal(calls.filter(c=>/study_get_(private_content|content_manifest)$/.test(c.path)).length,0,'anonymous requested private content');
 async function login(selectTeacher=false){await page.locator('#ownerEmail').fill('fixture@example.invalid');await page.locator('#ownerPassword').fill('synthetic-password');await page.locator('#passwordLogin').click();if(selectTeacher){await page.locator('#subjectHome:visible').waitFor();assert.equal(await page.locator('.ti-question').count(),0,'new owner inherited previous private view');await page.locator('#openTeacherInterview').click();await page.locator('.ti-nav [data-ti-view="predictions"]').click();}await page.waitForSelector('.ti-question');}
 await login();await page.waitForFunction(()=>document.getElementById('tiReadStatus').hidden);
 assert.equal(await page.locator('#teacherMain').isVisible(),true);assert.equal(await page.locator('#studyMain').isVisible(),false);assert.equal(await page.locator('#openTeacherInterview').getAttribute('class'),'active');assert.equal(await page.locator('nav[aria-label="学习导航"] [data-view].active').count(),0);
 assert.equal(await page.locator('.ti-nav [data-ti-view="predictions"].active').count(),1);assert((await page.locator('#tiContent').innerText()).includes('不可可靠估计'));assert((await page.locator('#tiContent').innerText()).includes('人工主观参考'));
 assert.equal(await page.locator('#tiTechnicalVersion:visible').count(),0);assert.equal(await page.locator('[data-submit]').count(),0);
 await page.locator('#tiType').selectOption('structured');assert((await page.locator('#tiContent').innerText()).includes('当前筛选 10 条'));await page.locator('#tiType').selectOption('subject');assert((await page.locator('#tiContent').innerText()).includes('当前筛选 90 条'));await page.locator('#tiPriority').selectOption('高');assert((await page.locator('#tiContent').innerText()).includes('当前筛选 20 条'));await page.locator('#tiPriority').selectOption('all');await page.locator('#tiOrder').selectOption('curriculum');await page.locator('#tiOrder').selectOption('priority');
 await page.locator('#tiSearch').fill('TI-P-011');assert.equal(await page.locator('.ti-question').count(),1);const draft=page.locator('[data-ti-draft="TI-P-011"]');await draft.locator('..').locator('..').locator('summary').click();await draft.fill('本人隔离练习草稿');
 await page.locator('#tiSearch').fill('TI-P-012');const secondDraft=page.locator('[data-ti-draft="TI-P-012"]');await secondDraft.locator('..').locator('..').locator('summary').click();await secondDraft.fill('另一题独立草稿');await page.locator('#tiSearch').fill('TI-P-011');assert.equal(await page.locator('[data-ti-draft="TI-P-011"]').inputValue(),'本人隔离练习草稿');assert(await page.evaluate(()=>Object.keys(localStorage).filter(k=>k.includes(':question:TI-P-')).length===2));
 const stored=await page.evaluate(()=>Object.fromEntries(Object.entries(localStorage)));assert(Object.keys(stored).some(k=>k.startsWith('teacher-interview-drafts-v1:')));assert(!JSON.stringify(stored).includes('合成逐字稿'));assert.equal(calls.filter(c=>c.path.endsWith('submit_study_batch')).length,0);
 const out=path.join(root,'private/teacher-interview/browser-check');fs.mkdirSync(out,{recursive:true});await page.screenshot({path:path.join(out,'desktop-prediction.png'),fullPage:true});
 bank=clone(fixture);bank.version='synthetic-v2';await page.locator('.ti-nav [data-ti-view="sources"]').click();await page.locator('#tiReload').click();await page.waitForFunction(()=>document.getElementById('tiVersion').textContent.includes('synthetic-v2'));await page.locator('.ti-nav [data-ti-view="predictions"]').click();assert.equal(await page.locator('[data-ti-draft="TI-P-011"]').inputValue(),'本人隔离练习草稿');
 await page.locator('#tiSearch').fill('');await page.locator('.ti-nav [data-ti-view="tree"]').click();await page.locator('#tiModule').selectOption('B1');assert.equal(await page.locator('#tiModule option[value="B1"]').innerText(),'测试模块');await page.locator('.ti-tree-node>summary').filter({hasText:'测试单元'}).click();const treeText=await page.locator('#tiContent').innerText();assert(treeText.includes('没有历史考次'));assert(treeText.includes('教材知识叶条目 1 个；目录外补充与教学拓展 1 个'));assert(treeText.includes('语义页据：印刷页 3（PDF 5）'));assert(treeText.includes('合成教材语义要点')&&treeText.includes('教学应用拓展（教材目录外）'));assert(!treeText.includes('reviewed_semantic_pages'));await page.locator('.ti-nav [data-ti-view="frequency"]').click();assert((await page.locator('#tiContent').innerText()).includes('直接考查：0'));await page.locator('#tiModule').selectOption('all');
 for(const name of ['templates','intros','sources']){await page.locator('.ti-nav [data-ti-view="'+name+'"]').click();assert.equal(await page.locator('.ti-nav [data-ti-view="'+name+'"].active').count(),1)}
 await page.locator('.ti-nav [data-ti-view="predictions"]').click();await page.locator('#tiSearch').fill('TI-P-011');await page.locator('.ti-reference').click();assert.equal(await page.locator('.ti-source').count(),3,'multiple reference IDs must match every source');await page.locator('#tiSearch').fill('');const beforeUpload=calls.length;await page.locator('#tiImportFile').setInputFiles({name:'bundle.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(fixture))});await page.waitForFunction(()=>document.getElementById('tiImportStatus').textContent.includes('本机预览：'));assert.equal(calls.length,beforeUpload,'file selection sent network request');assert.equal(await page.locator('#tiUpload').isEnabled(),true);await page.locator('#tiUpload').click();await page.waitForFunction(()=>document.getElementById('tiImportStatus').textContent.includes('服务端已确认保存'));assert(calls.some(c=>c.path.endsWith('study_begin_content_upload')&&c.body.p_key==='teacher-interview'));
 await page.locator('#tiSearch').fill('');await page.locator('.ti-nav [data-ti-view="predictions"]').click();await page.locator('#tiType').selectOption('all');await page.setViewportSize({width:360,height:800});await page.locator('.ti-question').first().locator('summary').filter({hasText:'完整口述逐字稿'}).click();assert(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth),'mobile horizontal overflow');await page.screenshot({path:path.join(out,'mobile-script.png'),fullPage:true});await page.screenshot({path:path.join(out,'mobile-script-viewport.png')});assert.equal(await page.locator('.ti-pagination').evaluate(el=>getComputedStyle(el).position),'static');
 await page.locator('[data-study-subject="psychology"]').first().click();await page.locator('[data-view="memory"]').click();await page.waitForFunction(()=>document.getElementById('teacherMain').hidden);assert.equal(await page.locator('nav [data-view="memory"].active').count(),1);assert.equal(await page.locator('#openTeacherInterview.active').count(),0);
 await page.locator('#openTeacherInterview').click();await page.locator('.ti-nav [data-ti-view="predictions"]').click();await page.waitForSelector('.ti-question');delay=350;await page.evaluate(()=>{window.TeacherInterview.reload({preferLatest:true})});await page.locator('#accountMenu summary').click();await page.locator('#logoutOwner').click();await page.waitForSelector('#privateLogin');assert.equal(await page.locator('#teacherMain').isVisible(),false);assert.equal(await page.locator('.ti-question').count(),0);delay=0;
 current='10000000-0000-4000-8000-000000000002';await login(true);await page.locator('#tiSearch').fill('TI-P-011');assert.equal(await page.locator('[data-ti-draft="TI-P-011"]').inputValue(),'','draft leaked to another account');allowed=false;await page.evaluate(()=>window.PsychSync.checkAccess());await page.waitForSelector('#privateLogin');assert.equal(await page.locator('.ti-question').count(),0,'denied user retained content');
 assert.deepEqual(errors,[]);await context.close();
 // Offline review: selecting a content package must never connect to any account.
 const review=await browser.newContext({viewport:{width:360,height:800}});let external=0;const offlineHTML='<html lang="zh-CN"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><link rel="stylesheet" href="/learning/style.css"><script src="/learning/teacher-interview.js" defer></script></head><body><main id="teacherMain"></main><script>window.addEventListener("DOMContentLoaded",()=>{TeacherInterview.mount({preview:true,host:document.getElementById("teacherMain"),authorized:()=>true,owner:()=>null});TeacherInterview.open("import",false)});</script></body></html>';await review.route('**/*',r=>{const u=new URL(r.request().url());if(u.origin===new URL(base).origin){if(u.pathname.endsWith('/private/teacher-interview/review-preview.html')&&!fs.existsSync(path.join(root,'private/teacher-interview/review-preview.html')))return r.fulfill({contentType:'text/html',body:offlineHTML});return r.continue()}external++;return r.abort()});const local=await review.newPage();await local.goto(base+'/private/teacher-interview/review-preview.html');await local.locator('#tiImportFile').setInputFiles({name:'bundle.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(fixture))});await local.waitForFunction(()=>document.getElementById('tiImportStatus').textContent.includes('本机预览：'));assert.equal(external,0);assert.equal(await local.locator('#tiUpload').isVisible(),false);await review.close();
 console.log('PASS: offline SQL ownership/role/namespace contract (no PostgreSQL executed); strict 100/10/90 schema; source/cycle/probability rejection; private namespace upload/checksum activation; anonymous and revoked access; six routes and active nav; type/module/search filtering; local import sends no request; per-account stable-ID drafts survive version update; no auto scoring/sync; logout clears content; mobile scripts wrap and next page stays in flow; offline review uses no account.');
 }finally{await browser.close()}
})().catch(error=>{console.error(error);process.exitCode=1});
