/* Exercise the actual route/filter/storage functions without a browser or network. */
const assert=require('node:assert/strict'),fs=require('fs'),vm=require('vm'),G=require('../learning/english-groups.js'),{make}=require('./subject_room_test_fixture.cjs');
(async()=>{
 const bank=await make('english'),audit=G.validate(bank),store=new Map(),context={window:{},location:{hash:'#english/objective'},history:{state:{},replaceState(s,_,url){this.state=s;context.location.hash=url}},localStorage:{getItem:k=>store.get(k)||null,setItem:(k,v)=>store.set(k,v)},structuredClone,console};
 const code=fs.readFileSync(require.resolve('../learning/english-study.js'),'utf8').replace('root.EnglishStudy={','root.Test={set(s){({bank,audit,nav,owner,record,visible}=s)},state:()=>nav,groups,applyRoute,persistNav,routeIsCurrent,writingType};root.EnglishStudy={');vm.runInNewContext(code,context);const api=context.window.Test;
 const base={module:'objective',writing_type:'all',paper:'all',year:'all',type:'all',mode:'all',search:'',group_id:audit.groups[0].id,current_question_id:audit.groups[0].question_ids[0],anchor:'question:'+audit.groups[0].question_ids[1],offset_within_anchor:12};const record={answers:{},notes:{},wrong:[]};api.set({bank,audit,nav:{...base},owner:'fictional-A',record,visible:true});api.persistNav();assert.equal(api.groups().length,6);assert.deepEqual(Array.from(api.groups(),g=>g.question_ids.length),[20,5,5,5,5,5]);
 context.location.hash='#english/translation';assert.equal(api.routeIsCurrent(),false);api.persistNav();assert.equal(context.location.hash,'#english/translation');api.applyRoute();assert.equal(api.state().module,'translation');assert.equal(api.groups().length,1);api.state().group_id=api.groups()[0].id;api.state().current_question_id=api.groups()[0].question_ids[0];api.persistNav();const translationID=api.state().group_id;
 context.location.hash='#english/writing';api.applyRoute();assert.equal(api.groups().length,2);api.state().writing_type='small';assert.equal(api.groups().length,1);api.state().group_id=api.groups()[0].id;api.persistNav();const smallID=api.state().group_id;assert.notEqual(smallID,translationID);
 api.state().writing_type='large';assert.equal(api.groups().length,1);assert.notEqual(api.groups()[0].id,smallID);api.state().writing_type='framework';assert.equal(api.groups().length,0);
 context.location.hash='#english/translation';api.applyRoute();assert.equal(api.state().group_id,translationID);context.location.hash='#english/objective';api.applyRoute();assert.equal(api.state().anchor,base.anchor);assert.equal(api.state().offset_within_anchor,12);context.location.hash='#english/'+encodeURIComponent(translationID);api.applyRoute();assert.equal(api.state().module,'translation');assert.equal(api.groups()[0].id,translationID);
 const writing=audit.groups.filter(g=>g.type==='writing');delete writing[0].raw.writing_type;bank.writingClassification=[{group_id:writing[0].id,writing_type:'framework',module:'writing'}];assert.equal(api.writingType(writing[0]),'framework');writing[0].raw.writing_type='small';assert.equal(api.writingType(writing[0]),'small');delete writing[0].raw.writing_type;bank.writingClassification=[];audit.byQuestion.get(writing[0].question_ids[0]).original_number=51;assert.equal(api.writingType(writing[0]),'small');audit.byQuestion.get(writing[0].question_ids[0]).original_number=52;assert.equal(api.writingType(writing[0]),'large');audit.byQuestion.get(writing[0].question_ids[0]).original_number=99;assert.equal(api.writingType(writing[0]),'unclassified');
 api.set({bank,audit,nav:{...base},owner:'fictional-B',record,visible:false});context.location.hash='#english/translation';api.applyRoute();assert.equal(api.state().group_id,null);assert(store.has('english-navigation-v1-user-fictional-A'));assert(!store.has('english-navigation-v1-user-fictional-B'));api.persistNav();assert(store.has('english-navigation-v1-user-fictional-B'));
 console.log('PASS: actual English module filters, 20/5/5 structure, stable IDs, scoped positions, pending-route preservation, legacy links, explicit mapping precedence and owner separation');
})().catch(e=>{console.error(e);process.exitCode=1});
