const vm=require('node:vm'),fs=require('node:fs'),assert=require('node:assert/strict'),{webcrypto}=require('node:crypto');
globalThis.crypto=webcrypto;const packageApi=require('../learning/subject-package.js');
const storage=new Map(),url='https://fixture-project.supabase.co',calls=[],uploads=new Map(),active=new Map();let lostPut=true,lostCommit=true,tamper=false,reads=0,maxReads=0,delayRead=false;
storage.set('psychology-sync-config-v1',JSON.stringify({url,publishableKey:'sb_publishable_fixture'}));storage.set('psychology-sync-session-v1:'+url,JSON.stringify({access_token:'fixture-only',refresh_token:'fixture-only',expires_at:Date.now()/1000+3600,user:{id:'fixture-user'}}));
const reply=x=>({ok:true,status:200,json:async()=>structuredClone(x)}),failure=(code,status=400)=>({ok:false,status,json:async()=>({code,message:'synthetic failure'})});
function manifestReply(subject){const u=active.get(subject);return u?{package_id:u.id,sha256:u.sha,manifest_text:u.text,baseline:'package:'+u.sha}:{available:false,subject,baseline:'legacy:'+subject}}
const fetch=async(path,options)=>{const b=JSON.parse(options.body);calls.push({path,b});
 if(path.endsWith('get_study_state'))return reply({user_id:'fixture-user',revision:0,state:{answers:{},wrong:[],favorites:[]}});
 if(path.endsWith('study_get_subject_package'))return reply(manifestReply(b.p_subject));
 if(path.endsWith('study_begin_subject_package')){const m=JSON.parse(b.p_manifest),sha=await packageApi.hash(new TextEncoder().encode(b.p_manifest));if(manifestReply(m.subject).baseline!==b.p_expected_baseline)return failure('40001');let u=uploads.get(sha);if(!u){u={id:sha,sha,text:b.p_manifest,m,baseline:b.p_expected_baseline,bodies:new Map()};uploads.set(sha,u)}return reply({package_id:u.id,sha256:sha,received:[...u.bodies.keys()]})}
 if(path.endsWith('study_put_subject_object')){const u=uploads.get(b.p_package),o=u.m.objects[b.p_index],bytes=Buffer.from(b.p_base64,'base64');assert(bytes.length<=262144);assert.equal(await packageApi.hash(bytes),o.sha256);u.bodies.set(o.index,bytes);if(lostPut&&o.index===3){lostPut=false;throw Error('lost object reply')}return reply({received:true,index:o.index,sha256:o.sha256})}
 if(path.endsWith('study_commit_subject_package')){const u=uploads.get(b.p_package);assert.equal(u.bodies.size,u.m.objects.length);if(manifestReply(u.m.subject).baseline!==u.baseline)return failure('40001');active.set(u.m.subject,u);if(lostCommit){lostCommit=false;throw Error('lost activation reply')}return reply({saved:true,subject:u.m.subject,sha256:u.sha})}
 if(path.endsWith('study_get_subject_object')){reads++;maxReads=Math.max(maxReads,reads);try{if(delayRead)await new Promise(r=>setTimeout(r,15));const u=uploads.get(b.p_package),o=u.m.objects[b.p_index];return reply({index:o.index,sha256:o.sha256,base64:Buffer.from(tamper?'altered':u.bodies.get(o.index)).toString('base64')})}finally{reads--}}
 if(path.includes('/logout'))return reply({});throw Error('unexpected endpoint '+path);
};
const window={SubjectPackage:packageApi},context={window,fetch,localStorage:{getItem:k=>storage.get(k)||null,setItem:(k,v)=>storage.set(k,v),removeItem:k=>storage.delete(k)},navigator:{locks:{request:async(n,o,cb)=>typeof o==='function'?o():cb({name:n})}},crypto:webcrypto,TextEncoder,Uint8Array,URL,AbortController,setTimeout,clearTimeout,Date,JSON,Set,Map,Promise,Number,Error,atob,btoa,location:{href:'https://example.invalid/',hash:''},history:{replaceState(){}}};
vm.runInNewContext(fs.readFileSync(require('node:path').join(__dirname,'../learning/sync.js'),'utf8'),context);
async function pack(subject,version){const values=[['root','bank','',{version}],['array','bank','memoryQuestions',[{id:'Q-stable',prompt:'Synthetic choice',options:['a','b'],answer:[0],review_status:'needs-review'}]],['array','bank','predictions',[{id:'E-stable',prompt:'Synthetic essay',answer_points:['point'],review_status:'needs-review'}]],['array','bank','subjects',[]],['array','bank','sources',[]],['array','bank','knowledgePoints',[]],['root','notes','',{}],['array','notes','records',[{id:'N-stable',text:version}]],['root','documents','',{}],['array','documents','documents',[]]];const objects=[],entries=new Map(),parsed=new Map();for(const [role,component,field,value] of values){const bytes=new TextEncoder().encode(JSON.stringify(value)),index=objects.length,path=`objects/${String(index).padStart(4,'0')}.json`;objects.push({index,path,role,component,field,start:0,count:role==='array'?value.length:0,bytes:bytes.length,sha256:await packageApi.hash(bytes)});entries.set(path,bytes);parsed.set(index,value)}const manifest={format:'private-subject-package',schema_version:1,subject,package_version:version,file_complete:true,semantic_review:{status:'incomplete',scope:'synthetic transport only',limitations:['No reviewed content']},objects},manifestText=JSON.stringify(manifest);return {manifest,manifestText,manifestSHA:await packageApi.hash(new TextEncoder().encode(manifestText)),entries,parsed}}
(async()=>{const api=window.PsychSync;assert.equal((await api.getStatus()).authenticated,true);const p1=await pack('psychology','fixture-v1');await assert.rejects(api.setSubjectPackage(p1),e=>e.code==='NETWORK_UNAVAILABLE'&&e.requestName==='study_put_subject_object'&&e.importPhase==='upload'&&e.importReceived===3&&e.importObjectIndex===3&&e.message.includes('已确认 3/10')&&!e.message.includes('fixture-only'));assert.equal(active.size,0);const prior=calls.length;const result=await api.setSubjectPackage(p1);assert(result.saved);assert(!calls.slice(prior).some(c=>c.path.endsWith('study_put_subject_object')&&c.b.p_index<4),'repeated acknowledged object');assert.equal(active.size,1);assert.equal((await api.getPrivateContent('psychology')).version,'fixture-v1');assert.equal((await api.getPrivateContent('notes')).records[0].text,'fixture-v1');
 const p2=await pack('psychology','fixture-v2');await api.setSubjectPackage(p2);assert.equal((await api.getPrivateContentManifest('psychology')).sha256,p2.manifestSHA);assert.equal((await api.getPrivateContent('psychology')).version,'fixture-v1','switched selected version without manual reload');assert.equal((await api.getPrivateContent('notes')).records[0].text,'fixture-v1','mixed notes and selected bank');assert.equal((await api.getPrivateContent('psychology',()=>{},{preferLatest:true})).version,'fixture-v2');assert.equal((await api.getPrivateContent('notes')).records[0].text,'fixture-v2');
 await assert.rejects(api.setPrivateContent('psychology',{}),/完整包/);assert(!calls.some(c=>c.path.endsWith('study_commit_content_upload')||c.path.endsWith('study_commit_subjective_upload')));
 await api.setSubjectPackage(await pack('politics','fixture-politics'));assert.equal(active.get('psychology').sha,p2.manifestSHA);assert.equal((await api.getPrivateContent('politics')).version,'fixture-politics');
 const stale=await pack('english','fixture-stale');lostPut=true;await assert.rejects(api.setSubjectPackage(stale),/请求未取得可读响应/);const winner=await pack('english','fixture-winner');await api.setSubjectPackage(winner);const countBeforeStale=calls.length;await assert.rejects(api.setSubjectPackage(await pack('english','fixture-stale')),/本科版本已改变/);assert.equal(active.get('english').sha,winner.manifestSHA);assert(!calls.slice(countBeforeStale).some(c=>c.path.endsWith('study_begin_subject_package')||c.path.endsWith('study_commit_subject_package')));
 tamper=true;await assert.rejects(api.getPrivateContent('psychology'),/SHA/);assert.equal(reads,0);tamper=false;delayRead=true;await api.getPrivateContent('psychology');assert.equal(maxReads,4);assert(!calls.some(c=>c.path.includes('submit_study_batch')));assert(![...storage.values()].join('').includes('Synthetic choice'));
 const reading=api.getPrivateContent('psychology');const rejected=assert.rejects(reading);await new Promise(r=>setTimeout(r,2));await api.signOut();await rejected;assert.equal(reads,0);console.log('PASS: real sync module + mocked transport, lost object/activation replies, receipt resume, subject isolation, manually pinned bank/notes versions, checksums, drained failures/logout, no old commit bypass, records untouched.');
})().catch(e=>{console.error(e);process.exitCode=1});
