/* All examples are synthetic. No uploaded content, real hashes or private IDs. */
const assert=require('node:assert/strict'),C=require('../learning/politics-catalog.js');
const source={id:'synthetic-source',file_name:'合成学习书.pdf'},bank={sources:[source],memoryQuestions:[{id:'synthetic-linked-question',source_question_number:9,source_refs:[{source_id:source.id}]}],predictions:[]};
const raw={id:'synthetic-note',title:'合成概念',knowledge_summary:'完整概述',explanation_plain:'完整通俗解析',discrimination_reminder:'完整辨析提醒',distinction:'完整概念区分',fact_version_limit:'保留原时点限制',source_time_scope:'不代表现行法律已核',scope_review_hold:{reason:'范围疑点不能解除',preserve_prior_source_scoped_hold:true,status:'retained_bounded_theory_scope_hold'},linked_reviewed_question_ids:['synthetic-linked-question'],linked_question_binding:{candidate_path:'/Users/fictional/private/candidate.json',candidate_sha256:'a'.repeat(64),identity:'仅作原题背景参考，不扩大授权'},source_refs:[{source_id:source.id,source_sha256:'b'.repeat(64),pdf_pages:[6,7],printed_pages:['003','004'],locator:'导论与概念辨析',ocr_ref:{path:'/Users/fictional/ocr.json',sha256:'c'.repeat(64)}}]};
const examples=[{id:'synthetic-example-one',book_part:1,original_example_number:3,prompt:'完整原题',options:{A:'甲完整选项',B:'乙完整选项'},original_reference_answer:'A',explanation_plain:'完整原解析',variants:[{id:'synthetic-internal-variant',prompt:'完整变式题',options:{A:'变式甲',B:'变式乙'},answer:'B',explanation_plain:'变式第一解析',explanation:'变式另一完整解析',prediction:false}],source_refs:raw.source_refs,answer_source_refs:[{source_id:source.id,pdf_page:12,printed_page:'009',locator:'原答案表'}]}, {id:'synthetic-example-two',source_example_number:8,prompt:'数组答案原题',source_reference_answer:['A','C'],options:{A:'甲',B:'乙',C:'丙'},explanation_plain:'数组原解析',source_answer_identity:'原教辅答案，非官方评分',independent_supplement_answer:'AB',source_answer_conflict:{original_reference_answer:'AC',earlier_independent_supplement_answer:'AB',detail:'保留原答案与补答差异',earlier_draft_path:'/Users/fictional/draft.json',earlier_draft_sha256:'d'.repeat(64)},theory_scope_hold:{target:'原题乙选项范围',does_not_clear_source_answer:'原答案身份不改变',status:'pending_independent_interpretation_review',auto_scoring_allowed:false},partial_obscuration_recovery:{original_page:'合成书.pdf/PDF7',recovery_basis:'只补原有缺字，不推断年份',snapshot_path:'/Users/fictional/snapshot.json',snapshot_sha256:'e'.repeat(64)},variants:[{prompt:'仅解析另一字段',answer:'保留参考答法',explanation:'完整另一字段解析'}]}, {id:'synthetic-example-three',prompt:'另一数组字段',original_reference_key:['B','D'],options:{B:'乙',D:'丁'},explanation_plain:'完整解析',variants:[]}];
const notes={rawRecords:[raw],referenceExamples:examples,records:[{id:raw.id,text:'source_sha256: '+ 'f'.repeat(64)+'\n/Users/fictional/private\nobsolete raw metadata'},...examples.map(r=>({id:r.id,text:'technical transfer '+ 'f'.repeat(64),adapter_projection:{source_field:'notes.referenceExamples'}}))]};
const before=JSON.stringify({notes,bank}),h=C.renderReferences(notes,bank).html;
for(const text of ['完整概述','完整通俗解析','完整辨析提醒','完整概念区分','保留原时点限制','范围疑点不能解除','仅作原题背景参考，不扩大授权','合成学习书.pdf','PDF 6、7 页','印刷 003、004 页','导论与概念辨析','甲完整选项','乙完整选项','完整原解析','变式甲','变式乙','变式第一解析','变式另一完整解析','完整另一字段解析','A、C','B、D','原教辅答案，非官方评分','保留原答案与补答差异','原答案身份不改变','只补原有缺字，不推断年份','原答案表'])assert(h.includes(text),text);
const visible=h.replace(/<[^>]+>/g,'');assert(!/[a-f0-9]{64}|\/Users\/|\[object Object\]|source_sha256|synthetic-note|synthetic-example|synthetic-internal-variant|"(?:prompt|answer|id)"\s*:/.test(visible));
assert(h.includes('href="#politics/memory/synthetic-linked-question"'));assert(h.includes('data-politics-reference="synthetic-note"'));assert(h.includes('参考例题 · 第 1 部分 · 例 3'));assert(!h.includes('data-pol-choice')&&!h.includes('data-pol-submit'));assert.equal(JSON.stringify({notes,bank}),before);
assert.deepEqual(C.answerValue(examples[1]),['A','C']);assert.deepEqual(C.answerValue(examples[2]),['B','D']);assert.equal(C.renderReferences(notes,bank,{search:'synthetic-example-two'}).count,1);
const escaped=C.renderReferences({rawRecords:[{id:'escape',title:'<script>title</script>',explanation_plain:'<img src=x onerror=bad>'}],records:[]},bank).html;assert(escaped.includes('&lt;script&gt;title'));assert(!escaped.includes('<img src=x'));
const legacyDump=C.renderReferences({records:[{id:'legacy-dump',text:'{"id":"synthetic-private-id","prompt":"raw JSON"}'}]},bank).html;assert(!legacyDump.includes('raw JSON'));assert(legacyDump.includes('缺少可读正文字段'));assert.equal(C.humanText('保留原范围hold与theory_hold'),'保留原范围限制与理论范围限制');
console.log('PASS: complete synthetic learning fields, native answer aliases, full variant options and both explanations, source pages, retained holds/conflicts/recovery, safe IDs and immutable records.');
