/* Real UI/IndexedDB; three synthetic subject packages, fictional identities and RPC. */
const {chromium}=require(process.env.PLAYWRIGHT_MODULE_PATH||'playwright');
const {createEnglishFixture}=require('./english_test_fixture.cjs');
const fs=require('fs'),path=require('path'),os=require('os'),http=require('http'),cp=require('child_process'),crypto=require('crypto'),assert=require('assert/strict');
const root=path.resolve(__dirname,'..'),out=process.env.EVIDENCE_DIR||path.join(root,'private/english-framework-check/browser'),temp=fs.mkdtempSync(path.join(os.tmpdir(),'three-subject-rooms-'));
const hash=b=>crypto.createHash('sha256').update(b).digest('hex'),project='https://room-fixture.supabase.co',uid={A:'30000000-0000-4000-8000-000000000001',B:'30000000-0000-4000-8000-000000000002'};
const BUILD_FIXTURE="# coding:utf-8\nimport json,sys,pathlib,hashlib,base64\nsys.path.insert(0,'scripts')\nfrom build_subject_package import build\nfrom question_release_gate import CHECKS\np=pathlib.Path(sys.argv[1]);bank=json.loads((p/'bank.json').read_text());sources={s['id']:s for s in bank['sources']};subject=bank['subject'];artifact={'format':'independent-question-review-v1','scope':'whole-question','completed':True,'author':'synthetic-protocol-author','reviewer':'synthetic-protocol-reviewer','completed_at':'2000-01-01T00:00:00Z','reviews':[]}\nfor q in bank['memoryQuestions']+bank['predictions']:\n artifact['reviews'].append({'question_id':q['id'],'decision':'passed','question_snapshot':q,'source_snapshots':{sid:sources[sid] for sid in q['source_ids']},'note_snapshots':{},'document_sha256':{},'note_basis':'external-source-only','checks':{k:{'status':'passed','evidence':'Synthetic room protocol assertion only; no actual exam content reviewed.'} for k in CHECKS}})\nraw=json.dumps(artifact,ensure_ascii=False).encode();(p/'evidence.json').write_bytes(raw);index={'format':'question-review-index-v1','records':[{'question_id':q['id'],'artifact':'evidence.json','sha256':hashlib.sha256(raw).hexdigest()} for q in bank['memoryQuestions']+bank['predictions']]};review={'status':'reviewed-with-limitations','scope':'Synthetic three-subject UI protocol fixture only.','limitations':['All data and credentials are fictional protocol fixtures; not real content approvals.']};notes={'records':[{'id':'common-note','text':'Synthetic '+subject+' note'}]};body=b'PK\\x03\\x04'+('Synthetic '+subject+' file').encode();docs={'documents':[{'file_name':subject+'-synthetic.docx','sha256':hashlib.sha256(body).hexdigest(),'base64':base64.b64encode(body).decode()}]};print(json.dumps(build(subject,bank['version'],bank,notes,docs,review,p/'package.zip',index,p)))\n";
async function packs(){
 let file;
 if(process.env.PACKAGE_FILE){file=path.resolve(process.env.PACKAGE_FILE);if(process.env.PACKAGE_SHA256)assert.equal(hash(fs.readFileSync(file)),process.env.PACKAGE_SHA256)}
 else{const dir=path.join(temp,'synthetic');fs.mkdirSync(dir);const bank=await createEnglishFixture({frameworkGroups:true});fs.writeFileSync(path.join(dir,'bank.json'),JSON.stringify(bank));cp.execFileSync('python3',['-c',BUILD_FIXTURE,dir],{cwd:root});file=path.join(dir,'package.zip')}
 const raw=JSON.parse(cp.execFileSync('python3',['-c',"import zipfile,json,base64,sys;z=zipfile.ZipFile(sys.argv[1]);m=z.read('manifest.json');print(json.dumps({'text':m.decode(),'entries':{n:base64.b64encode(z.read(n)).decode() for n in z.namelist() if n!='manifest.json'}}))",file],{maxBuffer:32*1024*1024}));const manifest=JSON.parse(raw.text),bank={};
 for(const o of manifest.objects){if(o.component!=='bank')continue;const v=JSON.parse(Buffer.from(raw.entries[o.path],'base64').toString());if(o.role==='root')Object.assign(bank,v);else{bank[o.field]=bank[o.field]||[];bank[o.field].push(...v)}}
 const p={file,bank,sha:hash(Buffer.from(raw.text)),text:raw.text,manifest,entries:raw.entries};
 const dir=path.join(temp,'held-synthetic');fs.mkdirSync(dir);const heldBank=await createEnglishFixture({frameworkGroups:true});const heldIDs=heldBank.writingClassification.map(c=>c.group_id);for(const g of heldBank.groups.filter(g=>heldIDs.includes(g.id))){g.practice_enabled=false;g.disabled_reason='Synthetic disabled framework protocol fixture; no source approval claimed.';g.original_text='DISABLED FRAMEWORK CONTENT MUST NOT LEAK';for(const q of heldBank.predictions.filter(q=>g.question_ids.includes(q.id))){q.practice_enabled=false;q.disabled_reason=g.disabled_reason;q.reference_answer='DISABLED REFERENCE MUST NOT LEAK'}}fs.writeFileSync(path.join(dir,'bank.json'),JSON.stringify(heldBank));cp.execFileSync('python3',['-c',BUILD_FIXTURE,dir],{cwd:root});const heldFile=path.join(dir,'package.zip'),heldRaw=JSON.parse(cp.execFileSync('python3',['-c',"import zipfile,json,base64,sys;z=zipfile.ZipFile(sys.argv[1]);m=z.read('manifest.json');print(json.dumps({'text':m.decode(),'entries':{n:base64.b64encode(z.read(n)).decode() for n in z.namelist() if n!='manifest.json'}}))",heldFile],{maxBuffer:32*1024*1024}));return {'english-v1':p,held:{file:heldFile,bank:heldBank,sha:hash(Buffer.from(heldRaw.text)),text:heldRaw.text,manifest:JSON.parse(heldRaw.text),entries:heldRaw.entries}};
}
(async()=>{const fixtures=await packs(),server=http.createServer((req,res)=>{const name=new URL(req.url,'http://local').pathname;if(name==='/'){res.setHeader('Content-Type','text/html;charset=utf-8');return res.end(fs.readFileSync(path.join(root,'index.html')))}if(/^\/learning\/[a-z-]+\.(js|css)$/.test(name)){res.setHeader('Content-Type',name.endsWith('.css')?'text/css':'application/javascript;charset=utf-8');return res.end(fs.readFileSync(path.join(root,name)))}res.statusCode=404;res.end()});await new Promise(r=>server.listen(0,'127.0.0.1',r));const base='http://127.0.0.1:'+server.address().port;let browser;const checks=[],errors=[];fs.mkdirSync(out,{recursive:true});
try{browser=await chromium.launch({headless:true,...(process.env.CHROME_BINARY?{executablePath:process.env.CHROME_BINARY}:{})});for(const [device,viewport] of Object.entries({desktop:{width:1440,height:1000},mobile:{width:390,height:844}})){const context=await browser.newContext({viewport,isMobile:device==='mobile',hasTouch:device!=='desktop'}),active={A:{},B:{}},uploads=new Map(),calls=[],states={A:{revision:0,state:{answers:{},wrong:[],favorites:[]},ids:new Set()},B:{revision:0,state:{answers:{},wrong:[],favorites:[]},ids:new Set()}};let revoked=false;
await context.addInitScript(({project,uid})=>{if(localStorage.getItem('room-fixture-seeded'))return;localStorage.setItem('room-fixture-seeded','yes');localStorage.setItem('psychology-sync-session-v1:'+project,JSON.stringify({access_token:'synthetic-A',refresh_token:'synthetic-A',expires_at:Date.now()/1000+3600,user:{id:uid,email:'a@example.invalid'}}))},{project,uid:uid.A});
await context.route('**/*',async route=>{const url=new URL(route.request().url());if(url.origin===base){if(url.pathname==='/learning/config.js')return route.fulfill({contentType:'application/javascript',body:`window.PSYCH_SYNC_CONFIG={url:'${project}',publishableKey:'sb_publishable_synthetic_fixture'};`});return route.continue()}if(url.origin!==project)return route.abort();const b=route.request().postDataJSON(),who=(route.request().headers().authorization||'').endsWith('synthetic-B')?'B':'A',st=states[who];calls.push({rpc:url.pathname,subject:b?.p_subject,which:who,index:b?.p_index});let result,status=200;
if(url.pathname.endsWith('/auth/v1/logout'))result={};else if(url.pathname.includes('/auth/v1/token')){const target=b.email.startsWith('b')?'B':'A';result={access_token:'synthetic-'+target,refresh_token:'synthetic-'+target,expires_in:3600,user:{id:uid[target],email:b.email}}}
else if(url.pathname.endsWith('get_study_state')){if(revoked){status=403;result={code:'42501',message:'synthetic permission revoked'}}else result={user_id:uid[who],revision:st.revision,state:structuredClone(st.state)}}
else if(url.pathname.endsWith('submit_study_batch')){const accepted=[];for(const op of b.operations){accepted.push(op.id);if(st.ids.has(op.id))continue;st.ids.add(op.id);st.revision++;if(op.kind==='answer'||op.kind==='import_answer')st.state.answers[op.target]={...op.payload,attempts:op.kind==='import_answer'?op.payload.attempts:(st.state.answers[op.target]?.attempts||0)+1,time:'2000-01-02'};else{const field=op.kind==='wrong'?'wrong':'favorites';st.state[field]=st.state[field].filter(id=>id!==op.target);if(op.payload.value)st.state[field].push(op.target)}}result={status:'ok',revision:st.revision,state:structuredClone(st.state),accepted}}
else if(url.pathname.endsWith('study_get_subject_package')){const p=active[who][b.p_subject];result=p?{package_id:p.sha,sha256:p.sha,manifest_text:p.text,baseline:'package:'+p.sha}:{available:false,subject:b.p_subject,baseline:'legacy:'+b.p_subject}}
else if(url.pathname.endsWith('study_get_subject_object')){const p=Object.values(fixtures).find(p=>p.sha===b.p_package)||uploads.get(b.p_package),o=p.manifest.objects[b.p_index];result={index:o.index,sha256:o.sha256,base64:p.entries[o.path]}}
else if(url.pathname.endsWith('study_begin_subject_package')){const sha=hash(Buffer.from(b.p_manifest));let p=uploads.get(sha);if(!p){p={sha,text:b.p_manifest,manifest:JSON.parse(b.p_manifest),entries:{},received:new Set()};uploads.set(sha,p)}result={package_id:sha,sha256:sha,received:[...p.received]}}
else if(url.pathname.endsWith('study_put_subject_object')){const p=uploads.get(b.p_package),o=p.manifest.objects[b.p_index],raw=Buffer.from(b.p_base64,'base64');assert.equal(hash(raw),o.sha256);p.entries[o.path]=b.p_base64;p.received.add(o.index);result={received:true,index:o.index,sha256:o.sha256}}
else if(url.pathname.endsWith('study_verify_subject_asset')){const p=uploads.get(b.p_package),os=p.manifest.objects.filter(o=>o.role==='asset'&&o.field===b.p_field),raw=Buffer.concat(os.map(o=>Buffer.from(p.entries[o.path],'base64')));result={verified:true,field:b.p_field,sha256:hash(raw)}}
else if(url.pathname.endsWith('study_commit_subject_package')){const p=uploads.get(b.p_package);assert.equal(p.received.size,p.manifest.objects.length);active[who][p.manifest.subject]=p;result={saved:true,subject:p.manifest.subject,sha256:p.sha}}
else if(url.pathname.endsWith('study_get_content_manifest')||url.pathname.endsWith('study_get_private_content')){status=404;result={code:'P0002',message:'Synthetic subject not imported'}}else throw Error('Unexpected synthetic RPC '+url.pathname);await route.fulfill({status,contentType:'application/json',body:JSON.stringify(result)})});
let page=await context.newPage();page.setDefaultTimeout(15000);page.on('pageerror',e=>errors.push({device,message:e.message}));const check=name=>{checks.push({device,name,passed:true});console.log(device+' PASS '+name)},choose=async subject=>page.locator('.room-subject-switch [data-study-subject="'+subject+'"]').click();
const bank=fixtures['english-v1'].bank,frameworkIDs=bank.writingClassification.filter(c=>c.writing_type==='framework'&&c.module==='writing').map(c=>c.group_id),frameworkGroups=bank.groups.filter(g=>frameworkIDs.includes(g.id));assert.equal(frameworkGroups.length,2);assert.equal(bank.frameworks,undefined);const firstFramework=frameworkGroups[0],frameworkTaskID=firstFramework.question_ids[0];
await page.goto(base);await page.locator('#subjectHome:visible').waitFor();await page.evaluate(()=>window.SubjectRoom.openManager('english'));await page.locator('#subjectPackageFile').setInputFiles(fixtures['english-v1'].file);await page.waitForFunction(()=>!document.getElementById('uploadSubjectPackage').disabled);await page.locator('#uploadSubjectPackage').click();await page.waitForFunction(()=>document.getElementById('subjectPackageStatus').textContent.includes('服务端已确认'));await page.locator('#openImportedPackage').click();await page.locator('[data-eg-group]').waitFor();
assert.equal(await page.evaluate(()=>window.SubjectRoom.getSubject()),'english');check('same-ZIP-import-no-framework-array-with-two-classified-material-groups');
// Save a real objective result in the fictional account and confirm it survives every new entrance.
const visibleObjectiveID=await page.locator('[data-eg-question]').first().getAttribute('data-eg-question'),firstObjective=bank.memoryQuestions.find(q=>q.id===visibleObjectiveID);assert(firstObjective);await page.locator('[data-eg-choice="'+firstObjective.id+'"][data-index="'+firstObjective.answer[0]+'"]').click();await page.locator('[data-eg-submit="'+firstObjective.id+'"]').click();const answerBefore=await page.evaluate(uid=>JSON.parse(localStorage.getItem('english-learning-v1-user-'+uid)).answers,uid.A);
await page.locator('[data-room-view="english/frameworks"]').click();await page.waitForFunction(()=>document.getElementById('subjectTools').textContent.includes('当前版本'));const toolsBefore=await page.locator('#subjectTools').textContent();
if(process.env.REPRODUCE_BASELINE==='1'){
 assert(toolsBefore.includes('框架资料尚未导入'));await page.screenshot({path:path.join(out,device+'-before-sidebar.png'),fullPage:false});await page.locator('[data-room-view="english/writing"]').click();await page.locator('[data-eg-group]').waitFor();await page.selectOption('#englishWritingType','framework');assert.equal(await page.locator('[data-eg-group]').count(),1);assert(frameworkIDs.includes(await page.locator('[data-eg-group]').getAttribute('data-eg-group')));assert((await page.locator('#englishContent').textContent()).includes('作文框架资料尚未导入'));check('baseline-bug-reproduced-sidebar-empty-and-classified-framework-task-plus-contradictory-empty-state');await context.close();continue;
}
const verifyCatalog=async()=>{await page.locator('[data-english-framework-group]').first().waitFor();assert.equal(await page.locator('[data-english-framework-group]').count(),frameworkGroups.length);const text=await page.locator('#subjectTools').textContent();assert(!text.includes('尚未导入'));for(const g of frameworkGroups){const card=page.locator('[data-english-framework-group="'+g.id+'"]');const content=await card.textContent();assert(content.includes(g.original_text));for(const qid of g.question_ids){const q=bank.predictions.find(q=>q.id===qid);assert(content.includes(qid));assert(content.includes(q.reference_answer||q.answer_points[0].point));assert(content.includes(q.answer_points[0].point))}for(const ref of g.source_refs){const id=typeof ref==='string'?ref:ref.id??ref.source_id;assert(content.includes(id))}assert(content.includes('完整材料组与子题审校均通过'))}assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth+1),false)};
await verifyCatalog();await page.screenshot({path:path.join(out,device+'-framework-catalog.png'),fullPage:false});check('sidebar-shows-both-actual-framework-materials-model-points-IDs-source-locators-and-review-scope');
const warm=calls.length;await page.reload();await verifyCatalog();assert.equal(calls.slice(warm).filter(c=>c.rpc.endsWith('study_get_subject_object')).length,0);check('catalog-refresh-authenticated-cache-zero-object-downloads');
await choose('politics');await page.waitForFunction(()=>document.getElementById('politicsContent').textContent.includes('资料尚未就绪'));await choose('english');await verifyCatalog();assert.deepEqual(await page.evaluate(uid=>JSON.parse(localStorage.getItem('english-learning-v1-user-'+uid)).answers,uid.A),answerBefore);check('subject-switch-restores-framework-catalog-and-retains-original-answer-record');
await page.locator('[data-framework-task-open="'+firstFramework.id+'"]').click();await page.locator('[data-eg-group="'+firstFramework.id+'"]').waitFor();assert.equal(await page.locator('#englishWritingType').inputValue(),'framework');assert(!(await page.locator('#englishContent').textContent()).includes('尚未导入'));assert.equal(await page.locator('[data-eg-question]').getAttribute('data-eg-question'),frameworkTaskID);await page.locator('[data-eg-draft="'+frameworkTaskID+'"]').fill('Fictional local framework draft only');await page.locator('[data-eg-reveal="'+frameworkTaskID+'"]').click();assert((await page.locator('#englishContent').textContent()).includes(bank.predictions.find(q=>q.id===frameworkTaskID).answer_points[0].point));await page.screenshot({path:path.join(out,device+'-framework-task.png'),fullPage:false});check('catalog-opens-original-gated-framework-task-correct-category-draft-and-answer-points-no-false-empty');
const savedHash=await page.evaluate(()=>location.hash);await page.reload();await page.locator('[data-eg-group="'+firstFramework.id+'"]').waitFor();assert.equal(await page.locator('[data-eg-draft="'+frameworkTaskID+'"]').inputValue(),'Fictional local framework draft only');assert.equal(await page.evaluate(()=>location.hash),savedHash);assert(!(await page.locator('#englishContent').textContent()).includes('尚未导入'));check('framework-task-refresh-restores-stable-group-ID-draft-and-route');
await page.evaluate(()=>window.PsychSync.signOut());await page.locator('#loginPanel:visible').waitFor();await page.locator('#ownerEmail').fill('a@example.invalid');await page.locator('#ownerPassword').fill('synthetic-not-real');await page.locator('#passwordLogin').click();await page.locator('[data-eg-group="'+firstFramework.id+'"]').waitFor();assert.equal(await page.locator('[data-eg-draft="'+frameworkTaskID+'"]').inputValue(),'Fictional local framework draft only');assert.deepEqual(await page.evaluate(uid=>JSON.parse(localStorage.getItem('english-learning-v1-user-'+uid)).answers,uid.A),answerBefore);await page.locator('[data-room-view="english/frameworks"]').click();await verifyCatalog();check('logout-login-framework-task-and-catalog-restore-original-draft-answer-record-no-reimport');
await page.evaluate(()=>window.PsychSync.signOut());await page.locator('#loginPanel:visible').waitFor();await page.locator('#ownerEmail').fill('b@example.invalid');await page.locator('#ownerPassword').fill('synthetic-not-real');await page.locator('#passwordLogin').click();await page.locator('#subjectHome:visible').waitFor();await choose('english');await page.locator('[data-room-view="english/frameworks"]').click();await page.waitForFunction(()=>document.getElementById('subjectTools').textContent.includes('本科资料尚未就绪'));assert.equal(await page.locator('[data-english-framework-group]').count(),0);assert.equal(await page.locator('[data-eg-draft]').count(),0);check('other-account-without-package-sees-honest-empty-no-private-framework-or-draft-leak');
await page.evaluate(()=>window.SubjectRoom.openManager('english'));await page.locator('#subjectPackageFile').setInputFiles(fixtures.held.file);await page.waitForFunction(()=>!document.getElementById('uploadSubjectPackage').disabled);await page.locator('#uploadSubjectPackage').click();await page.waitForFunction(()=>document.getElementById('subjectPackageStatus').textContent.includes('服务端已确认'));await page.locator('#openImportedPackage').click();await page.locator('[data-eg-group]').waitFor();await page.locator('[data-room-view="english/frameworks"]').click();await page.locator('[data-framework-unavailable]').first().waitFor();assert.equal(await page.locator('[data-framework-unavailable]').count(),2);const heldText=await page.locator('#subjectTools').textContent();assert(!heldText.includes('DISABLED FRAMEWORK CONTENT'));assert(!heldText.includes('DISABLED REFERENCE'));assert(!heldText.includes('尚未导入'));assert.equal(await page.locator('[data-framework-task-open]').count(),0);check('disabled-classified-frameworks-have-honest-unavailable-state-without-body-reference-or-task-links');await context.close();}
assert.deepEqual(errors,[]);fs.writeFileSync(path.join(out,'receipt.json'),JSON.stringify({passed:true,baseline_reproduced:process.env.REPRODUCE_BASELINE==='1',checks,errors,package_sha256:hash(fs.readFileSync(fixtures['english-v1'].file)),synthetic_only:!process.env.PACKAGE_FILE,actual_private_package:!!process.env.PACKAGE_FILE,mocked_remote:true,real_external_requests:false,public_deployment:false,source_sha256:Object.fromEntries(['english-study.js','english-groups.js','subject-room.js','sync.js','subject-package.js','access.js','shell.js','style.css'].map(n=>[n,hash(fs.readFileSync(path.join(root,'learning',n)))]))},null,2));console.log(JSON.stringify({passed:true,checks:checks.length,baseline_reproduced:process.env.REPRODUCE_BASELINE==='1'}));
}finally{if(browser)await browser.close();await new Promise(r=>server.close(r));fs.rmSync(temp,{recursive:true,force:true})}})().catch(e=>{console.error(e);process.exitCode=1});
