'use strict';
const KEY='psychology-learning-v2',OLD_KEY='psychology-combined-bank-v1',PAGE_SIZE=12;
const $=id=>document.getElementById(id),esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const titles={trend:'趋势解析',memory:'记忆练习',predictions:'主观题预测',coverage:'覆盖与缺口',corrections:'笔记修正',sources:'权威来源',progress:'我的学习',sync:'账号与同步'};
let data={subjects:[],sources:[],knowledgePoints:[],memoryQuestions:[],predictions:[],corrections:[],predictionCoverage:[],trend:{}},view='trend',page=0,selected=new Map(),revealed=new Set();
let storageKey=KEY,syncTimer=null,syncGeneration=0;
let state={version:2,answers:{},wrong:[],favorites:[],notes:{},legacyRecords:{},updatedAt:null};
const verified=x=>['verified','reviewed','已核验','已审校','核验通过'].includes(x.review_status||x.verification_status);
const statusLabels={'verified':'已核验','needs-review':'待独立核验','authored-needs-review':'已编待审','partial-needs-review':'部分覆盖待审','uncovered':'尚未覆盖','excluded':'导航条目排除','limited-search-summary':'仅检索摘要'};
const status=x=>statusLabels[x.review_status||x.verification_status]||x.review_status||x.verification_status||'待核验';
const array=x=>Array.isArray(x)?x:[];
const subjectName=id=>data.subjects.find(s=>s.id===id)?.title||id||'综合';
const urlSafe=url=>{try{const u=new URL(url);return ['https:','http:'].includes(u.protocol)?esc(u.href):''}catch{return ''}};
function toast(text){$('toast').textContent=text;$('toast').hidden=false;clearTimeout(toast.timer);toast.timer=setTimeout(()=>$('toast').hidden=true,4000)}
function object(v){return v&&typeof v==='object'&&!Array.isArray(v)}
function validState(v){if(!object(v)||!object(v.answers)||!Array.isArray(v.wrong))throw Error('记录格式不正确');const result={version:2,answers:{},wrong:[],favorites:[],notes:{},legacyRecords:object(v.legacyRecords)?v.legacyRecords:{},updatedAt:typeof v.updatedAt==='string'?v.updatedAt:null};for(const [id,a] of Object.entries(v.answers)){if(!object(a)||typeof a.correct!=='boolean'||!Number.isInteger(a.attempts)||a.attempts<1)continue;result.answers[id]={correct:a.correct,firstCorrect:typeof a.firstCorrect==='boolean'?a.firstCorrect:a.correct,attempts:a.attempts,selected:array(a.selected).filter(n=>Number.isInteger(n)&&n>=0),time:typeof a.time==='string'?a.time:''}}result.wrong=[...new Set(v.wrong.filter(id=>typeof id==='string'))];result.favorites=[...new Set(array(v.favorites).filter(id=>typeof id==='string'))];for(const [id,n]of Object.entries(v.notes||{})){if(object(n)&&typeof n.text==='string')result.notes[id]={text:n.text.slice(0,20000),time:typeof n.time==='string'?n.time:''}}return result}
function restore(){try{const saved=localStorage.getItem(storageKey);if(saved)state=validState(JSON.parse(saved))}catch{toast('本机记录读取失败，可通过导入恢复。')}}
function save(){if(syncStatus.readOnly)return toast('此窗口仅查看，不能修改账号记录。');state.updatedAt=new Date().toISOString();try{localStorage.setItem(storageKey,JSON.stringify(state));$('saveStatus').textContent='已保存至本机'}catch{$('saveStatus').textContent='保存失败 · 请导出';toast('浏览器存储不可用，请导出记录。')}metrics();if(syncStatus.authenticated){clearTimeout(syncTimer);syncTimer=setTimeout(()=>syncCurrent(),1000)}}
function meta(x){return `<div class="meta"><span class="tag">${esc(subjectName(x.subject))}</span><span class="tag ${verified(x)?'verified':'pending'}">${esc(status(x))}</span><span>${esc(x.id)}</span></div>`}
function textBlock(v){return Array.isArray(v)?v.map(x=>`<p>${esc(x)}</p>`).join(''):`<p>${esc(v)}</p>`}
function references(x){const refs=array(x.note_refs),sources=array(x.source_ids).map(id=>data.sources.find(s=>s.id===id)).filter(Boolean);return `<details class="details"><summary>笔记定位与权威来源（${refs.length+sources.length}）</summary>${!refs.length&&!sources.length?'<p class="fine">尚未绑定来源，不能视为已完成追溯。</p>':''}${refs.map(r=>`<div class="reference"><b>${esc(r.file_name)}</b> · ${esc(r.locator)}${r.basis_type?`<p>${esc(r.basis_type)}</p>`:''}${r.excerpt?`<blockquote>“${esc(r.excerpt)}”</blockquote>`:''}<button class="btn" data-open-note="${esc(r.locator.replace(/^audit:/,''))}">查看相关笔记原文</button></div>`).join('')}${sources.map(s=>`<div class="reference">${sourceLink(s)}<p>${esc(s.summary)}</p><span class="fine">${esc(s.organization)} · ${esc(s.verification_status||'待核验')}</span></div>`).join('')}</details>`}
function sourceLink(s){const url=urlSafe(s.url);return url?`<a href="${url}" target="_blank" rel="noopener noreferrer">${esc(s.title)} ↗</a>`:`<b>${esc(s.title)}</b> <span class="fine">链接尚未提供</span>`}
function variations(x){return array(x.variations).length?`<h3>换一种考法</h3><ul>${x.variations.map(v=>`<li>${esc(v)}</li>`).join('')}</ul>`:''}
function favoriteButton(x){return `<button class="btn" data-favorite="${esc(x.id)}" aria-pressed="${state.favorites.includes(x.id)}">${state.favorites.includes(x.id)?'★ 已收藏':'☆ 收藏'}</button>`}
function matches(x){const s=$('subject').value,r=$('review').value,p=$('practice').value,q=$('search').value.trim().toLowerCase();if(!['sources','trend'].includes(view)&&s!=='all'&&x.subject!==s)return false;if(r==='verified'&&!verified(x)||r==='pending'&&verified(x))return false;if(['memory','predictions'].includes(view)&&(p==='wrong'&&!state.wrong.includes(x.id)||p==='favorites'&&!state.favorites.includes(x.id)||p==='unseen'&&(state.answers[x.id]||state.notes[x.id])))return false;return !q||JSON.stringify(x).toLowerCase().includes(q)}
function metrics(){const all=[...data.memoryQuestions,...data.predictions],checked=all.filter(verified).length,answered=data.memoryQuestions.filter(q=>state.answers[q.id]).length;$('metrics').innerHTML=[['可练内容',all.length],['已核验题目',checked],['本机已作答',answered],['待补知识点',data.knowledgePoints.filter(k=>k.gap_reason||!verified(k)).length]].map(([s,n])=>`<div class="metric"><b>${n}</b><span>${s}</span></div>`).join('')}
function empty(title='暂无符合筛选的内容',body='可调整学科、核验状态或搜索条件。'){return `<div class="empty"><h2>${title}</h2><p>${body}</p></div>`}
function memory(q){const picked=selected.get(q.id)||[],show=revealed.has(q.id),ans=array(q.answer),record=state.answers[q.id];return `<article class="card" data-id="${esc(q.id)}">${meta(q)}<h2>${esc(q.prompt)}</h2><div class="options" role="group" aria-label="选择答案">${array(q.options).map((o,i)=>`<button class="option ${picked.includes(i)?'selected':''} ${show&&verified(q)?ans.includes(i)?'correct':picked.includes(i)?'incorrect':'':''}" data-choice="${esc(q.id)}" data-index="${i}" aria-pressed="${picked.includes(i)}" ${show?'disabled':''}><b>${String.fromCharCode(65+i)}</b><span>${esc(typeof o==='string'?o:o.text)}</span></button>`).join('')}</div><p class="fine">${ans.length>1?'多选':'单选'} · ${verified(q)?'已核验，可计入本机练习进度':'待核验内容只供查看，不计正确率'}${record?` · 已练 ${record.attempts} 次`:''}</p><div class="actions"><button class="btn primary" data-submit="${esc(q.id)}" ${!picked.length||show?'disabled':''}>${verified(q)?'提交并查看解析':'查看暂定答案'}</button>${favoriteButton(q)}<button class="btn" data-wrong="${esc(q.id)}">${state.wrong.includes(q.id)?'移出错题':'加入错题'}</button>${show?`<button class="btn" data-retry="${esc(q.id)}">再练一次</button>`:''}</div>${show?`<div class="answer"><h3>${verified(q)?'答案':'暂定答案 · 仍待核验'}：${ans.map(i=>String.fromCharCode(65+i)).join('、')}</h3>${textBlock(q.plain_explanation)}<h3>逐项解释</h3><ul>${array(q.option_explanations).map((e,i)=>`<li><b>${String.fromCharCode(65+i)}</b> ${esc(e)}</li>`).join('')}</ul>${variations(q)}${q.review_evidence?`<p class="fine">审校依据：${esc(typeof q.review_evidence==='object'?JSON.stringify(q.review_evidence):q.review_evidence)}</p>`:''}</div>`:''}${references(q)}</article>`}
function prediction(q){const f=q.forecast||{},range=array(f.knowledge_point_range),shown=revealed.has(q.id);return `<article class="card">${meta(q)}<h2>${esc(q.title||q.prompt)}</h2><p class="prompt">${esc(q.prompt)}</p><div class="probability"><div>知识点在${esc(f.target||'下一次考试')}出现<strong>${range.length===2?`${esc(range[0])}–${esc(range[1])}%`:'未估计'}</strong>${esc(f.label||'主观判断，非统计校准')}</div><div>具体题目原样命中<strong>未估计</strong>不将知识点出现概率当作这道题的命中率</div></div><p class="fine">事件口径：${esc(f.event||'狭主题作为实质考点')}<br>依据：${esc(f.basis||'待补充')}<br>不确定性：${esc(f.uncertainty||'待补充')}</p><div class="actions"><button class="btn primary" data-reveal="${esc(q.id)}">${shown?'收起答案要点':'查看答案要点'}</button>${favoriteButton(q)}</div>${shown?`<div class="answer"><h3>作答要点</h3><ul>${array(q.answer_points).map(p=>`<li>${esc(p)}</li>`).join('')}</ul><h3>通俗解析</h3>${textBlock(q.plain_explanation)}${variations(q)}</div>`:''}<details class="details"><summary>写下我的作答（仅本机）</summary><label>先回忆，再对照要点<textarea data-note="${esc(q.id)}" rows="6" style="display:block;width:100%;margin-top:10px;border:1px solid var(--line);border-radius:8px;padding:12px;font:inherit" placeholder="写下论证结构、关键概念与例子…">${esc(state.notes[q.id]?.text||'')}</textarea></label></details>${references(q)}</article>`}
function coverage(k){const counts=k.coverage_counts||{};return `<article class="card"><div class="coverage-row"><div>${meta(k)}<h2>${esc(k.title)}</h2></div><span class="tag">${array(k.memory_question_ids).length} 记忆题 · ${array(k.prediction_ids).length} 预测题</span></div><p class="fine">${Object.entries(counts).map(([s,n])=>`${esc(statusLabels[s]||s)} ${n}`).join(' · ')}</p>${k.gap_reason?`<p class="pending" style="padding:12px;border-radius:6px">覆盖缺口：${esc(k.gap_reason)}</p>`:''}<details class="details"><summary>逐项查看 ${array(k.targets).length} 个细分目标</summary>${array(k.targets).map(t=>`<div class="reference"><b>${esc(t.id)}</b> · ${esc(statusLabels[t.status]||t.status)}<p>${esc(t.label)}</p>${t.gap_reason?`<p class="fine">${esc(t.gap_reason)}</p>`:''}<p>${array(t.question_ids).map(id=>`<button class="btn" data-open-question="${esc(id)}">${esc(id)}</button>`).join(' ')}</p></div>`).join('')}</details>${references(k)}</article>`}

function essayCoverage(t){const labels={'direct_main':'题干直接考查','direct_subquestion':'子问直接考查','answer_component':'答案组成点','untested':'未覆盖','pending_verification':'待核验','excluded_context':'上下文/导航排除'};return `<article class="card">${meta(t)}<h2>${esc(t.title)}</h2><p>${esc(labels[t.coverage_role]||t.coverage_role)} · ${esc(t.source_locator)}</p>${t.gap_reason?`<p class="fine">${esc(t.gap_reason)}</p>`:''}${array(t.mappings).map(m=>`<div class="reference"><button class="btn" data-open-question="${esc(m.question_id)}">${esc(m.question_id)}</button><p>${esc(m.prompt_clause)}</p><p class="fine">训练评分点：${array(m.answer_point_indexes).map(esc).join('、')}</p></div>`).join('')}${t.outside_notes?'<p class="fine">笔记外权威补充，未冒充笔记覆盖</p>':''}</article>`}

function correction(x){return `<article class="card">${meta(x)}<h2>${esc(x.title)}</h2><p class="fine">原笔记表述</p><blockquote>${esc(x.before)}</blockquote><div class="answer"><h3>建议修正</h3>${textBlock(x.after)}<h3>修正依据</h3>${textBlock(x.reason)}</div>${references(x)}</article>`}
function source(s){return `<article class="card">${meta(s)}<h2>${sourceLink(s)}</h2><p>${esc(s.summary)}</p>${s.quote?`<blockquote>“${esc(s.quote)}”</blockquote>`:''}<p class="fine">${esc(s.organization)} · 查阅：${esc(s.accessed_at||'未记录')} · 来源 ID：${esc(s.id)}</p></article>`}
function trend(){const t=data.trend||{};if(!array(t.findings).length&&!t.scope)return empty('趋势研究正在接入','完成独立核验后将在此展示年度证据、口径差异与预测依据。');return `<article class="card"><p class="eyebrow">EXAM PATTERNS & EVIDENCE</p><h2>${esc(t.title||'北大心理学趋势研究')}</h2>${textBlock(t.scope)}</article><div class="findings">${array(t.findings).filter(f=>!$('search').value.trim()||JSON.stringify(f).toLowerCase().includes($('search').value.trim().toLowerCase())).map(f=>`<article class="card"><h2>${esc(f.title)}</h2>${textBlock(f.text)}<p class="fine">证据：${esc(typeof f.evidence==='object'?JSON.stringify(f.evidence):f.evidence)}</p><p class="fine">不确定性：${esc(f.uncertainty)}</p></article>`).join('')}</div>${array(t.annual).length?`<article class="card"><h2>逐年观察</h2>${t.annual.map(a=>`<div class="annual"><b>${esc(a.year)}</b><div><p>${esc(Array.isArray(a.topics)?a.topics.join(' · '):a.topics)}</p><p class="fine">${esc(a.notes)}</p></div></div>`).join('')}</article>`:''}${array(t.topic_forecasts).length?`<article class="card"><h2>下一次考试：主题出现的主观宽区间</h2><p class="fine">事件为至少一道主观题把该主题作为实质考点；非统计校准、非置信区间。主题可重叠，不能相加为100%；具体题原样命中未估计。</p>${t.topic_forecasts.map(f=>`<div class="annual"><b>${esc(array(f.range).join('–'))}%</b><div><p>${esc(f.topic)}</p><p class="fine">依据：${esc(f.basis)} · 条件与不确定性：${esc(f.condition)}</p></div></div>`).join('')}</article>`:''}<article class="card"><h2>研究口径与限制</h2>${textBlock(t.methodology)}<ul>${array(t.limitations).map(l=>`<li>${esc(l)}</li>`).join('')}</ul></article>`}
function progress(){const ids=new Set([...data.memoryQuestions,...data.predictions].map(q=>q.id)),legacyCount=Object.keys(state.answers).filter(id=>!ids.has(id)).length;return `<article class="card"><h2>我的学习记录</h2><p>${syncStatus.authenticated?'答题、错题与收藏已接入账号同步；主观题草稿仅保存在当前浏览器。':'当前浏览器保存答题记录、错题、收藏与主观题草稿。登录和服务端权限验证通过后可同步答题、错题及收藏。'}</p><p>当前内容已答 ${data.memoryQuestions.filter(q=>state.answers[q.id]).length} 题 · 错题 ${state.wrong.filter(id=>ids.has(id)).length} · 收藏 ${state.favorites.filter(id=>ids.has(id)).length} · 草稿 ${Object.keys(state.notes).length} 份</p><p class="fine">保留的旧题记录 ${legacyCount} 条，不匹配新题的 ID 仍保留在导出文件内。原题库存储保持原样。</p><div class="actions"><button class="btn primary" id="export">导出学习记录</button><button class="btn" id="import">导入并合并记录</button><button class="btn" id="legacy">读取本机旧版记录</button></div></article><article class="card"><h2>跨设备使用</h2><p>暂时可以在电脑导出 JSON，在手机导入；导入会合并，采用较新的答题和草稿，并保留双方的错题与收藏。此方式需要手动操作。</p><p class="fine">账号与同步页面提供邮箱链接登录。草稿不上传；导入前请确认当前账户。</p></article>`}
function render(){document.querySelectorAll('[data-view]').forEach(b=>b.classList.toggle('active',b.dataset.view===view));$('viewTitle').textContent=titles[view];$('toolbar')?.classList.toggle('hidden',view==='progress');document.querySelector('.toolbar').hidden=['progress','sync'].includes(view);$('subject').closest('label').hidden=['sources','trend'].includes(view);$('review').closest('label').hidden=view==='trend';$('practice').closest('label').hidden=!['memory','predictions'].includes(view);$('coverageModeLabel').hidden=view!=='coverage';if(view==='trend')$('content').innerHTML=trend();else if(view==='progress')$('content').innerHTML=progress();else if(view==='sync')$('content').innerHTML=syncPanel();else{const map={memory:['memoryQuestions',memory],predictions:['predictions',prediction],coverage:$('coverageMode').value==='predictions'?['predictionCoverage',essayCoverage]:['knowledgePoints',coverage],corrections:['corrections',correction],sources:['sources',source]},[key,renderer]=map[view],list=data[key].filter(matches);page=Math.min(page,Math.max(0,Math.ceil(list.length/PAGE_SIZE)-1));$('content').innerHTML=`<p class="fine">当前筛选 ${list.length} 条${view==='coverage'?' · 覆盖台账逐项列出，缺口不计作完成':''}</p>`+(list.length?list.slice(page*PAGE_SIZE,(page+1)*PAGE_SIZE).map(renderer).join(''):empty(data[key].length?'暂无符合筛选的内容':'内容正在接入',data[key].length?'可调整筛选条件。':'审校完成的内容将在此展示，当前不以占位数据冒充题库。'))+(list.length>PAGE_SIZE?`<div class="pagination"><button class="btn" id="prev" ${page===0?'disabled':''}>上一页</button><span>${page+1} / ${Math.ceil(list.length/PAGE_SIZE)}</span><button class="btn" id="next" ${(page+1)*PAGE_SIZE>=list.length?'disabled':''}>下一页</button></div>`:'')}bind();if(syncStatus.readOnly)document.querySelectorAll('[data-submit],[data-favorite],[data-wrong],[data-note],#legacy,#import').forEach(el=>el.disabled=true)}
function bind(){document.querySelectorAll('[data-open-question]').forEach(b=>b.onclick=()=>{view=data.predictions.some(q=>q.id===b.dataset.openQuestion)?'predictions':'memory';page=0;location.hash=view;$('subject').value='all';$('review').value='all';$('practice').value='all';$('search').value=b.dataset.openQuestion;render()});document.querySelectorAll('[data-choice]').forEach(b=>b.onclick=()=>{const q=data.memoryQuestions.find(q=>q.id===b.dataset.choice),i=Number(b.dataset.index),picked=selected.get(q.id)||[];selected.set(q.id,array(q.answer).length>1?picked.includes(i)?picked.filter(n=>n!==i):[...picked,i]:[i]);render()});document.querySelectorAll('[data-submit]').forEach(b=>b.onclick=()=>{const q=data.memoryQuestions.find(q=>q.id===b.dataset.submit),picked=selected.get(q.id)||[];if(!picked.length)return;revealed.add(q.id);if(verified(q)){const correct=[...picked].sort().join(',')===[...q.answer].sort().join(','),old=state.answers[q.id];state.answers[q.id]={correct,attempts:(old?.attempts||0)+1,selected:picked,time:new Date().toISOString()};if(!correct&&!state.wrong.includes(q.id))state.wrong.push(q.id);save()}render()});document.querySelectorAll('[data-retry]').forEach(b=>b.onclick=()=>{revealed.delete(b.dataset.retry);selected.delete(b.dataset.retry);render()});document.querySelectorAll('[data-reveal]').forEach(b=>b.onclick=()=>{revealed.has(b.dataset.reveal)?revealed.delete(b.dataset.reveal):revealed.add(b.dataset.reveal);render()});document.querySelectorAll('[data-favorite]').forEach(b=>b.onclick=()=>{const id=b.dataset.favorite;state.favorites=state.favorites.includes(id)?state.favorites.filter(x=>x!==id):[...state.favorites,id];save();render()});document.querySelectorAll('[data-wrong]').forEach(b=>b.onclick=()=>{const id=b.dataset.wrong;state.wrong=state.wrong.includes(id)?state.wrong.filter(x=>x!==id):[...state.wrong,id];save();render()});document.querySelectorAll('[data-note]').forEach(t=>t.oninput=()=>{state.notes[t.dataset.note]={text:t.value,time:new Date().toISOString()};save()});if($('prev'))$('prev').onclick=()=>{page--;render();window.scrollTo(0,0)};if($('next'))$('next').onclick=()=>{page++;render();window.scrollTo(0,0)};bindSync();if($('export'))$('export').onclick=exportState;if($('import'))$('import').onclick=()=>$('importFile').click();if($('legacy'))$('legacy').onclick=()=>{try{const count=readLegacyRecords();toast(count?'已读取 '+count+' 份旧版记录；原存储保持原样。':'当前浏览器没有找到旧版记录。')}catch(e){toast(e.message)}}}
function readLegacyRecords(){let count=0;for(const key of [OLD_KEY,'puxin-memory-bank-v1']){const raw=localStorage.getItem(key);if(!raw)continue;merge(JSON.parse(raw),'legacy:'+key);count++}return count}
function merge(raw,origin='import'){if(syncStatus.readOnly)return toast('此窗口仅查看。');const incoming=validState(raw);for(const [id,a]of Object.entries(incoming.answers)){if(!state.answers[id]||a.time>state.answers[id].time)state.answers[id]=a}for(const [id,n]of Object.entries(incoming.notes)){if(!state.notes[id]||n.time>state.notes[id].time)state.notes[id]=n}state.wrong=[...new Set([...state.wrong,...incoming.wrong])];state.favorites=[...new Set([...state.favorites,...incoming.favorites])];Object.assign(state.legacyRecords,incoming.legacyRecords);if(origin==='legacy'||raw.version===1)state.legacyRecords[`${origin}-${new Date().toISOString()}`]=raw;save();render()}
function exportState(){const payload={format:'psychology-learning-record',exportedAt:new Date().toISOString(),...state},url=URL.createObjectURL(new Blob([JSON.stringify(payload,null,2)],{type:'application/json'})),a=document.createElement('a');a.href=url;a.download=`心理学学习记录-${new Date().toISOString().slice(0,10)}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(url),10000);toast('已导出，请妥善保存包含个人学习草稿的文件。')}
/* Account storage is separate from anonymous drafts and from the historical keys. */
function switchAccount(userId){
  const next=userId?KEY+'-user-'+userId:KEY;
  if(next===storageKey)return;
  clearTimeout(syncTimer);syncGeneration++;
  if(!syncStatus.readOnly){try{localStorage.setItem(storageKey,JSON.stringify(state))}catch{}}
  storageKey=next;state={version:2,answers:{},wrong:[],favorites:[],notes:{},legacyRecords:{},updatedAt:null};restore();
  selected.clear();revealed.clear();metrics();
  if(userId&&window.PsychSync){const generation=syncGeneration;window.PsychSync.getAccountState().then(remote=>{
    if(remote&&generation===syncGeneration)applyRemote(remote);
  }).catch(error=>toast(error.message))}
}
function applyRemote(remote){
  if(!remote||typeof remote!=='object')return;
  const incoming=validState({...remote,version:2,notes:state.notes,legacyRecords:state.legacyRecords});
  state.answers=incoming.answers;state.wrong=incoming.wrong;state.favorites=incoming.favorites;
  state.updatedAt=new Date().toISOString();
  if(!syncStatus.readOnly){try{localStorage.setItem(storageKey,JSON.stringify(state))}catch{toast('同步成功，但本机缓存不可写，请导出备份。')}}
  metrics();render();
}
async function syncCurrent(){
  if(!syncStatus.authenticated||syncStatus.readOnly)return;
  const generation=syncGeneration,stamp=state.updatedAt;
  try{const remote=await window.PsychSync.sync(state);if(generation===syncGeneration&&stamp===state.updatedAt)applyRemote(remote)}
  catch(error){if(generation===syncGeneration)toast(error.message)}
}

let syncStatus={configured:false,authenticated:false,message:'尚未配置 · 仅本机保存'};
function syncPanel(){return `<article class="card"><h2>账号与跨设备同步</h2><div class="actions"><button class="btn" id="selfCheck">运行只读自检</button></div><div id="selfCheckResult" aria-live="polite"></div><p>Kiky 是你的显示名。安全登录使用邮箱链接；密码不会在此公开网页中保存。登录后通过服务端账户隔离同步答题进度、错题与收藏。</p><p class="tag">${esc(syncStatus.message||'尚未配置 · 仅本机保存')}</p>${syncStatus.conflict?'<p>云端已有另一设备的更新，未自动覆盖。本机离线队列仍保留。</p><button class="btn" id="keepCloud">保留云端</button><button class="btn" id="applyLocal">将本机操作应用到最新云端</button>':''}<p class="fine">${syncStatus.authenticated?'已登录：'+esc(syncStatus.email||'当前账户'):'当前未登录；本机学习记录继续保留。'}</p><div class="actions"><button class="btn primary" id="syncNow" ${!syncStatus.authenticated?'disabled':''}>同步学习记录</button><button class="btn" id="signOut" ${!syncStatus.authenticated?'disabled':''}>退出登录</button></div></article>${window.PSYCH_SYNC_CONFIG&&syncStatus.configured?'<article class="card"><h2>项目公开配置已接入</h2><p>现有项目 fdpofmiuprjtvjbtnrku 已配置，无需再次复制 key。账号与数据库允许名单仍须完成验证。</p></article>':`<article class="card"><h2>连接已获批准的 Supabase 项目</h2><p class="fine">仅填写项目 URL 和 publishable key（可公开客户端密钥）。不要输入 service_role、secret key、数据库密码或账户密码。保存配置本身不发送登录邮件。</p><label>项目 URL<input id="projectURL" type="url" placeholder="https://项目编号.supabase.co" style="width:100%;margin-bottom:16px"></label><label>Publishable key<input id="publishableKey" type="text" placeholder="sb_publishable_…" autocomplete="off" style="width:100%"></label><div class="actions"><button class="btn" id="configureSync" ${!window.PsychSync?'disabled':''}>保存并启用已批准项目</button></div>${!window.PsychSync?'<p class="pending" style="padding:10px">安全同步模块尚未接入，当前不会向后端发送数据。</p>':''}</article>`}<article class="card"><h2>邮箱链接登录</h2><label>账户邮箱<input id="loginEmail" type="email" autocomplete="email" placeholder="在此由你本人输入" style="width:100%"></label><div class="actions"><button class="btn primary" id="signIn" ${!syncStatus.configured||!window.PsychSync?'disabled':''}>发送登录链接到我的邮箱</button></div><p class="fine">需先在 Supabase 完成邮件认证、允许的回跳地址及用户数据隔离设置。</p></article>`}
async function resolveSync(choice){try{const remote=await window.PsychSync.resolveConflict(choice);if(remote)applyRemote(remote)}catch(error){toast(error.message)}}
async function runSync(action){try{await action()}catch(e){toast(e.message||'同步操作失败，本机记录仍保留。')}}
function bindSync(){if(view!=='sync')return;if($('selfCheck'))$('selfCheck').onclick=()=>runSync(async()=>{const checks=await window.PsychSync.selfCheck();$('selfCheckResult').innerHTML=checks.map(c=>'<p>'+esc(c.passed?'通过':'待处理')+' · '+esc(c.check)+'：'+esc(c.detail)+'</p>').join('')});if($('keepCloud'))$('keepCloud').onclick=()=>resolveSync('cloud');if($('applyLocal'))$('applyLocal').onclick=()=>resolveSync('local');if($('configureSync'))$('configureSync').onclick=()=>runSync(async()=>{const url=$('projectURL').value.trim(),publishableKey=$('publishableKey').value.trim();if(!/^https:\/\/[a-z0-9-]+\.supabase\.co\/?$/.test(url))throw Error('请输入官方 Supabase 项目的 HTTPS URL');if(!publishableKey.startsWith('sb_publishable_'))throw Error('只接受 sb_publishable_ 开头的公开客户端密钥');await window.PsychSync.configure({url,publishableKey});toast('已配置；请由本人主动请求登录链接。');if(window.PsychSync.getStatus)syncStatus=await window.PsychSync.getStatus();render()});$('signIn').onclick=()=>runSync(async()=>{const email=$('loginEmail').value.trim();if(!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email))throw Error('请输入本人账户邮箱');await window.PsychSync.signIn(email);toast('登录链接已请求，请查看你的邮箱。')});$('signOut').onclick=()=>runSync(async()=>{await window.PsychSync.signOut();switchAccount(null);toast('已退出；账号草稿隔离保存在本机。')});$('syncNow').onclick=()=>runSync(async()=>{const remote=await window.PsychSync.sync(state);if(remote)applyRemote(remote);toast('服务端已确认同步。')})}

async function init(){restore();if(window.PsychSync){if(window.PsychSync.subscribe)window.PsychSync.subscribe(s=>{syncStatus=s;switchAccount(s.authenticated?s.user_id:null);if(view==='sync')render()});if(window.PsychSync.getStatus)syncStatus=await window.PsychSync.getStatus();switchAccount(syncStatus.authenticated?syncStatus.user_id:null)};document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>{view=b.dataset.view;page=0;location.hash=view;render()});for(const id of ['subject','review','practice','search','coverageMode'])$(id).addEventListener(id==='search'?'input':'change',()=>{page=0;render()});$('importFile').onchange=async e=>{try{const file=e.target.files[0];if(!file)return;if(file.size>20*1024*1024)throw Error('请选择小于 20 MB 的学习记录');const raw=JSON.parse(await file.text());if(!['psychology-learning-record','psychology-combined-study-record','puxin-study-record'].includes(raw.format)||![1,2].includes(raw.version))throw Error('不支持的记录格式');merge(raw);toast('记录已合并导入；未匹配的旧题 ID 仍保留。')}catch(err){toast(err.message||'导入失败')}e.target.value=''};try{if(!syncStatus.authenticated)throw Error('请先登录并通过本人允许名单。');const raw=await window.PsychSync.getPrivateContent('psychology');for(const key of ['subjects','sources','knowledgePoints','memoryQuestions','predictions','corrections','predictionCoverage'])data[key]=array(raw[key]);data.trend=object(raw.trend)?raw.trend:{};data.version=raw.version;data.build=raw.build;$('subject').innerHTML+='<option disabled>────────</option>'+data.subjects.map(s=>`<option value="${esc(s.id)}">${esc(s.title)}</option>`).join('');$('version').textContent=`内容版本 ${raw.version||'未设置'} · ${typeof raw.build==='string'?raw.build:''}`;view=titles[location.hash.slice(1)]?location.hash.slice(1):'trend';metrics();render()}catch(err){metrics();render();$('content').insertAdjacentHTML('afterbegin',`<article class="card"><h2>内容尚未加载</h2><p>登录后从服务端读取本人私有内容；如尚未导入，请使用内容管理。</p><p class="fine">${esc(err.message)}</p><button class="btn" onclick="location.reload()">重新加载</button></article>`)}}
window.reloadPrivateStudy=init;window.clearStudyContent=()=>{data={subjects:[],sources:[],knowledgePoints:[],memoryQuestions:[],predictions:[],corrections:[],predictionCoverage:[],trend:{}};selected.clear();revealed.clear();$('content').replaceChildren();$('metrics').replaceChildren();$('subject').innerHTML='<option value="all">全部学科</option>';};init();
