/* One material per page; answers remain keyed by immutable child IDs. */
(function(root){
'use strict';
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])),list=v=>Array.isArray(v)?v:[],labels={cloze:'完形填空','reading-a':'阅读理解','reading-b':'新题型',translation:'翻译',writing:'写作','legacy-choice':'旧版单题','legacy-task':'旧版任务'};
const moduleLabels={objective:'完形 · 阅读 · 新题型',translation:'翻译任务',writing:'作文任务'};
function moduleFor(g){return g?.type==='translation'?'translation':g?.type==='writing'?'writing':'objective'}
function writingType(g){const q=g?.question_ids?.length===1?audit?.byQuestion.get(g.question_ids[0]):null,raw=g?.raw||g;const declared=raw?.writing_type??q?.writing_type;if(['small','large','framework'].includes(declared))return declared;const mapped=list(bank?.writingClassification).find(c=>c.group_id===g?.id);if(['small','large','framework'].includes(mapped?.writing_type)&&(!mapped.module||mapped.module==='writing'))return mapped.writing_type;if(q?.original_number===49||q?.original_number===51)return 'small';if(q?.original_number===52)return 'large';return 'unclassified'}
const routeURL=()=> '#english/'+(nav.module||'objective')+(nav.group_id?'/'+encodeURIComponent(nav.group_id):'');
let api,host,main,owner=null,status={},bank=null,audit=null,questionAudit=null,epoch=0,loading=null,visible=false,record=null,nav=null,revealed=new Set(),syncTimer=null,scrollTimer=null,restoring=false,displayedRoute=null;
const empty=()=>({version:1,answers:{},wrong:[],favorites:[],notes:{},selections:{},history:[]});
const recordKey=()=>`english-learning-v1-user-${owner}`,navKey=()=>`english-navigation-v1-user-${owner}`,version=()=>bank?.version??bank?.content_package_version??bank?.subject_version;
const read=(key,fallback)=>{try{return JSON.parse(localStorage.getItem(key))||fallback}catch{return fallback}},el=id=>main?.querySelector('#'+id),scope=()=>JSON.stringify(['english',nav.paper,version(),nav.mode,nav.year,nav.type,nav.search,nav.module,nav.writing_type]);
function persist(){if(!owner||!record)return;localStorage.setItem(recordKey(),JSON.stringify(record))}
function persistNav(){if(!owner||!nav||!bank)return;const stored=read(navKey(),{version:1,slots:{}});if(!stored.slots||typeof stored.slots!=='object')stored.slots={};const current={...nav,package_version:version()};stored.slots[scope()]=current;stored.last=current;stored.modules=stored.modules||{};stored.modules[nav.module]=current;localStorage.setItem(navKey(),JSON.stringify(stored));if(visible&&(routeIsCurrent()||location.hash===displayedRoute)){history.replaceState({...history.state,englishOwner:owner,englishNavigation:{...nav}},'',routeURL());displayedRoute=location.hash;}if(visible)root.SubjectRoom?.remember('english')}
function activeAnswer(q){const a=record.answers[q.id],proof=list(bank.questionReviews).find(p=>p.id===q.id);return a&&a.content_version===version()&&a.question_sha256===proof?.question_sha256?a:null}
function activeDraft(q){const d=record.notes[q.id];return d?.content_version===version()?d:null}
function answered(q){return !!activeAnswer(q)||!!activeDraft(q)?.text?.trim()}
function matches(g,pin=true){if(moduleFor(g)!==nav.module||nav.module==='writing'&&nav.writing_type!=='all'&&writingType(g)!==nav.writing_type)return false;if(nav.paper!=='all'&&g.paper_type!==nav.paper||nav.year!=='all'&&String(g.year)!==nav.year||nav.type!=='all'&&g.type!==nav.type)return false;if(nav.search&&!JSON.stringify([g.title,g.original_text,...g.question_ids.map(id=>audit.byQuestion.get(id).prompt)]).toLowerCase().includes(nav.search.toLowerCase()))return false;if(pin&&g.id===nav.group_id)return true;const qs=g.question_ids.map(id=>audit.byQuestion.get(id));return nav.mode==='all'||nav.mode==='unanswered'&&qs.some(q=>!answered(q))||nav.mode==='mistakes'&&qs.some(q=>record.wrong.includes(q.id)&&!!activeAnswer(q))}
function groups(){return audit?audit.groups.filter(g=>matches(g)):[]}
function activeGroup(){return audit?.groups.find(g=>g.id===nav?.group_id)}
function writable(){return owner&&status.authenticated&&!status.readOnly}
function allowed(g,q){return writable()&&audit.accepted.has(g.id)&&questionAudit.accepted.has(q)&&q.practice_enabled!==false&&q.safe_for_quiz!==false}
function notice(text){if(el('englishStatus'))el('englishStatus').textContent=text}
function archive(id,kind,value){if(!value)return;const token=JSON.stringify([id,kind,value.content_version,value.time,value.attempts]);if(!record.history.some(h=>h.token===token))record.history.push({token,question_id:id,kind,record:structuredClone(value)})}
function mount(){if(main)return;main=document.createElement('main');main.id='englishStudyMain';main.hidden=true;main.innerHTML='<header><div><p class="eyebrow">ENGLISH · FULL MATERIAL</p><h1 id="englishTitle">英语二整篇练习</h1></div></header><p id="englishStatus" class="notice" role="status"></p><section class="english-toolbar" aria-label="英语整组筛选"><label>试卷<select id="englishPaper"><option value="all">全部试卷</option></select></label><label>年份<select id="englishYear"><option value="all">全部年份</option></select></label><label>题型<select id="englishType"><option value="all">全部题型</option></select></label><label id="englishWritingLabel" hidden>作文类别<select id="englishWritingType"><option value="all">全部作文</option><option value="small">小作文</option><option value="large">大作文</option><option value="framework">框架</option><option value="unclassified">未分类作文</option></select></label><label>范围<select id="englishMode"><option value="all">全部材料</option><option value="unanswered">含未答题的整组</option><option value="mistakes">含当前版本错题的整组</option></select></label><label>搜索<input id="englishSearch" type="search" autocomplete="off"></label></section><div class="actions"><button class="btn" id="englishRefresh">核验权限并重新读取</button><button class="btn" id="englishLatest">保存草稿并读取新版</button><button class="btn" id="englishSync">同步英语答题与错题</button></div><p class="fine">整组保留全部原文与子题。未提交选项、草稿和阅读位置仅本机；跨设备记录没有内容版本凭据时作为历史保留，不自动计入当前结果。</p><div id="englishContent" aria-live="polite"></div>';host.append(main);
 for(const [name,key] of [['englishPaper','paper'],['englishYear','year'],['englishType','type'],['englishMode','mode'],['englishWritingType','writing_type'],['englishSearch','search']])el(name).addEventListener(name==='englishSearch'?'input':'change',()=>{captureAnchor();if(!nav)return;nav[key]=el(name).value;const saved=read(navKey(),{slots:{}}).slots?.[scope()];nav={...nav,group_id:null,current_question_id:null,anchor:'group',offset_within_anchor:0,...(saved||{})};render(false);restoreAnchor()});
 el('englishRefresh').onclick=()=>load(false);el('englishLatest').onclick=()=>load(true);el('englishSync').onclick=syncRecords;
 main.addEventListener('click',event=>{const b=event.target.closest('button');if(!b)return;if(b.dataset.egJump){jump(b.dataset.egJump);return}if(b.dataset.egMove){move(Number(b.dataset.egMove));return}if(b.dataset.egChoice){choose(b.dataset.egChoice,Number(b.dataset.index));return}if(b.dataset.egSubmit){submit(b.dataset.egSubmit);return}if(b.dataset.egReveal){captureAnchor();revealed.has(b.dataset.egReveal)?revealed.delete(b.dataset.egReveal):revealed.add(b.dataset.egReveal);render(false);restoreAnchor();return}if(b.dataset.egFavorite){const id=b.dataset.egFavorite;record.favorites=record.favorites.includes(id)?record.favorites.filter(x=>x!==id):[...record.favorites,id];persist();scheduleSync();render(false);return}});
 main.addEventListener('input',event=>{const t=event.target;if(!t.dataset.egDraft||!writable())return;const q=audit.byQuestion.get(t.dataset.egDraft),g=activeGroup();if(!q||!g||!allowed(g,q))return;const old=record.notes[q.id];if(old&&old.content_version!==version())archive(q.id,'draft',old);record.notes[q.id]={text:t.value,time:new Date().toISOString(),content_version:version()};nav.current_question_id=q.id;persist();captureAnchor()});
 main.addEventListener('focusin',event=>{const item=event.target.closest('[data-eg-question]');if(item){nav.current_question_id=item.dataset.egQuestion;captureAnchor()}});
 window.addEventListener('scroll',()=>{if(!visible||restoring||!bank)return;clearTimeout(scrollTimer);scrollTimer=setTimeout(captureAnchor,120)},{passive:true});window.addEventListener('pagehide',captureAnchor);
 window.addEventListener('popstate',()=>{if(visible&&bank&&history.state?.englishOwner===owner){const saved=history.state.englishNavigation;if(saved){nav={...nav,...saved};render(false);restoreAnchor()}}});
}
function setupControls(){const papers=[...new Set(audit.groups.map(g=>g.paper_type).filter(Boolean))],years=[...new Set(audit.groups.map(g=>g.year).filter(Number.isInteger))].sort((a,b)=>b-a),types=[...new Set(audit.groups.filter(g=>moduleFor(g)===nav.module).map(g=>g.type))];el('englishPaper').innerHTML='<option value="all">全部试卷</option>'+papers.map(v=>`<option value="${esc(v)}">${v==='english-i'?'英语一':'英语二'}</option>`).join('');el('englishYear').innerHTML='<option value="all">全部年份</option>'+years.map(v=>`<option value="${v}">${v||'年份未标'}</option>`).join('');el('englishType').innerHTML='<option value="all">全部题型</option>'+types.map(v=>`<option value="${esc(v)}">${esc(labels[v]||v)}</option>`).join('');for(const [id,key] of [['englishPaper','paper'],['englishYear','year'],['englishType','type'],['englishMode','mode'],['englishWritingType','writing_type']]){const select=el(id);if(![...select.options].some(o=>o.value===nav[key]))nav[key]='all';select.value=nav[key]}el('englishSearch').value=nav.search||'';el('englishWritingLabel').hidden=nav.module!=='writing';el('englishType').closest('label').hidden=nav.module!=='objective';el('englishTitle').textContent='英语二 · '+moduleLabels[nav.module]}
function sources(refs){return '<details class="details"><summary>材料与来源定位</summary>'+list(refs).map(ref=>{const sid=typeof ref==='string'?ref:ref.id??ref.source_id,s=audit.sources.get(sid)||{};const url=typeof s.url==='string'&&/^https?:\/\//.test(s.url)?s.url:'';return '<div class="reference">'+(url?`<a href="${esc(url)}" target="_blank" rel="noopener noreferrer">${esc(s.title||sid)}</a>`:esc(s.title||sid))+(typeof ref==='object'?'<p>'+esc(ref.locator||'')+'</p>':'')+'</div>'}).join('')+'</details>'}
function questionHTML(q,g){const entries=EnglishGroups.optionEntries(q),answer=activeAnswer(q),selection=record.selections[q.id]?.content_version===version()?record.selections[q.id].selected:answer?.selected||[],old=record.answers[q.id],draft=activeDraft(q),show=revealed.has(q.id),can=allowed(g,q),wrong=record.wrong.includes(q.id)&&!!answer;
 return `<section class="english-question${wrong?' english-wrong':''}" data-eg-question="${esc(q.id)}" data-eg-anchor="question:${esc(q.id)}"><h3 tabindex="-1">${esc(q.original_number??'任务')} · ${esc(q.title||q.prompt)}</h3><p class="fine">稳定题号：${esc(q.id)} · ${can?'当前子题与整组审校均通过':'练习未启用，以整组与子题审校范围为准'}${wrong?' · 当前版本错题':''}</p>${entries.length?`<div class="options" role="group" aria-label="第${esc(q.original_number)}题全部选项">${entries.map(([label,text],i)=>`<button class="option${selection.includes(i)?' selected':''}${show&&answer?(EnglishGroups.answerIndexes(q).includes(i)?' correct':selection.includes(i)?' incorrect':''):''}" data-eg-choice="${esc(q.id)}" data-index="${i}" aria-pressed="${selection.includes(i)}" ${can?'':'disabled'}><b>${esc(label)}</b><span>${esc(text)}</span></button>`).join('')}</div><button class="btn primary" data-eg-submit="${esc(q.id)}" ${can&&selection.length?'':'disabled'}>提交本题</button>`:`<label>完整作答（仅本机）<textarea data-eg-draft="${esc(q.id)}" rows="10" ${can?'':'disabled'}>${esc(draft?.text||'')}</textarea></label>`}<div class="actions"><button class="btn" data-eg-reveal="${esc(q.id)}">${show?'收起':'查看'}解析与变式</button><button class="btn" data-eg-favorite="${esc(q.id)}" ${writable()?'':'disabled'}>${record.favorites.includes(q.id)?'★ 已收藏':'☆ 收藏'}</button></div>${old&&!answer?'<details class="details"><summary>历史作答（不自动计入当前结果）</summary><p>'+esc(old.content_version||'版本未记录')+' · '+esc(old.attempts||1)+'次 · 保留原结果</p></details>':''}${record.notes[q.id]&&!draft?'<details class="details"><summary>历史草稿</summary><p>'+esc(record.notes[q.id].content_version||'版本未记录')+'</p><p>'+esc(record.notes[q.id].text)+'</p></details>':''}${show?`<div class="answer" data-eg-anchor="explanation:${esc(q.id)}"><p>${esc(q.explanation||q.plain_explanation||'本题解析待补，不据测试答案核准真实内容。')}</p>${list(q.answer_points).map(p=>'<p>'+esc(typeof p==='string'?p:p.point||p.explanation||p.label)+'</p>').join('')}<details><summary>变式考法</summary>${list(q.variants||q.variations).map(v=>'<p>'+esc(typeof v==='string'?v:JSON.stringify(v))+'</p>').join('')}</details></div>`:''}</section>`}
function render(resetAnchor=false){if(!bank||!audit||!nav)return;setupControls();if(nav.module==='writing'&&nav.writing_type==='framework'&&!groups().length){el('englishContent').innerHTML=writingFrameworks();persistNav();return;}const all=groups();let g=all.find(g=>g.id===nav.group_id),fallback=false;if(!g){g=all[0];fallback=!!nav.group_id;nav.group_id=g?.id||null;nav.current_question_id=g?.question_ids[0]||null;nav.anchor='group';nav.offset_within_anchor=0}else if(!g.question_ids.includes(nav.current_question_id))nav.current_question_id=g.question_ids[0];if(!g){el('englishContent').innerHTML='<article class="card"><h2>当前模块没有符合筛选的材料</h2><p>无资料不是错误。可调整筛选或导入本科资料；旧记录、草稿及整篇上下文保持原样。</p><button class="btn" data-room-manage="english">导入本科资料</button></article>';persistNav();return}const index=all.indexOf(g),reason=audit.failures.find(f=>f.group_id===g.id)?.reason;const paragraphs=g.original_text.split(/\n\s*\n|\r?\n/).filter(p=>p.trim());
 el('englishContent').innerHTML=`${fallback?'<p class="navigation-notice">原组或锚点在当前版本不可用，已退回可用组；历史记录保留。</p>':''}${audit.legacy?'<p class="notice">旧包未提供groups整篇结构，按原任务显示；不会推断缺失的阅读上下文。</p>':''}<article class="card english-material" data-eg-group="${esc(g.id)}"><h2 tabindex="-1" data-eg-anchor="group">${esc(g.title||labels[g.type])} · ${esc(g.year||'年份未标')}</h2><p class="fine">组号：${esc(g.id)} · ${esc(version())} · ${g.question_ids.length}个完整子任务</p>${reason?'<p class="notice">'+esc(reason)+' 不计作已审整组或已完成练习。</p>':''}<nav class="english-quick-nav" aria-label="同篇快捷定位"><button class="btn" data-eg-jump="passage">原文 / 任务材料</button><button class="btn" data-eg-jump="question:${esc(nav.current_question_id)}">作答区</button>${g.question_ids.map(qid=>`<button class="btn" data-eg-jump="question:${esc(qid)}">${esc(audit.byQuestion.get(qid).original_number??'任务')}</button>`).join('')}</nav><section class="english-passage" data-eg-anchor="passage"><h3>完整原文 / 任务材料</h3>${paragraphs.map((text,i)=>`<p lang="en" data-eg-anchor="passage:${i}">${esc(text)}</p>`).join('')}${list(g.attachments).map(a=>`<figure><img src="${esc(a.data_url)}" alt="${esc(a.alt)}"><figcaption>${esc(a.alt)}</figcaption></figure>`).join('')}</section>${list(g.shared_options).length?'<section class="english-shared-options"><h3>共享选项（完整保留）</h3>'+g.shared_options.map(o=>'<p><b>'+esc(o.label)+'</b> '+esc(o.text)+'</p>').join('')+'</section>':''}<div class="english-questions">${g.question_ids.map(id=>questionHTML(audit.byQuestion.get(id),g)).join('')}</div>${sources(g.source_refs)}</article><nav class="single-card-nav" aria-label="英语材料导航"><button class="btn" data-eg-move="-1" ${index===0?'disabled':''}>上一篇</button><span>第 ${index+1} / ${all.length} 篇<small>${esc(g.id)}</small></span><button class="btn" data-eg-move="1" ${index===all.length-1?'disabled':''}>下一篇</button></nav>`;
 if(nav.module==='writing'&&nav.writing_type==='framework')el('englishContent').insertAdjacentHTML('beforeend',writingFrameworks());persistNav();if(resetAnchor){nav.anchor='group';nav.offset_within_anchor=0;restoreAnchor()}
}
function writingFrameworks(){const fs=list(bank.frameworks).filter(f=>f.module!=='translation');return fs.length?'<article class="card"><h2>作文框架（训练资料）</h2><p>框架不计为整题审校通过或官方范文。</p></article>'+fs.map(f=>'<article class="card" data-eg-anchor="framework:'+esc(f.id)+'"><h2>'+esc(f.title||f.id)+'</h2><p class="fine">'+esc(f.id)+' · '+esc({small:'小作文',large:'大作文'}[f.writing_type]||'未分类框架')+'</p><p class="pre-line">'+esc(f.body||'')+'</p></article>').join(''):'<article class="card"><h2>作文框架资料尚未导入</h2><p>无资料不是错误；可导入本科框架资料，原作答记录保持原样。</p><button class="btn" data-room-manage="english">导入本科资料</button></article>'}
function routeIsCurrent(){const parts=location.hash.slice(1).split('/');if(parts[0]!=='english')return false;if(parts.length===1)return true;const explicit=Object.hasOwn(moduleLabels,parts[1]);let gid;try{gid=decodeURIComponent(parts.slice(explicit?2:1).join('/'))}catch{return false}return (!explicit||parts[1]===nav.module)&&(!gid||gid===nav.group_id)}
function applyRoute(){const parts=location.hash.slice(1).split('/');if(parts[0]!=='english')return;const stored=read(navKey(),{modules:{}}),explicit=Object.hasOwn(moduleLabels,parts[1]);let gid;try{gid=decodeURIComponent(parts.slice(explicit?2:1).join('/'))}catch{}const g=audit?.groups.find(g=>g.id===(gid||nav.group_id));const module=explicit?parts[1]:g?moduleFor(g):nav.module||'objective';if(module!==nav.module){const saved=stored.modules?.[module];nav={module,writing_type:'all',paper:'all',year:'all',type:'all',mode:'all',search:'',group_id:null,current_question_id:null,anchor:'group',offset_within_anchor:0,...saved,module};}if(gid&&gid!==nav.group_id){nav.group_id=gid;nav.current_question_id=null;nav.anchor='group';nav.offset_within_anchor=0;if(!explicit){nav.paper='all';nav.year='all';nav.type='all';nav.writing_type='all';nav.mode='all';nav.search=''}}}
function inset(){let n=12;for(const h of document.querySelectorAll('header,[data-study-fixed-header]')){const r=h.getBoundingClientRect(),position=getComputedStyle(h).position;if(['fixed','sticky'].includes(position)&&r.top<=0&&r.bottom>0)n=Math.max(n,r.bottom+12)}return n}
function findAnchor(name){return [...main.querySelectorAll('[data-eg-anchor]')].find(n=>n.dataset.egAnchor===name)}
function captureAnchor(){if(!visible||!bank||!nav||restoring)return;const nodes=[...main.querySelectorAll('[data-eg-anchor]')],line=inset();let found=nodes[0];for(const node of nodes)if(node.getBoundingClientRect().top<=line+2)found=node;if(found){nav.anchor=found.dataset.egAnchor;nav.offset_within_anchor=Math.max(0,Math.min(found.offsetHeight,Math.round(line-found.getBoundingClientRect().top)));if(/^(question|explanation):/.test(nav.anchor))nav.current_question_id=nav.anchor.slice(nav.anchor.indexOf(':')+1);persistNav()}}
function restoreAnchor(){if(!visible||!bank)return;const stamp=epoch;restoring=true;requestAnimationFrame(()=>{if(stamp!==epoch||!visible){restoring=false;return}let target=findAnchor(nav.anchor);if(!target){target=findAnchor('group');nav.anchor='group';nav.offset_within_anchor=0;notice('原锚点已不可用，回到当前组标题；旧记录保留。')}if(target){const offset=Math.max(0,Math.min(Number(nav.offset_within_anchor)||0,Math.max(0,target.offsetHeight-24)));window.scrollTo({top:Math.max(0,scrollY+target.getBoundingClientRect().top+offset-inset()),behavior:'auto'});if(nav.anchor==='group'||nav.anchor.startsWith('question:')){target.tabIndex=-1;target.focus({preventScroll:true})}}restoring=false;persistNav()})}
function jump(anchor){captureAnchor();nav.anchor=anchor;nav.offset_within_anchor=0;if(anchor.startsWith('question:'))nav.current_question_id=anchor.slice(9);persistNav();restoreAnchor()}
function move(delta){captureAnchor();const all=groups(),index=all.findIndex(g=>g.id===nav.group_id),next=all[index+delta];if(!next)return;nav.group_id=next.id;nav.current_question_id=next.question_ids[0];nav.anchor='group';nav.offset_within_anchor=0;history.pushState({englishOwner:owner,englishNavigation:{...nav}},'',routeURL());render(true)}
function choose(id,index){const q=audit.byQuestion.get(id),g=activeGroup();if(!q||!g||!allowed(g,q))return;captureAnchor();const prior=record.selections[id]?.content_version===version()?record.selections[id].selected:activeAnswer(q)?.selected||[],multiple=EnglishGroups.answerIndexes(q).length>1;record.selections[id]={selected:multiple?prior.includes(index)?prior.filter(i=>i!==index):[...prior,index]:[index],content_version:version()};nav.current_question_id=id;persist();render(false);restoreAnchor()}
function submit(id){const q=audit.byQuestion.get(id),g=activeGroup(),picked=record.selections[id]?.selected;if(!q||!g||!allowed(g,q)||record.selections[id]?.content_version!==version()||!picked?.length)return;captureAnchor();const old=record.answers[id];archive(id,'answer',old);const correct=[...picked].sort((a,b)=>a-b).join(',')===[...EnglishGroups.answerIndexes(q)].sort((a,b)=>a-b).join(',');record.answers[id]={correct,attempts:(old?.attempts||0)+1,selected:[...picked],time:new Date().toISOString(),content_version:version(),question_sha256:list(bank.questionReviews).find(p=>p.id===id).question_sha256};record.wrong=correct?record.wrong.filter(qid=>qid!==id):[...new Set([...record.wrong,id])];revealed.add(id);nav.current_question_id=id;persist();scheduleSync();render(false);restoreAnchor()}
function scheduleSync(){clearTimeout(syncTimer);if(typeof api.stageSubjectLocal==='function')try{api.stageSubjectLocal('english',record)}catch(e){notice('英语记录已保留本机；'+e.message)}syncTimer=setTimeout(syncRecords,1000)}
function mergeRemote(remote,before=structuredClone(record)){if(!remote)return;for(const [target,value] of Object.entries(remote.answers||{})){if(!target.startsWith('english:'))continue;const id=target.slice(8),local=record.answers[id];if(JSON.stringify(local)!==JSON.stringify(before.answers[id]))continue;if(local&&local.attempts>=value.attempts&&JSON.stringify(local.selected)===JSON.stringify(value.selected)&&local.correct===value.correct)continue;if(local)archive(id,'answer',local);record.answers[id]={...value,content_version:value.content_version||null,question_sha256:value.question_sha256||null}}for(const field of ['wrong','favorites']){const incoming=list(remote[field]).filter(id=>id.startsWith('english:')).map(id=>id.slice(8));const prior=new Set(list(before[field])),current=new Set(record[field]),next=new Set(incoming);for(const id of current)if(!prior.has(id))next.add(id);for(const id of prior)if(!current.has(id))next.delete(id);record[field]=[...next]}persist()}
async function syncRecords(){if(!owner||!record||!writable())return;const stamp=epoch,before=structuredClone(record);try{if(typeof api.syncSubject!=='function')throw Error('当前记录接口未提供英语科目同步，记录已保留本机。');const remote=await api.syncSubject('english',record);if(stamp!==epoch)return;mergeRemote(remote,before);notice('英语答题与错题同步已确认；草稿、未提交选项及阅读位置仅本机。')}catch(e){if(stamp===epoch)notice('本机记录保留；同步未完成：'+e.message)}}
async function load(preferLatest=false){if(loading)return loading;captureAnchor();const stamp=++epoch,previous={bank,audit,questionAudit,nav:nav?structuredClone(nav):null};el('englishRefresh').disabled=true;el('englishLatest').disabled=true;notice('正在核验本人权限并读取英语完整材料…');const work=(async()=>{try{const s=await api.getStatus();if(stamp!==epoch)return false;if(!s.authenticated||s.user_id!==owner)throw Error('当前账号权限尚未核验。');status=s;const raw=await api.getPrivateContent('english',()=>{}, {preferLatest,validatePayload:EnglishGroups.validate});if(stamp!==epoch)return false;const qAudit=await SubjectPackage.auditQuestionReviews(raw),gAudit=await EnglishGroups.audit(raw,qAudit,SubjectPackage);if(stamp!==epoch)return false;bank=raw;questionAudit=qAudit;audit=gAudit;const stored=read(navKey(),{slots:{}}),saved=stored.last;nav={module:'objective',writing_type:'all',paper:'all',year:'all',type:'all',mode:'all',search:'',group_id:null,current_question_id:null,anchor:'group',offset_within_anchor:0,...saved,...(nav||{})};applyRoute();
 if(saved?.package_version&&saved.package_version!==version()){nav.anchor='group';nav.offset_within_anchor=0;for(const [id,a] of Object.entries(record.answers))if(a.content_version!==version())archive(id,'answer',a);record.selections={};persist()}
 setupControls();render(false);notice(`当前加载 ${version()}；已核整组 ${audit.complete_groups} / ${audit.total_groups}。子题独审与整组完整性分别核对；不完整材料保持停用。仅当前包范围：${typeof bank.package_scope==='string'?bank.package_scope:bank.package_scope?JSON.stringify(bank.package_scope):'范围未提供，不表示目标全部完成'}`);restoreAnchor();return true;
 }catch(e){if(stamp!==epoch)return false;bank=previous.bank;audit=previous.audit;questionAudit=previous.questionAudit;nav=previous.nav;notice('读取未完成：'+e.message+'；当前可用版本及旧记录保留。');if(!bank)el('englishContent').innerHTML='<article class="card"><h2>英语二资料尚未就绪</h2><p>上传本科完整资料包后开始整篇练习；此处不预置假题，也不表示审校完成。</p><button class="btn primary" data-room-manage="english">进入本科资料管理</button></article>';return false}finally{if(stamp===epoch){el('englishRefresh').disabled=false;el('englishLatest').disabled=false}}})();loading=work;work.finally(()=>{if(loading===work)loading=null});return work}
function initialize(options){api=options.api;host=options.host;mount();api.subscribe?.(s=>{status=s;if(owner&&(!s.authenticated||s.user_id!==owner))reset();if(main&&s.readOnly)main.querySelectorAll('[data-eg-choice],[data-eg-submit],[data-eg-draft],[data-eg-favorite]').forEach(n=>n.disabled=true)})}
async function open(){const s=await api.getStatus();if(root.SubjectRoom&&root.SubjectRoom.getSubject()!=='english')return false;if(!s.authenticated){reset();return false}if(owner!==s.user_id){reset();owner=s.user_id;record={...empty(),...read(recordKey(),empty())};nav=null;const ownRecord=record,before=structuredClone(record);api.getAccountState?.().then(remote=>{if(record===ownRecord&&owner===s.user_id){mergeRemote(remote,before);if(visible&&bank){captureAnchor();render(false);restoreAnchor()}}}).catch(()=>{})}status=s;visible=true;main.hidden=false;if(!bank)return load(false);applyRoute();render(false);restoreAnchor();return true}
function hide(){captureAnchor();visible=false;if(main)main.hidden=true}
function reset(){displayedRoute=null;epoch++;clearTimeout(syncTimer);clearTimeout(scrollTimer);loading=null;bank=null;audit=null;questionAudit=null;owner=null;record=null;nav=null;revealed.clear();visible=false;if(main){main.hidden=true;el('englishContent').replaceChildren();notice('尚未读取本人英语材料。')}}
root.EnglishStudy={initialize,open,hide,reset,reload:load,captureAnchor};
})(window);
