/* Readonly views over existing source metadata and registered reference records. */
(function(root){
'use strict';
const list=v=>Array.isArray(v)?v:[],esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const labels={all:'全部来源',real:'真题（教辅重印）',xiao:'肖1000题',foundation:'徐涛基础题',high:'徐涛提高题',leg:'腿姐',prediction:'原创预测',mixed:'多来源待明确归属',other:'其他 / 未标来源'};
const modules={marx:'马克思主义基本原理',mao:'毛泽东思想和中国特色社会主义理论体系概论',xi:'习近平新时代中国特色社会主义思想概论',history:'中国近现代史纲要'};
function family(source){const title=source?.file_name||source?.title||'';if(/腿姐|陆寓丰/.test(title))return 'leg';if(/肖.*1000|1000题/.test(title))return 'xiao';if(/徐涛|通关优题库/.test(title)){if(/基础题篇/.test(title))return 'foundation';if(/提高题篇|拔高题篇/.test(title))return 'high';if(/强化真题集/.test(title))return 'real'}return 'other'}
function classification(q,bank){
 if(q.prediction===true||/^authored_/.test(q.source_type||''))return {source:'prediction',year:null};
 const registry=new Map(list(bank.sources).map(s=>[s.id,s])),refs=list(q.source_refs),questionRefs=refs.filter(r=>typeof r==='object'&&/^(question|original_question|question_material_and_subquestions)$/.test(r.role||'')),ids=(questionRefs.length?questionRefs:refs).map(r=>typeof r==='string'?r:r.id||r.source_id);
 if(!ids.length)ids.push(...list(q.source_ids));
 const families=[...new Set(ids.map(id=>family(registry.get(id))).filter(x=>x!=='other'))];
 if(q.source_type==='real_exam_reprinted_in_textbook'||q.past_exam===true){const year=Number(q.exam_year??q.year);return {source:families.includes('real')?'real':'other',year:Number.isInteger(year)&&year>=1900&&year<=2200?year:null}}
 return {source:families.length===1?families[0]:families.length?'mixed':'other',year:null};
}
function catalog(bank){const byID=new Map([...list(bank.memoryQuestions),...list(bank.predictions)].map(q=>[q.id,classification(q,bank)]));return {byID,sources:Object.keys(labels).filter(k=>k==='all'||[...byID.values()].some(v=>v.source===k)),years:[...new Set([...byID.values()].filter(v=>v.source==='real'&&v.year).map(v=>v.year))].sort((a,b)=>b-a)}}
// Keep the audit projection in the package; present only learning fields here.
const statusText={author_created_specific_learning_variant_not_past_exam:'作者编写的具体学习变式，非原真题',not_newly_cleared:'既有事实限制未解除，不代表当前事实已核验',source_book_time_actual_read_specific_current_legal_status_not_independently_verified:'保留原书时点；具体法律现行效力未独立核验',book_2025_reference_actual_read_official_fulltext_not_independently_verified:'保留教辅原时点；官方完整文本未独立核验',not_independently_verified_preserve_book_time_and_scope:'未作当前事实独立核验，保留原书时点和范围',no_exact_existing_question_link_do_not_invent:'没有精确关联原题，不推断题目对应关系',direct_or_chapter_context_support:'关联仅作原题或章节背景参考，不扩大练习授权',pending_independent_interpretation_review:'题意范围仍待独立审校',not_systematically_deduplicated_against_4008:'尚未与原题库系统去重，不据此增加原题计数',original_book_answer_table:'原教辅答案表，非官方命题答案'};
const humanLabels={reason:'范围说明',identity:'来源身份',scope:'适用范围',limits:'限制',limitations:'限制',summary:'说明',text:'原文',detail:'疑点说明',target:'疑点涉及范围',status:'审校范围',condition:'适用条件',conditions:'适用条件',when:'条件',result:'条件下的判断',support:'依据',original_reference_answer:'原教辅参考答案',earlier_independent_supplement_answer:'既有独立补答',does_not_clear_source_answer:'原答案身份保留',original_page:'原页情况',recovery_basis:'补录依据'};
function humanText(text){return String(text).replace(/current_version_unverified/g,'现行版本未核验').replace(/theory_hold/g,'理论范围限制').replace(/\bhold\b/g,'限制')}
function plain(text){return '<p class="pre-line">'+esc(humanText(text))+'</p>'}
function learningValue(v){if(v==null)return '';if(typeof v==='string')return plain(/^same_prompt_and_all_options_as_/.test(v)?'题干及全部选项与已登记原题相同，不计作新增原题。':statusText[v]||v);if(typeof v==='number')return plain(v);if(Array.isArray(v))return '<ul>'+v.map(x=>'<li>'+learningValue(x)+'</li>').join('')+'</ul>';if(typeof v==='object')return Object.entries(v).map(([k,x])=>{if(k==='obscured_field'&&typeof x==='string'&&/^options\.[A-D]$/.test(x))return section('补录选项',x.split('.').pop());if(k==='preserve_prior_source_scoped_hold'&&x===true)return plain('原有范围限制保留');if(!humanLabels[k]||x==null)return '';if(k==='status'&&typeof x==='string'&&!statusText[x]&&!/[\u3400-\u9fff]/.test(x))return '';return section(humanLabels[k],x,k)}).join('');return ''}
function section(label,v,key=''){if(v==null||v===''||Array.isArray(v)&&!v.length)return '';return '<section class="politics-reference-field"'+(key?' data-reference-section="'+esc(key)+'"':'')+'><h3>'+esc(label)+'</h3>'+learningValue(v)+'</section>'}
function refsHTML(refs,sources){const registry=new Map(list(sources).map(s=>[s.id||s.source_id,s]));return list(refs).map(ref=>{const r=typeof ref==='string'?{id:ref}:ref||{},s=registry.get(r.source_id||r.id)||{},pages=r.pdf_pages??r.pdf_page,printed=r.printed_pages??r.printed_page,format=v=>Array.isArray(v)?v.join('、'):String(v);const name=r.file_name||s.file_name||r.title||s.title||'来源名称未标注';return '<div class="reference">'+esc(name)+(pages!=null?' · PDF '+esc(format(pages))+' 页':'')+(printed!=null?' · 印刷 '+esc(format(printed))+' 页':'')+(r.locator?plain(r.locator):'')+(r.support?plain(r.support):'')+(r.limits?learningValue(r.limits):'')+(typeof r.url==='string'&&/^https?:\/\//.test(r.url)?'<a href="'+esc(r.url)+'" target="_blank" rel="noopener noreferrer">查看来源</a>':'')+'</div>'}).join('')}
function sourceSection(label,refs,sources){return list(refs).length?'<section class="politics-reference-field"><h3>'+esc(label)+'</h3>'+refsHTML(refs,sources)+'</section>':''}
function optionsHTML(options){const entries=Array.isArray(options)?options.map((o,i)=>[o?.key||o?.label||String.fromCharCode(65+i),typeof o==='object'?o.text:o]):options&&typeof options==='object'?Object.entries(options).map(([k,o])=>[k,typeof o==='object'?o.text:o]):[];return entries.map(([k,t])=>'<p class="pre-line" data-reference-option="'+esc(k)+'"><b>'+esc(k)+'</b> · '+esc(t??'')+'</p>').join('')}
function answerValue(r){return [r.original_reference_answer,r.source_reference_answer,r.original_reference_key,r.answer].find(v=>v!=null&&v!==''&&(!Array.isArray(v)||v.length))}
function answerHTML(v){return Array.isArray(v)&&v.every(x=>typeof x==='string'&&/^[A-D]$/.test(x))?plain(v.join('、')):learningValue(v)}
function variantsHTML(variants,sources){return list(variants).map((v,i)=>'<section class="politics-variant" data-reference-variant="'+i+'"><h3>变式 '+(i+1)+'（归属母例题，只读参考）</h3>'+(typeof v==='string'?plain(v):section('变式题目',v.prompt,'variant-prompt')+(v.options?'<h4>完整变式选项</h4>'+optionsHTML(v.options):'')+'<h4>变式参考答案</h4>'+answerHTML(v.answer)+section('通俗解析',v.explanation_plain,'variant-explanation-plain')+section('解析',v.explanation,'variant-explanation')+section('变式身份',v.identity||v.classification,'variant-identity')+sourceSection('变式来源',v.source_refs,sources))+'</section>').join('')}
function safeLegacyBody(r){const t=r.original_text||r.text||'';if(typeof t!=='string'||/[a-f0-9]{64}|local-sha256:|libfile_|\/Users\/|POL-(?:CORE|REAL|XTFOUND|XTHIGH|XS2027|LJ2027|PRED)-|"(?:sha256|source_id|ocr_ref|candidate_path|id|prompt|answer|prediction|practice_enabled)"\s*:/.test(t))return '<p>该资料缺少可读正文字段，原始追溯记录仍保留在私包中。</p>';return plain(t)}
function knowledgeHTML(r,sources){const hasBody=[r.knowledge_summary,r.explanation_plain,r.discrimination_reminder,r.distinction].some(v=>v!=null&&v!=='');return (hasBody?section('知识概述',r.knowledge_summary,'knowledge-summary')+section('通俗解析',r.explanation_plain,'explanation-plain')+section('辨析提醒',r.discrimination_reminder,'discrimination-reminder')+section('概念区分',r.distinction,'distinction'):safeLegacyBody(r))+section('范围与限制',r.fact_version_limit,'fact-version-limit')+section('原资料时间范围',r.source_time_scope,'source-time-scope')+section('保留的疑点',r.scope_review_hold,'scope-review-hold')+section('关联依据',r.linked_question_binding?.identity,'link-identity')+section('关联范围',r.linked_question_scope,'link-scope')+section('事实核验范围',r.official_current_fact_check,'fact-check')+section('当前事实核验范围',r.current_official_verification_status,'current-fact-check')+sourceSection('来源与定位',r.source_refs,sources)}
function exampleHTML(r,sources){const answer=answerValue(r);return section('原资料部别',r.book_part_name,'book-part-name')+section('原例题题目',r.prompt,'example-prompt')+'<h3>完整原选项</h3>'+optionsHTML(r.options)+'<section data-reference-section="original-answer"><h3>原参考答案与解析</h3>'+(answer==null?plain('原资料未提供参考答案'):answerHTML(answer))+'</section>'+section('答案身份',r.source_answer_identity||r.reference_answer_type,'answer-identity')+section('答案来源核验范围',r.original_answer_source_status,'answer-source-status')+section('答案配对依据',r.pairing_identity_basis,'pairing-identity-basis')+section('原答案审校范围',r.answer_status,'answer-status')+section('既有独立补答（不替代原教辅答案）',r.independent_supplement_answer,'independent-supplement')+section('答案差异与保留疑点',r.source_answer_conflict,'answer-conflict')+section('题意范围限制',r.theory_scope_hold,'theory-scope-hold')+(r.theory_hold===true?plain('原题理论范围疑点保留，例题不启用计分。'):'')+section('通俗解析',r.explanation_plain,'example-explanation')+section('解析身份',r.explanation_authorship,'explanation-authorship')+section('原资料时点说明',r.source_exam_time_note,'source-exam-time')+section('范围与限制',r.fact_version_limit,'example-fact-limit')+section('原例题身份范围',r.source_identity_overlap_status,'example-overlap')+section('选项补录说明',r.partial_obscuration_recovery,'option-recovery')+sourceSection('题目来源与定位',r.source_refs,sources)+sourceSection('原参考答案出处',r.answer_source_refs,sources)+sourceSection('解析依据',r.explanation_basis_refs,sources)+variantsHTML(r.variants,sources)}
function referenceTitle(r,kind){if(r.title)return r.title;if(kind==='knowledge')return '知识参考';const part=r.book_part,number=r.original_example_number??r.source_example_number;return '参考例题'+(part!=null?' · 第 '+part+' 部分':'')+(number!=null?' · 例 '+number:'')}
function linkedHTML(r,bank){return list(r.linked_reviewed_question_ids||r.question_links).map((link,i)=>{const id=typeof link==='string'?link:link.question_id||link.id,q=[...bank.memoryQuestions,...bank.predictions].find(q=>q.id===id);if(!q)return '';const cls=classification(q,bank),number=q.source_question_number??q.original_question_number;return '<a class="btn" href="#politics/'+(bank.predictions.includes(q)?'predictions':'memory')+'/'+encodeURIComponent(id)+'">关联原题 '+(i+1)+' · '+esc(labels[cls.source]||labels.other)+(number!=null?' · 原题号 '+esc(number):'')+'</a>'}).join('')}
function references(notes){const projected=new Map(list(notes?.records).map(r=>[r.id,r]));const raw=list(notes?.rawRecords).length?notes.rawRecords:list(notes?.records).filter(r=>r.adapter_projection?.source_field!=='notes.referenceExamples'),examples=list(notes?.referenceExamples);return [...raw.map(r=>({kind:'knowledge',module:r.module||'unclassified',record:{...r,text:projected.get(r.id)?.text}})),...examples.map(r=>({kind:'example',module:r.module||'unclassified',record:{...r,text:projected.get(r.id)?.text}}))]}
function renderReferences(notes,bank,filter={}){const rows=references(notes),matches=rows.filter(({kind,module,record:r})=>(!filter.kind||filter.kind==='all'||filter.kind===kind)&&(!filter.module||filter.module==='all'||filter.module===module)&&(!filter.search||JSON.stringify(r).toLowerCase().includes(filter.search.toLowerCase()))),page=Math.max(0,Math.min(Number(filter.page)||0,Math.max(0,Math.ceil(matches.length/20)-1))),slice=matches.slice(page*20,page*20+20);
 const sources=[...list(bank.sources),...list(notes.sources)];
 const body=slice.map(({kind,module,record:r})=>'<article class="card" data-politics-reference="'+esc(r.id)+'" data-reference-kind="'+kind+'"><h2>'+esc(referenceTitle(r,kind))+'</h2><p class="fine">'+esc(modules[module]||'原资料未标模块')+' · '+(kind==='example'?'参考书例题，非预测，只读参考，不启用计分':'核心知识参考，不新增练习授权')+'</p>'+(kind==='knowledge'?knowledgeHTML(r,sources):exampleHTML(r,sources))+linkedHTML(r,bank)+(r.partial_obscuration_recovery?.reviewed_question_id?linkedHTML({question_links:[r.partial_obscuration_recovery.reviewed_question_id]},bank):'')+'</article>').join('');
 return {count:matches.length,page,modules:[...new Set(rows.map(r=>r.module))],html:'<p class="fine">已有资料：'+rows.filter(r=>r.kind==='knowledge').length+'条核心知识 · '+rows.filter(r=>r.kind==='example').length+'条参考书例题；当前筛选 '+matches.length+' 条。按资料原有模块组织，不新增知识或练习授权。</p>'+(body||'<article class="card"><h2>当前筛选没有资料</h2><p>可重置筛选；原资料与记录保留。</p></article>')+'<nav class="single-card-nav"><button class="btn" data-pol-reference-page="-1" '+(page===0?'disabled':'')+'>上一页</button><span>第 '+(page+1)+' / '+Math.max(1,Math.ceil(matches.length/20))+' 页</span><button class="btn" data-pol-reference-page="1" '+((page+1)*20>=matches.length?'disabled':'')+'>下一页</button></nav>'};}
const api={labels,modules,family,classification,catalog,references,renderReferences,refsHTML,knowledgeHTML,exampleHTML,answerValue,variantsHTML,humanText};if(typeof module==='object'&&module.exports)module.exports=api;else root.PoliticsCatalog=api;
})(typeof window==='undefined'?globalThis:window);
