/* Graduate politics only. No legacy school bank or source content is bundled. */
(function(root){
'use strict';
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const list=v=>Array.isArray(v)?v:[];
const blank=()=>({answers:{},wrong:[],favorites:[],notes:{},selections:{},history:[]});
let api,main,owner=null,bank=null,audit=null,record=null,nav=null,status={},epoch=0,loading=null,visible=false,timer=null,referenceDoc=null,referenceError=null;
const el=id=>main?.querySelector('#'+id),key=()=>`politics-learning-v1-user-${owner}`,navKey=()=>`politics-navigation-v1-user-${owner}`;
const read=(k,f)=>{try{return JSON.parse(localStorage.getItem(k))||f}catch{return f}};
function slotKey(view=nav.view){const base=[bank?.version,view,nav.mode,nav.topic,nav.search];return JSON.stringify(nav.source!=='all'||nav.year!=='all'?[...base,nav.source||'all',nav.year||'all']:base)}
async function loadReferences(){if(referenceDoc)return true;const stamp=epoch,uid=owner;try{const doc=await api.getPrivateContent('notes',()=>{},{subject:'politics'});if(stamp!==epoch||uid!==owner)return false;referenceDoc=doc;referenceError=null;return true}catch(e){if(stamp===epoch)referenceError=e.message;return false}}
function validate(b){
 if(!b||b.subject!=='politics'||b.exam_scope!=='graduate-politics')throw Error('此页面只接收考研政治包；遗留高中政治/教资不属于本科。');
 if(typeof b.version!=='string'||!['subjects','sources','knowledgePoints','memoryQuestions','predictions'].every(k=>Array.isArray(b[k])))throw Error('考研政治包缺少版本或必需注册表。');
 const ids=new Set(),topics=new Set(['politics',...b.subjects.map(s=>s.id)]),sources=new Set();
 for(const s of b.sources){if(!s||typeof s.id!=='string'||sources.has(s.id))throw Error('来源ID缺失或重复。');sources.add(s.id)}
 for(const q of [...b.memoryQuestions,...b.predictions]){if(!q||typeof q.id!=='string'||!q.id||ids.has(q.id)||!topics.has(q.subject)||typeof q.prompt!=='string')throw Error('本科题号、学科或题干无效。');ids.add(q.id)}
 for(const q of b.memoryQuestions)if(!Array.isArray(q.options)||!Array.isArray(q.answer)||!q.answer.length||q.answer.some(i=>!Number.isInteger(i)||i<0||i>=q.options.length))throw Error('选择题必须保留完整选项和零基答案。');
 for(const q of b.predictions)if(!Array.isArray(q.answer_points))throw Error('主观题缺少完整作答要点。');
 if(b.frameworks!==undefined&&(!Array.isArray(b.frameworks)||b.frameworks.some(f=>!f||typeof f.id!=='string'||typeof f.title!=='string'||typeof f.body!=='string')))throw Error('框架资料结构无效。');return b;
}
function persist(){if(owner&&record)localStorage.setItem(key(),JSON.stringify(record))}
function saveNav(){if(!owner||!nav)return;const stored=read(navKey(),{slots:{}});stored.slots=stored.slots||{};stored.slots[slotKey()]={...nav};stored.last={...nav};localStorage.setItem(navKey(),JSON.stringify(stored));if(visible&&location.hash.startsWith('#politics'))history.replaceState({...history.state,roomOwner:owner,politicsNavigation:{...nav}},'','#politics/'+nav.view+(nav.id?'/'+encodeURIComponent(nav.id):''));if(visible&&location.hash.startsWith('#politics'))root.SubjectRoom?.remember('politics')}
function proof(q){return list(bank?.questionReviews).find(p=>p.id===q.id)}
function currentAnswer(q){const a=record.answers[q.id];return a?.content_version===bank.version&&a.question_sha256===proof(q)?.question_sha256?a:null}
function currentDraft(q){const d=record.notes[q.id];return d?.content_version===bank.version?d:null}
function allowed(q){return status.authenticated&&!status.readOnly&&audit?.accepted.has(q)&&q.practice_enabled!==false&&q.safe_for_quiz!==false}
function archive(id,kind,value){if(!value)return;const token=JSON.stringify([id,kind,value]);if(!record.history.some(h=>h.token===token))record.history.push({token,question_id:id,kind,record:structuredClone(value)})}
function notice(s){if(el('politicsStatus'))el('politicsStatus').textContent=s}
function syncStage(){if(!owner||status.readOnly)return;try{api.stageSubjectLocal('politics',record)}catch(e){notice('本机记录保留；'+e.message)}clearTimeout(timer);timer=setTimeout(sync,1000)}
function merge(remote,before){if(!remote)return;for(const [target,value] of Object.entries(remote.answers||{})){if(!target.startsWith('politics:'))continue;const id=target.slice(9),local=record.answers[id];if(JSON.stringify(local)!==JSON.stringify(before.answers[id]))continue;if(local&&local.attempts>=value.attempts&&local.correct===value.correct&&JSON.stringify(local.selected)===JSON.stringify(value.selected))continue;archive(id,'answer',local);record.answers[id]={...value,content_version:value.content_version||null,question_sha256:value.question_sha256||null}}
 for(const field of ['wrong','favorites']){const next=new Set(list(remote[field]).filter(id=>id.startsWith('politics:')).map(id=>id.slice(9))),prior=new Set(before[field]);for(const id of record[field])if(!prior.has(id))next.add(id);for(const id of prior)if(!record[field].includes(id))next.delete(id);record[field]=[...next]}persist()}
async function sync(){if(!owner||status.readOnly)return;const stamp=epoch,before=structuredClone(record);try{const remote=await api.syncSubject('politics',record);if(stamp!==epoch)return;merge(remote,before);notice('考研政治记录同步已确认；草稿与位置仅本机。')}catch(e){if(stamp===epoch)notice('本机记录保留；同步未完成：'+e.message)}}
function mount(host){main=document.createElement('main');main.id='politicsStudyMain';main.hidden=true;main.innerHTML='<header><div><p class="eyebrow">GRADUATE EXAM · POLITICS</p><h1 id="politicsTitle">考研政治学习室</h1></div></header><p id="politicsStatus" class="notice" role="status"></p><div class="actions"><button class="btn" id="politicsRefresh">核验权限并重新读取</button><button class="btn" id="politicsSync">同步本科记录</button><button class="btn" data-room-manage="politics">本科资料管理</button></div><section class="room-question-toolbar" id="politicsToolbar"><label>章节<select id="politicsTopic"><option value="all">全部章节</option></select></label><label>题目来源<select id="politicsSource"><option value="all">全部来源</option></select></label><label>真题年份<select id="politicsYear" disabled><option value="all">全部年份</option></select></label><label>范围<select id="politicsMode"><option value="all">全部题目</option><option value="unanswered">未作答</option><option value="wrong">当前版本错题</option><option value="favorites">收藏</option></select></label><label>搜索<input id="politicsSearch" type="search"></label></section><button class="btn" id="politicsResetFilters">重置筛选</button><section id="politicsReferenceToolbar" class="room-question-toolbar" hidden><label>资料类别<select id="politicsReferenceKind"><option value="all">知识与例题</option><option value="knowledge">核心知识原文</option><option value="example">参考书例题与变式</option></select></label><label>原资料模块<select id="politicsReferenceModule"><option value="all">全部模块</option></select></label><label>搜索<input type="search" id="politicsReferenceSearch"></label><button class="btn" id="politicsReferenceReset">重置资料筛选</button></section><div id="politicsContent" aria-live="polite"></div>';host.append(main);
 el('politicsRefresh').onclick=()=>load(false);el('politicsSync').onclick=sync;
 for(const [id,name] of [['politicsTopic','topic'],['politicsMode','mode'],['politicsSearch','search'],['politicsSource','source'],['politicsYear','year']])el(id).addEventListener(name==='search'?'input':'change',()=>{if(!nav)return;nav[name]=el(id).value;if(name==='source'){nav.year='all';el('politicsYear').value='all';el('politicsYear').disabled=nav.source!=='real'}const slot=read(navKey(),{slots:{}}).slots?.[slotKey()];nav.id=slot?.id||null;render(true)});
 el('politicsResetFilters').onclick=()=>{Object.assign(nav,{topic:'all',mode:'all',search:'',source:'all',year:'all',id:null});for(const id of ['politicsTopic','politicsMode','politicsSource','politicsYear'])el(id).value='all';el('politicsSearch').value='';el('politicsYear').disabled=true;render(true)};
 for(const [id,key] of [['politicsReferenceKind','kind'],['politicsReferenceModule','module'],['politicsReferenceSearch','search']])el(id).addEventListener(key==='search'?'input':'change',()=>{nav.reference={...nav.reference,[key]:el(id).value,page:0};render(false)});el('politicsReferenceReset').onclick=()=>{nav.reference={kind:'all',module:'all',search:'',page:0};render(false)};
 main.addEventListener('input',e=>{if(!e.target.dataset.polDraft||!bank)return;const q=bank.predictions.find(q=>q.id===e.target.dataset.polDraft);if(!q||!allowed(q))return;if(record.notes[q.id]?.content_version!==bank.version)archive(q.id,'draft',record.notes[q.id]);record.notes[q.id]={text:e.target.value,time:new Date().toISOString(),content_version:bank.version};persist()});
 main.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.polReferencePage){nav.reference={...nav.reference,page:(nav.reference?.page||0)+Number(b.dataset.polReferencePage)};render(true);return}if(b.dataset.polMove){move(Number(b.dataset.polMove));return}const id=b.dataset.polChoice||b.dataset.polSubmit||b.dataset.polFavorite||b.dataset.polReveal,q=bank&&[...bank.memoryQuestions,...bank.predictions].find(q=>q.id===id);if(!q)return;
 if(b.dataset.polChoice&&allowed(q)){const selected=record.selections[id]?.content_version===bank.version?record.selections[id].selected:[],i=Number(b.dataset.index);record.selections[id]={selected:q.answer.length>1?selected.includes(i)?selected.filter(x=>x!==i):[...selected,i]:[i],content_version:bank.version};persist();render(false)}
 if(b.dataset.polSubmit&&allowed(q)){const selected=record.selections[id]?.selected;if(record.selections[id]?.content_version!==bank.version||!selected?.length)return;archive(id,'answer',record.answers[id]);const correct=[...selected].sort((a,b)=>a-b).join(',')===[...q.answer].sort((a,b)=>a-b).join(',');record.answers[id]={correct,selected:[...selected],attempts:(record.answers[id]?.attempts||0)+1,time:new Date().toISOString(),content_version:bank.version,question_sha256:proof(q).question_sha256};record.wrong=correct?record.wrong.filter(x=>x!==id):[...new Set([...record.wrong,id])];persist();syncStage();render(false)}
 if(b.dataset.polFavorite&&!status.readOnly){record.favorites=record.favorites.includes(id)?record.favorites.filter(x=>x!==id):[...record.favorites,id];persist();syncStage();render(false)}if(b.dataset.polReveal){nav.reveal=nav.reveal===id?null:id;render(false)}});
 window.addEventListener('popstate',()=>{if(visible&&history.state?.roomOwner===owner&&history.state.politicsNavigation){nav={...nav,...history.state.politicsNavigation};render(true)}});
}
function filtered(){const qs=nav.view==='predictions'?bank.predictions:bank.memoryQuestions;return qs.filter(q=>(nav.source==='all'||root.PoliticsCatalog.classification(q,bank).source===nav.source)&&(nav.year==='all'||String(root.PoliticsCatalog.classification(q,bank).year)===nav.year)&&(nav.topic==='all'||q.subject===nav.topic)&&(nav.mode==='all'||nav.mode==='favorites'&&record.favorites.includes(q.id)||nav.mode==='wrong'&&record.wrong.includes(q.id)&&!!currentAnswer(q)||nav.mode==='unanswered'&&(q.id===nav.id||!currentAnswer(q)&&!currentDraft(q)?.text?.trim()))&&(!nav.search||JSON.stringify(q).toLowerCase().includes(nav.search.toLowerCase())))}
const sourceHTML=s=>'<div class="reference">'+(typeof s.url==='string'&&/^https?:\/\//.test(s.url)?`<a href="${esc(s.url)}" target="_blank" rel="noopener noreferrer">${esc(s.title||s.file_name||s.id)}</a>`:esc(s.title||s.file_name||s.id))+'</div>';
function render(align=false){if(!bank||!nav)return;const names={trend:'考研政治趋势解读',memory:'考研政治选择题',predictions:'考研政治主观题训练',frameworks:'考研政治知识框架与变式'};el('politicsTitle').textContent=names[nav.view]||names.memory;el('politicsToolbar').hidden=!['memory','predictions'].includes(nav.view);el('politicsResetFilters').hidden=el('politicsToolbar').hidden;el('politicsReferenceToolbar').hidden=nav.view!=='frameworks';for(const [id,key] of [['politicsTopic','topic'],['politicsMode','mode'],['politicsSearch','search'],['politicsSource','source'],['politicsYear','year']])el(id).value=nav[key];el('politicsYear').disabled=nav.source!=='real';let content='';
 if(['memory','predictions'].includes(nav.view)){const qs=filtered();let q=qs.find(q=>q.id===nav.id),fallback=false;if(!q){fallback=!!nav.id;q=qs[0];nav.id=q?.id||null}if(q){const i=qs.indexOf(q),answer=currentAnswer(q),selection=record.selections[q.id]?.content_version===bank.version?record.selections[q.id].selected:answer?.selected||[],can=allowed(q);content='<p class="fine">当前筛选 '+qs.length+' 题 · '+esc(root.PoliticsCatalog.labels[nav.source]||root.PoliticsCatalog.labels.all)+(nav.year!=='all'?' · 真题 '+esc(nav.year):'')+'</p>'+(fallback?'<p class="navigation-notice">原题在当前版本或筛选不可用，回到可用题；历史记录保留。</p>':'')+`<article class="card" data-pol-question="${esc(q.id)}"><h2 tabindex="-1">${esc(q.prompt)}</h2><p class="fine">${esc(q.id)} · ${esc(root.PoliticsCatalog.labels[root.PoliticsCatalog.classification(q,bank).source])}${root.PoliticsCatalog.classification(q,bank).year?' · 真题 '+root.PoliticsCatalog.classification(q,bank).year:''} · ${can?'当前整题独审通过':'待审 / 停用，不计练习'}${answer?' · '+(answer.correct?'正确':'当前版本错题'):''}</p>`+(Array.isArray(q.options)?'<div class="options">'+q.options.map((o,i)=>`<button class="option${selection.includes(i)?' selected':''}" data-pol-choice="${esc(q.id)}" data-index="${i}" aria-pressed="${selection.includes(i)}" ${can?'':'disabled'}><b>${String.fromCharCode(65+i)}</b><span>${esc(o)}</span></button>`).join('')+`</div><button class="btn primary" data-pol-submit="${esc(q.id)}" ${can&&selection.length?'':'disabled'}>提交本题</button>`:`<label>完整作答（草稿仅本机）<textarea rows="10" data-pol-draft="${esc(q.id)}" ${can?'':'disabled'}>${esc(currentDraft(q)?.text||'')}</textarea></label>`)+`<div class="actions"><button class="btn" data-pol-reveal="${esc(q.id)}">答案、解析与变式</button><button class="btn" data-pol-favorite="${esc(q.id)}" ${status.readOnly?'disabled':''}>${record.favorites.includes(q.id)?'★ 已收藏':'☆ 收藏'}</button></div>`;
 if(record.answers[q.id]&&!answer)content+='<p class="fine">保留历史作答，版本凭据不匹配，不自动计入本科当前结果。</p>';if(record.notes[q.id]&&!currentDraft(q))content+='<details><summary>旧版草稿</summary><p>'+esc(record.notes[q.id].text)+'</p></details>';
 if(nav.reveal===q.id)content+='<section class="answer"><h3>参考答案与解析</h3><p>'+esc(Array.isArray(q.answer)?q.answer.map(i=>String.fromCharCode(65+i)).join('、'):q.reference_answer||'')+'</p><p>'+esc(q.plain_explanation||q.explanation||'解析待补')+'</p>'+list(q.answer_points).map(p=>'<p>'+esc(typeof p==='string'?p:p.point||p.label||p.explanation)+'</p>').join('')+'<h3>变式考法（归属母题，不计作独立真题）</h3>'+[...list(q.variants||q.variations),...list(q.subanswers).flatMap(a=>a.variant?[a.variant]:list(a.variants))].map(v=>'<p>'+esc(typeof v==='string'?v:JSON.stringify(v))+'</p>').join('')+list(q.source_refs||q.source_ids).map(ref=>{const id=typeof ref==='string'?ref:ref.id;return sourceHTML(bank.sources.find(s=>s.id===id)||{id})}).join('')+'</section>';
 content+=`</article><nav class="single-card-nav"><button class="btn" data-pol-move="-1" ${i===0?'disabled':''}>上一题</button><span>第 ${i+1} / ${qs.length} 题<small>${esc(q.id)}</small></span><button class="btn" data-pol-move="1" ${i===qs.length-1?'disabled':''}>下一题</button></nav>`}else content='<article class="card"><h2>没有符合筛选的题目</h2><p>可调整章节、范围或搜索。已有记录保持原样。</p></article>';
 }else if(nav.view==='trend')content=root.SubjectTrend.render(bank,'politics');else if(nav.view==='frameworks'){if(referenceDoc){const refs=root.PoliticsCatalog.renderReferences(referenceDoc,bank,nav.reference||{});nav.reference={...nav.reference,page:refs.page};el('politicsReferenceModule').innerHTML='<option value="all">全部模块</option>'+refs.modules.map(m=>'<option value="'+esc(m)+'">'+esc(root.PoliticsCatalog.modules[m]||'原资料未标模块')+'</option>').join('');el('politicsReferenceKind').value=nav.reference.kind||'all';el('politicsReferenceModule').value=nav.reference.module||'all';el('politicsReferenceSearch').value=nav.reference.search||'';content=list(bank.frameworks).map(f=>'<article class="card" data-politics-native-framework="'+esc(f.id)+'"><h2>'+esc(f.title)+'</h2><p class="pre-line">'+esc(f.body)+'</p></article>').join('')+refs.html}else content='<article class="card"><h2>知识资料读取未完成</h2><p>'+esc(referenceError||'正在读取本科已导入的知识原文与例题…')+'</p><button class="btn" id="politicsReferenceRetry">重试读取知识资料</button></article>'}
 el('politicsContent').innerHTML=content;if(el('politicsReferenceRetry'))el('politicsReferenceRetry').onclick=async()=>{await loadReferences();render(false)};saveNav();if(align)requestAnimationFrame(()=>{if(!visible)return;const t=el('politicsContent').querySelector('h2');if(t){scrollTo({top:Math.max(0,scrollY+t.getBoundingClientRect().top-12),behavior:'auto'});t.focus({preventScroll:true})}})
}
function move(delta){const qs=filtered(),i=qs.findIndex(q=>q.id===nav.id),q=qs[i+delta];if(!q)return;nav.id=q.id;nav.reveal=null;history.pushState({roomOwner:owner,politicsNavigation:{...nav}},'','#politics/'+nav.view+'/'+encodeURIComponent(q.id));render(true)}
async function load(latest=false){if(loading)return loading;const stamp=++epoch,previous={bank,audit};notice('正在核验本人权限并读取考研政治包…');const work=(async()=>{try{const s=await api.getStatus();if(stamp!==epoch||s.user_id!==owner||!s.authenticated)return false;status=s;const raw=await api.getPrivateContent('politics',()=>{},{preferLatest:latest,validatePayload:validate});if(stamp!==epoch)return false;const reviewed=await SubjectPackage.auditQuestionReviews(raw);if(stamp!==epoch)return false;if(bank!==raw)referenceDoc=null;bank=raw;audit=reviewed;const catalog=root.PoliticsCatalog.catalog(bank);el('politicsSource').innerHTML=catalog.sources.map(k=>'<option value="'+k+'">'+esc(root.PoliticsCatalog.labels[k])+'</option>').join('');el('politicsYear').innerHTML='<option value="all">全部年份</option>'+catalog.years.map(y=>'<option value="'+y+'">'+y+'</option>').join('');if(!catalog.sources.includes(nav.source))nav.source='all';if(nav.source!=='real'||nav.year!=='all'&&!catalog.years.includes(Number(nav.year)))nav.year='all';el('politicsSource').value=nav.source;el('politicsYear').value=nav.year;el('politicsYear').disabled=nav.source!=='real';el('politicsTopic').innerHTML='<option value="all">全部章节</option>'+bank.subjects.map(s=>`<option value="${esc(s.id)}">${esc(s.title||s.id)}</option>`).join('');if(![...el('politicsTopic').options].some(o=>o.value===nav.topic))nav.topic='all';el('politicsTopic').value=nav.topic;el('politicsMode').value=nav.mode;el('politicsSearch').value=nav.search;if(nav.view==='frameworks')await loadReferences();render(true);notice('当前整题审核通过 '+audit.passed+' / '+audit.active+'；未审内容不计练习。');return true}catch(e){if(stamp!==epoch)return false;bank=previous.bank;audit=previous.audit;notice('读取未完成：'+e.message+(bank?'；旧版与记录保留。':'；本科尚无可加载资料。'));if(!bank){el('politicsToolbar').hidden=true;el('politicsContent').innerHTML='<article class="card"><h2>考研政治资料尚未就绪</h2><p>上传本人考研政治完整包后可开始；这里不预置假题，也不混入遗留高中政治/教资。</p><button class="btn primary" data-room-manage="politics">进入本科资料管理</button></article>'}return false}finally{if(stamp===epoch)loading=null}})();loading=work;return work}
async function open(view='memory',id=null){if(!['memory','predictions','trend','frameworks'].includes(view))view='memory';const s=await api.getStatus();if(root.SubjectRoom&&root.SubjectRoom.getSubject()!=='politics')return false;if(!s.authenticated){reset();return false}if(owner!==s.user_id){reset();owner=s.user_id;record={...blank(),...read(key(),blank())};nav={view:'memory',id:null,mode:'all',topic:'all',search:'',source:'all',year:'all',reference:{kind:'all',module:'all',search:'',page:0},...read(navKey(),{}).last};const ownRecord=record,before=structuredClone(record);api.getAccountState?.().then(remote=>{if(record===ownRecord){merge(remote,before);if(visible&&bank)render(false)}}).catch(()=>{})}status=s;visible=true;main.hidden=false;if(view&&nav.view!==view){const slot=read(navKey(),{slots:{}}).slots?.[slotKey(view)];nav={...nav,view,id:null,...(slot||{})}}if(id){nav.id=id;if(bank&&!filtered().some(q=>q.id===id))Object.assign(nav,{source:'all',year:'all',topic:'all',search:'',mode:'all'})}if(!bank)return load(false);if(nav.view==='frameworks')await loadReferences();render(true);return true}
function hide(){saveNav();visible=false;if(main)main.hidden=true}
function reset(){epoch++;clearTimeout(timer);loading=null;owner=null;bank=null;audit=null;referenceDoc=null;referenceError=null;record=null;nav=null;visible=false;if(main){main.hidden=true;el('politicsContent').replaceChildren()}}
function initialize(options){api=options.api;mount(options.host);api.subscribe?.(s=>{status=s;if(owner&&(!s.authenticated||s.user_id!==owner))reset();if(main&&s.readOnly)main.querySelectorAll('[data-pol-choice],[data-pol-submit],[data-pol-draft],[data-pol-favorite]').forEach(n=>n.disabled=true)})}
root.PoliticsStudy={initialize,open,hide,reset,reload:load,validate,getLoadedVersion:()=>bank?.version||null};
})(window);
