/* Readonly views over existing source metadata and registered reference records. */
(function(root){
'use strict';
const list=v=>Array.isArray(v)?v:[],esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const labels={all:'全部来源',real:'真题（教辅重印）',xiao:'肖1000题',foundation:'徐涛基础题',high:'徐涛提高题',leg:'腿姐',prediction:'原创预测',mixed:'多来源待明确归属',other:'其他 / 未标来源'};
const modules={marx:'马克思主义基本原理',mao:'毛泽东思想和中国特色社会主义理论体系概论',xi:'习近平新时代中国特色社会主义思想概论',history:'中国近现代史纲要'};
function family(source){const title=source?.file_name||source?.title||'';if(/腿姐|陆寓丰/.test(title))return 'leg';if(/肖.*1000|1000题/.test(title))return 'xiao';if(/徐涛|通关优题库/.test(title)){if(/基础题篇/.test(title))return 'foundation';if(/提高题篇|拔高题篇/.test(title))return 'high';if(/强化真题集/.test(title))return 'real'}return 'other'}
function classification(q,bank){
 if(q.prediction===true||/^authored_/.test(q.source_type||''))return {source:'prediction',year:null};
 const registry=new Map(list(bank.sources).map(s=>[s.id,s])),refs=list(q.source_refs),questionRefs=refs.filter(r=>typeof r==='object'&&/^(question|original_question|question_material_and_subquestions)$/.test(r.role||'')),ids=(questionRefs.length?questionRefs:refs).map(r=>typeof r==='string'?r:r.id||r.source_id);
 if(!ids.length)ids.push(...list(q.source_ids));
 const families=[...new Set(ids.map(id=>family(registry.get(id))).filter(x=>x!=='other'))];
 if(q.source_type==='real_exam_reprinted_in_textbook'||q.past_exam===true){const year=Number(q.exam_year??q.year);return {source:families.includes('real')?'real':'other',year:Number.isInteger(year)&&year>=1900&&year<=2200?year:null}}
 return {source:families.length===1?families[0]:families.length?'mixed':'other',year:null};
}
function catalog(bank){const byID=new Map([...list(bank.memoryQuestions),...list(bank.predictions)].map(q=>[q.id,classification(q,bank)]));return {byID,sources:Object.keys(labels).filter(k=>k==='all'||[...byID.values()].some(v=>v.source===k)),years:[...new Set([...byID.values()].filter(v=>v.source==='real'&&v.year).map(v=>v.year))].sort((a,b)=>b-a)}}
function refsHTML(refs,sources){const registry=new Map(list(sources).map(s=>[s.id||s.source_id,s]));return list(refs).map(ref=>{const r=typeof ref==='string'?{id:ref}:ref,s=registry.get(r.id||r.source_id)||{};return '<div class="reference">'+esc(s.title||s.file_name||r.file_name||r.id||r.source_id)+'<p class="fine">'+esc(r.locator||'')+(r.pdf_page?' · PDF '+esc(r.pdf_page):r.pdf_pages?' · PDF '+esc(r.pdf_pages.join(', ')):'')+'</p></div>'}).join('')}
function references(notes){const projected=new Map(list(notes?.records).map(r=>[r.id,r]));const raw=list(notes?.rawRecords).length?notes.rawRecords:list(notes?.records).filter(r=>r.adapter_projection?.source_field!=='notes.referenceExamples'),examples=list(notes?.referenceExamples);return [...raw.map(r=>({kind:'knowledge',module:r.module||'unclassified',record:{...r,text:projected.get(r.id)?.text}})),...examples.map(r=>({kind:'example',module:r.module||'unclassified',record:{...r,text:projected.get(r.id)?.text}}))]}
function renderReferences(notes,bank,filter={}){const rows=references(notes),matches=rows.filter(({kind,module,record:r})=>(!filter.kind||filter.kind==='all'||filter.kind===kind)&&(!filter.module||filter.module==='all'||filter.module===module)&&(!filter.search||JSON.stringify(r).toLowerCase().includes(filter.search.toLowerCase()))),page=Math.max(0,Math.min(Number(filter.page)||0,Math.max(0,Math.ceil(matches.length/20)-1))),slice=matches.slice(page*20,page*20+20);
 const body=slice.map(({kind,module,record:r})=>'<article class="card" data-politics-reference="'+esc(r.id)+'" data-reference-kind="'+kind+'"><h2>'+esc(r.title||r.id)+'</h2><p class="fine">'+esc(r.id)+' · '+esc(modules[module]||'原资料未标模块')+' · '+(kind==='example'?'参考书例题，非预测，不启用计分':'核心知识原文，只读参考')+'</p><p class="pre-line">'+esc(kind==='knowledge'?r.text||[r.knowledge_summary,r.explanation_plain,r.discrimination_reminder,r.distinction].filter(Boolean).join('\n\n'):r.prompt||'')+'</p>'+(kind==='example'?'<h3>完整原选项</h3>'+Object.entries(r.options||{}).map(([k,o],i)=>'<p>'+esc(Array.isArray(r.options)?o?.key||o?.label||String.fromCharCode(65+i):k)+' · '+esc(typeof o==='object'?o.text:o)+'</p>').join('')+'<h3>原参考答案与解析</h3><p class="pre-line">'+esc(typeof r.original_reference_answer==='string'?r.original_reference_answer:JSON.stringify(r.original_reference_answer??r.answer??''))+'</p><p class="pre-line">'+esc(r.explanation_plain||'')+'</p><h3>母例题的变式</h3>'+list(r.variants).map(v=>'<p class="pre-line">'+esc(typeof v==='string'?v:JSON.stringify(v))+'</p>').join(''):'')+'<p class="pre-line">'+esc(r.fact_version_limit||r.scope_review_hold||'')+'</p>'+(kind==='example'&&r.text?'<details class="details"><summary>例题完整原文与来源限制</summary><p class="pre-line">'+esc(r.text)+'</p></details>':'')+refsHTML(r.source_refs,bank.sources)+list(r.linked_reviewed_question_ids||r.question_links).map(link=>{const id=typeof link==='string'?link:link.question_id||link.id,q=[...bank.memoryQuestions,...bank.predictions].find(q=>q.id===id);return q?'<a class="btn" href="#politics/'+(bank.predictions.includes(q)?'predictions':'memory')+'/'+encodeURIComponent(id)+'">关联原题 '+esc(id)+'</a>':''}).join('')+'</article>').join('');
 return {count:matches.length,page,modules:[...new Set(rows.map(r=>r.module))],html:'<p class="fine">已有资料：'+rows.filter(r=>r.kind==='knowledge').length+'条核心知识 · '+rows.filter(r=>r.kind==='example').length+'条参考书例题；当前筛选 '+matches.length+' 条。按资料原有模块组织，不新增知识或练习授权。</p>'+(body||'<article class="card"><h2>当前筛选没有资料</h2><p>可重置筛选；原资料与记录保留。</p></article>')+'<nav class="single-card-nav"><button class="btn" data-pol-reference-page="-1" '+(page===0?'disabled':'')+'>上一页</button><span>第 '+(page+1)+' / '+Math.max(1,Math.ceil(matches.length/20))+' 页</span><button class="btn" data-pol-reference-page="1" '+((page+1)*20>=matches.length?'disabled':'')+'>下一页</button></nav>'};}
const api={labels,modules,family,classification,catalog,references,renderReferences,refsHTML};if(typeof module==='object'&&module.exports)module.exports=api;else root.PoliticsCatalog=api;
})(typeof window==='undefined'?globalThis:window);
