/* Subject entry and owner-scoped last actual room. Contains no learning bank. */
(function(root){
'use strict';
const courses={psychology:{name:'心理学',brand:'心理学学习室',hint:'北大题型为简答、论述。选择题仅作记忆辅助。',description:'趋势解析、记忆辅助、主观题预测、口诀与覆盖台账。'},politics:{name:'考研政治',brand:'考研政治学习室',hint:'考研政治与遗留高中政治/教资题库分别保存。',description:'选择题、主观题训练、知识框架、来源与变式。'},english:{name:'英语二',brand:'英语二学习室',hint:'完形与阅读按完整篇章；翻译与作文按完整任务。',description:'整篇练习、完整翻译和写作任务、框架与来源。'}};
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let api,callbacks,host,home,tools,owner=null,current=null,generation=0;
const read=(k,f)=>{try{return JSON.parse(localStorage.getItem(k))||f}catch{return f}},key=()=>`study-room-v1-user-${owner}`;
function store(){return read(key(),{visits:{}})}
function remember(subject=current){if(!owner||!courses[subject]||subject!==current||/^#(subjects|legacy)(?:\/|$)/.test(location.hash))return;const state=store();state.visits=state.visits||{};state.visits[subject]=location.hash;state.last={subject,route:location.hash};localStorage.setItem(key(),JSON.stringify(state));history.replaceState({...history.state,roomOwner:owner,roomSubject:subject},'',location.hash)}
function setCurrent(subject){if(current!==subject)root.clearManagedSubjectContent?.();current=subject;host.dataset.roomSubject=subject||'';const course=courses[subject];document.getElementById('roomBrand').firstChild.textContent=course?course.brand:'私人学习室';document.getElementById('roomTagline').textContent=course?'理解 · 回忆 · 迁移':'选择科目 · 保留进度';document.getElementById('roomCourseHint').textContent=course?.hint||'三科内容与进度独立保存。';document.getElementById('roomSubjectStatus').textContent=course?'当前科目：'+course.name:'本人私有学习内容';document.querySelectorAll('[data-room-menu]').forEach(n=>n.hidden=n.dataset.roomMenu!==subject);document.querySelectorAll('[data-study-subject]').forEach(b=>{b.classList.toggle('active',b.dataset.studySubject===subject);b.setAttribute('aria-pressed',String(b.dataset.studySubject===subject))});root.PrivateContentManager?.setSubject?.(subject||'psychology');document.getElementById('accountBackup').textContent=!subject||subject==='psychology'?'备份与恢复 · 学习统计':'本科学习进度';document.getElementById('managerTitle').textContent=(course?.name||'本科')+'题库与资料管理';document.querySelectorAll('[data-management-section="corrections"],[data-management-section="sources"]').forEach(b=>b.hidden=subject!=='psychology')}
function hideHomeTools(){home.hidden=true;tools.hidden=true;generation++}
function hideStudies(){root.EnglishStudy?.hide();root.PoliticsStudy?.hide();document.getElementById('studyMain').hidden=true;document.getElementById('managePanel').hidden=true}
function showHome(){generation++;hideStudies();tools.hidden=true;home.hidden=false;setCurrent(null);home.innerHTML='<header><div><p class="eyebrow">PRIVATE STUDY ROOMS</p><h1>选择学习科目</h1></div></header><p class="notice">各科题库、版本、学习记录与进度分别保存。已导入内容才会显示题目；资料未就绪时可先进入管理页。</p><section class="room-course-cards">'+Object.entries(courses).map(([id,c])=>'<article class="card"><p class="eyebrow">'+(id==='english'?'ENGLISH II':id==='politics'?'GRADUATE POLITICS':'PSYCHOLOGY')+'</p><h2>'+esc(c.name)+'</h2><p>'+esc(c.description)+'</p><div class="actions"><button class="btn primary" data-study-subject="'+id+'">进入'+esc(c.name)+'</button><button class="btn" data-room-manage="'+id+'">本科资料管理</button></div></article>').join('')+'</section><p class="fine">没有历史位置时展示此页；有历史时优先恢复最后实际科目、栏目和题目。侧栏随时可切换科目。</p><p><a href="#legacy" data-room-legacy>遗留高中政治 / 教资入口</a>独立保留，不属于考研政治。</p>'}
function routeFor(subject){const saved=store().visits?.[subject];if(typeof saved==='string'&&saved.startsWith('#')&&!saved.startsWith('#subjects'))return saved;if(subject==='psychology'){const legacy=read(`psychology-learning-v2-user-${owner}:navigation:psychology:v1`,{}).last;return '#'+(legacy?.route||legacy?.view||'trend')}if(subject==='english'){const last=read(`english-navigation-v1-user-${owner}`,{}).last;return '#english'+(last?.group_id?'/'+encodeURIComponent(last.group_id):'')}const last=read(`politics-navigation-v1-user-${owner}`,{}).last;return '#politics/'+(last?.view||'overview')+(last?.id?'/'+encodeURIComponent(last.id):'')}
function navigate(route,replace=false){if(!owner)return;if(replace)history.replaceState({...history.state,roomOwner:owner,roomSubject:current},'',route);else history.pushState({roomOwner:owner,roomSubject:current},'',route);window.dispatchEvent(new HashChangeEvent('hashchange'))}
function select(subject){if(!courses[subject])return;remember();setCurrent(subject);navigate(routeFor(subject))}
function ownerChanged(uid){if(owner===uid)return;root.clearManagedSubjectContent?.();owner=uid;current=null;generation++;tools.replaceChildren();tools.hidden=true;home.hidden=true;const state=store(),legacy=read(`psychology-learning-v2-user-${owner}:navigation:psychology:v1`,{}).last;const inherited=history.state?.roomOwner||history.state?.englishOwner||history.state?.studyNavigation?.owner;const foreign=inherited&&![owner,`psychology-learning-v2-user-${owner}`].includes(inherited);if(!location.hash||foreign){let route=state.last&&courses[state.last.subject]?state.last.route:null;if(!route&&legacy)route='#'+(legacy.route||legacy.view||'trend');if(!route){const en=read(`english-navigation-v1-user-${owner}`,{}).last;if(en)route='#english'+(en.group_id?'/'+encodeURIComponent(en.group_id):'')}history.replaceState({...history.state,roomOwner:owner,roomSubject:state.last?.subject||(legacy?'psychology':route?.startsWith('#english')?'english':null)},'',route||'#subjects')}setCurrent(null)}
async function showEnglishTool(section){const stamp=++generation;hideStudies();home.hidden=true;tools.hidden=false;tools.innerHTML='<header><h1>'+esc(courses.english.name)+' · '+esc({trend:'趋势解读',frameworks:'作文框架资料',sources:'材料与来源',progress:'本科进度'}[section]||'资料')+'</h1></header><p class="notice">正在核验本人权限并读取本科资料…</p>';try{const bank=await api.getPrivateContent('english',()=>{},{validatePayload:EnglishGroups.validate});if(stamp!==generation)return;const qa=await SubjectPackage.auditQuestionReviews(bank),ga=await EnglishGroups.audit(bank,qa,SubjectPackage);if(stamp!==generation)return;let body='';if(section==='trend')body=root.SubjectTrend.render(bank,'english');else if(section==='frameworks')body=Array.isArray(bank.frameworks)&&bank.frameworks.length?bank.frameworks.filter(f=>f.module!=='translation').map(f=>'<article class="card"><h2>'+esc(f.title||f.id)+'</h2><p class="pre-line">'+esc(f.body||'')+'</p><p class="fine">资料声明：'+esc(f.review_status||'未标注审校范围')+'；训练框架不视作官方范文。</p></article>').join(''):'<article class="card"><h2>框架资料尚未导入</h2><p>本科包可提供作文结构、翻译步骤和训练要点；完整翻译与作文仍在整篇任务页。</p></article>';else if(section==='sources')body='<article class="card"><h2>本科材料与来源注册表</h2>'+bank.sources.map(s=>'<div class="reference">'+(typeof s.url==='string'&&/^https?:\/\//.test(s.url)?`<a href="${esc(s.url)}" target="_blank" rel="noopener noreferrer">${esc(s.title||s.file_name||s.id)}</a>`:esc(s.title||s.file_name||s.id))+'</div>').join('')+'</article>';else{const r=read(`english-learning-v1-user-${owner}`,{answers:{},wrong:[],favorites:[],notes:{}}),qs=[...bank.memoryQuestions,...bank.predictions],current=q=>r.answers?.[q.id]?.content_version===bank.version&&r.answers[q.id].question_sha256===bank.questionReviews?.find(p=>p.id===q.id)?.question_sha256;body='<article class="card"><h2>英语二当前版本进度</h2><p>已核整组 '+ga.complete_groups+' / '+ga.total_groups+' · 作答 '+qs.filter(current).length+' · 当前错题 '+qs.filter(q=>current(q)&&r.wrong?.includes(q.id)).length+' · 本科收藏 '+qs.filter(q=>r.favorites?.includes(q.id)).length+' · 本机草稿 '+bank.predictions.filter(q=>r.notes?.[q.id]?.content_version===bank.version&&r.notes[q.id].text?.trim()).length+'</p><p>历史或缺版本凭据的作答保留，不自动计入当前结果；草稿与位置仅本机。</p></article>'}tools.innerHTML='<header><h1>'+esc(courses.english.name)+' · '+esc({trend:'趋势解读',frameworks:'作文框架资料',sources:'材料与来源',progress:'本科进度'}[section])+'</h1></header><p class="fine">当前版本 '+esc(bank.version)+' · 仅当前包范围：'+esc(typeof bank.package_scope==='string'?bank.package_scope:bank.package_scope?JSON.stringify(bank.package_scope):'范围未提供，不表示目标全部完成')+'</p>'+body+'<button class="btn" data-room-manage="english">本科资料管理</button>'}catch(e){if(stamp!==generation)return;tools.innerHTML='<header><h1>英语二资料</h1></header><article class="card"><h2>本科资料尚未就绪</h2><p>'+esc(e.message)+'</p><button class="btn primary" data-room-manage="english">上传本科完整包</button></article>'}}
async function managerVersion(subject){const stamp=generation;let box=document.getElementById('roomManagerVersion');if(!box){box=document.createElement('p');box.id='roomManagerVersion';box.className='notice';document.getElementById('managerVersionSection').prepend(box)}box.hidden=subject==='psychology';if(subject==='psychology')return;box.textContent=courses[subject].name+'：正在读取本科版本清单…';try{const m=await api.getPrivateContentManifest(subject);if(stamp!==generation||subject!==current)return;box.textContent='服务端本科包：'+m.package_version+' · SHA '+m.sha256.slice(0,12)+'。练习页可保留已选旧版；显式读取新版后切换。'}catch(e){if(stamp===generation&&subject===current)box.textContent=courses[subject].name+'完整包尚未就绪，或版本读取未完成：'+e.message}}
function restoreRoute(){if(!owner)return false;const hash=location.hash.slice(1);if(hash==='legacy'){showHome();home.innerHTML='<header><h1>遗留课程入口说明</h1></header><article class="card"><h2>高中政治 / 教资旧入口独立保留</h2><p>旧课程不属于考研政治。本页不把既有599道高中政治题转入考研题库，也不预置未导入内容。</p><p>旧公开链接当前仍返回登录入口；既有私有留存与学习记录保持原样，需单独迁移时再核对原课程。</p><a href="politics/index.html">旧链接（返回登录入口）</a><button class="btn" data-room-home>返回三科选择</button></article>';return true}if(hash==='subjects'||!hash){showHome();return true}if(hash==='english'||hash.startsWith('english/')){hideHomeTools();setCurrent('english');callbacks.english();remember();return true}if(hash.startsWith('english-tools/')){setCurrent('english');showEnglishTool(hash.split('/')[1]);remember();return true}if(hash==='politics'||hash.startsWith('politics/')){hideHomeTools();setCurrent('politics');hideStudies();let id=null;try{id=hash.split('/')[2]?decodeURIComponent(hash.split('/').slice(2).join('/')):null}catch{}root.PoliticsStudy.open(hash.split('/')[1]||'overview',id);remember();return true}if(hash==='manage'||hash.startsWith('manage/')||hash==='notes'){hideHomeTools();const subject=(history.state?.roomOwner===owner&&courses[history.state.roomSubject]?history.state.roomSubject:null)||current||store().last?.subject||'psychology';setCurrent(subject);callbacks.manager(hash==='notes'?'notes':hash.split('/')[1]||'bank');if(subject==='psychology')callbacks.ensurePsychology();managerVersion(subject);remember();return true}hideHomeTools();setCurrent('psychology');callbacks.psychology(hash);remember();return true}
function openManager(subject=current||'psychology',section='bank'){remember();setCurrent(subject);navigate('#manage'+(section==='bank'?'':'/'+section))}
async function openImported(subject){remember();setCurrent(subject);navigate(subject==='psychology'?'#memory':subject==='english'?'#english':'#politics/overview');if(subject==='psychology'){await callbacks.ensurePsychology();await root.reloadPrivateStudy?.({preferLatest:true})}else if(subject==='english'){await root.EnglishStudy.open();await root.EnglishStudy.reload(true)}else{await root.PoliticsStudy.open();await root.PoliticsStudy.reload(true)}}
function reset(){owner=null;current=null;generation++;if(tools){tools.replaceChildren();tools.hidden=true}if(home)home.hidden=true}
function initialize(options){api=options.api;callbacks=options.callbacks;host=options.host;home=document.createElement('main');home.id='subjectHome';home.hidden=true;tools=document.createElement('main');tools.id='subjectTools';tools.hidden=true;host.append(home,tools);document.addEventListener('click',e=>{if(e.target.closest('[data-room-legacy]')){e.preventDefault();remember();navigate('#legacy');return}if(e.target.closest('[data-room-home]')){e.preventDefault();remember();navigate('#subjects');return}const subject=e.target.closest('[data-study-subject]');if(subject){select(subject.dataset.studySubject);return}const manage=e.target.closest('[data-room-manage]');if(manage){openManager(manage.dataset.roomManage);return}const view=e.target.closest('[data-room-view]');if(view){const [subject,section]=view.dataset.roomView.split('/');setCurrent(subject);navigate(subject==='english'?(['practice','translation','writing'].includes(section)?'#english/'+({practice:'objective',translation:'translation',writing:'writing'}[section]):'#english-tools/'+section):'#politics/'+section)}});window.addEventListener('pagehide',()=>remember());window.addEventListener('popstate',restoreRoute)}
root.SubjectRoom={initialize,ownerChanged,restoreRoute,select,remember,setCurrent,openManager,openImported,hideHomeTools,reset,getSubject:()=>current,label:subject=>courses[subject]?.name||subject};
})(window);
