/* Subject entry and owner-scoped last actual room. Contains no learning bank. */
(function(root){
'use strict';
const courses={psychology:{name:'心理学',brand:'心理学学习室',hint:'北大题型为简答、论述。选择题仅作记忆辅助。',description:'趋势解析、记忆辅助、主观题预测、口诀与覆盖台账。'},politics:{name:'考研政治',brand:'考研政治学习室',hint:'考研政治与遗留高中政治/教资题库分别保存。',description:'选择题、主观题训练、知识框架、来源与变式。'},english:{name:'英语二',brand:'英语二学习室',hint:'完形与阅读按完整篇章；翻译与作文按完整任务。',description:'整篇练习、完整翻译和写作任务、框架与来源。'}};
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let api,callbacks,host,home,tools,owner=null,current=null,generation=0;
const read=(k,f)=>{try{return JSON.parse(localStorage.getItem(k))||f}catch{return f}},key=()=>`study-room-v1-user-${owner}`;
function store(){return read(key(),{visits:{}})}
function syncNavigation(){const hash=location.hash,managed=/^#(?:manage(?:\/|$)|notes$)/.test(hash);let route=null;if(current==='politics'&&hash.startsWith('#politics/'))route='politics/'+hash.split('/')[1];if(current==='english'){if(hash.startsWith('#english-tools/'))route='english/'+hash.split('/')[1];else if(/^#english(?:\/|$)/.test(hash)){const part=hash.split('/')[1];route='english/'+({translation:'translation',writing:'writing'}[part]||'practice')}}document.querySelectorAll('[data-room-view]').forEach(b=>{const active=b.dataset.roomView===route;b.classList.toggle('active',active);if(active)b.setAttribute('aria-current','page');else b.removeAttribute('aria-current')});if(current==='politics'||current==='english'||!current){const manager=document.getElementById('openManager');manager.classList.toggle('active',managed);if(managed)manager.setAttribute('aria-current','page');else manager.removeAttribute('aria-current');document.querySelectorAll('nav[aria-label="学习导航"] [data-view]').forEach(b=>b.classList.remove('active'))}}
function remember(subject=current){syncNavigation();if(!owner||!courses[subject]||subject!==current||/^#(subjects|legacy)(?:\/|$)/.test(location.hash))return;const state=store();state.visits=state.visits||{};state.visits[subject]=location.hash;state.last={subject,route:location.hash};localStorage.setItem(key(),JSON.stringify(state));history.replaceState({...history.state,roomOwner:owner,roomSubject:subject},'',location.hash)}
function setCurrent(subject){if(current!==subject)root.clearManagedSubjectContent?.();current=subject;host.dataset.roomSubject=subject||'';const course=courses[subject];document.getElementById('roomBrand').firstChild.textContent=course?course.brand:'私人学习室';document.getElementById('roomTagline').textContent=course?'理解 · 回忆 · 迁移':'选择科目 · 保留进度';document.getElementById('roomCourseHint').textContent=course?.hint||'三科内容与进度独立保存。';document.getElementById('roomSubjectStatus').textContent=course?'当前科目：'+course.name:'本人私有学习内容';document.querySelectorAll('[data-room-menu]').forEach(n=>n.hidden=n.dataset.roomMenu!==subject);document.querySelectorAll('[data-study-subject]').forEach(b=>{b.classList.toggle('active',b.dataset.studySubject===subject);b.setAttribute('aria-pressed',String(b.dataset.studySubject===subject))});root.PrivateContentManager?.setSubject?.(subject||'psychology');document.getElementById('accountBackup').hidden=subject==='politics'||subject==='english';document.getElementById('managerTitle').textContent=(course?.name||'本科')+'题库与资料管理';document.querySelector('[data-management-section="corrections"]').hidden=subject!=='psychology';document.querySelector('[data-management-section="sources"]').textContent=subject==='psychology'?'权威来源':'材料与来源';syncNavigation()}
function hideHomeTools(){home.hidden=true;tools.hidden=true;generation++}
function hideStudies(){root.EnglishStudy?.hide();root.PoliticsStudy?.hide();document.getElementById('studyMain').hidden=true;document.getElementById('managePanel').hidden=true}
function showHome(){generation++;hideStudies();tools.hidden=true;home.hidden=false;setCurrent(null);home.innerHTML='<header><div><p class="eyebrow">PRIVATE STUDY ROOMS</p><h1>选择学习科目</h1></div></header><p class="notice">各科题库、版本、学习记录与进度分别保存。已导入内容才会显示题目；资料未就绪时可先进入管理页。</p><section class="room-course-cards">'+Object.entries(courses).map(([id,c])=>'<article class="card"><p class="eyebrow">'+(id==='english'?'ENGLISH II':id==='politics'?'GRADUATE POLITICS':'PSYCHOLOGY')+'</p><h2>'+esc(c.name)+'</h2><p>'+esc(c.description)+'</p><div class="actions"><button class="btn primary" data-study-subject="'+id+'">进入'+esc(c.name)+'</button><button class="btn" data-room-manage="'+id+'">本科资料管理</button></div></article>').join('')+'</section><p class="fine">没有历史位置时展示此页；有历史时优先恢复最后实际科目、栏目和题目。侧栏随时可切换科目。</p><p><a href="#legacy" data-room-legacy>遗留高中政治 / 教资入口</a>独立保留，不属于考研政治。</p>'}
function routeFor(subject){const saved=store().visits?.[subject];if(typeof saved==='string'&&saved.startsWith('#')&&!saved.startsWith('#subjects'))return saved;if(subject==='psychology'){const legacy=read(`psychology-learning-v2-user-${owner}:navigation:psychology:v1`,{}).last;return '#'+(legacy?.route||legacy?.view||'trend')}if(subject==='english'){const last=read(`english-navigation-v1-user-${owner}`,{}).last;return '#english'+(last?.group_id?'/'+encodeURIComponent(last.group_id):'')}const last=read(`politics-navigation-v1-user-${owner}`,{}).last;return '#politics/'+(last?.view||'memory')+(last?.id?'/'+encodeURIComponent(last.id):'')}
function navigate(route,replace=false){if(!owner)return;if(replace)history.replaceState({...history.state,roomOwner:owner,roomSubject:current},'',route);else history.pushState({roomOwner:owner,roomSubject:current},'',route);window.dispatchEvent(new HashChangeEvent('hashchange'))}
function select(subject){if(!courses[subject])return;remember();setCurrent(subject);navigate(routeFor(subject))}
function ownerChanged(uid){if(owner===uid)return;root.clearManagedSubjectContent?.();owner=uid;current=null;generation++;tools.replaceChildren();tools.hidden=true;home.hidden=true;const state=store(),legacy=read(`psychology-learning-v2-user-${owner}:navigation:psychology:v1`,{}).last;const inherited=history.state?.roomOwner||history.state?.englishOwner||history.state?.studyNavigation?.owner;const foreign=inherited&&![owner,`psychology-learning-v2-user-${owner}`].includes(inherited);if(!location.hash||foreign){let route=state.last&&courses[state.last.subject]?state.last.route:null;if(!route&&legacy)route='#'+(legacy.route||legacy.view||'trend');if(!route){const en=read(`english-navigation-v1-user-${owner}`,{}).last;if(en)route='#english'+(en.group_id?'/'+encodeURIComponent(en.group_id):'')}history.replaceState({...history.state,roomOwner:owner,roomSubject:state.last?.subject||(legacy?'psychology':route?.startsWith('#english')?'english':null)},'',route||'#subjects')}setCurrent(null)}
/* Prefer native framework documents; otherwise project only explicitly classified, current-reviewed groups. */
function englishFrameworks(bank,qa,ga){
 const list=v=>Array.isArray(v)?v:[],groups=ga.groups.filter(g=>g.type==='writing'&&root.EnglishGroups.writingType(bank,g,ga.byQuestion)==='framework'),native=list(bank.frameworks).filter(f=>f&&f.module!=='translation'&&typeof f.id==='string'&&typeof f.body==='string'),represented=new Set(),cards=[];
 const boundGroup=f=>groups.find(g=>g.id===f.id||g.id===f.group_id||g.question_ids.includes(f.id)||g.question_ids.includes(f.question_id));
 const readable=g=>ga.accepted.has(g.id)&&g.practice_enabled!==false&&g.question_ids.every(id=>{const q=ga.byQuestion.get(id);return qa.accepted.has(q)&&q.practice_enabled!==false&&q.safe_for_quiz!==false});
 const unavailable=(id,reason)=>'<article class="card" data-framework-unavailable="'+esc(id)+'"><h2>框架任务暂不可用</h2><p class="fine">'+esc(id)+'</p><p>'+esc(reason||'当前材料组或子题审校未通过；正文与参考框架暂不展示。')+'</p><p>已识别本科框架条目，不表示未导入；原记录保留。</p></article>';
 const sourceRefs=refs=>'<details class="details" open><summary>框架材料与来源</summary>'+list(refs).map(ref=>{const id=typeof ref==='string'?ref:ref.id??ref.source_id,source=ga.sources.get(id);if(!source)return '';const url=typeof source.url==='string'&&/^https?:\/\//.test(source.url)?source.url:'';return '<div class="reference">'+(url?'<a href="'+esc(url)+'" target="_blank" rel="noopener noreferrer">'+esc(source.title||source.file_name||id)+'</a>':esc(source.title||source.file_name||id))+'<p class="fine">'+esc(id)+' · '+esc(typeof ref==='string'?'':ref.locator||'')+'</p></div>'}).join('')+'</details>';
 for(const f of native){const g=boundGroup(f);if(represented.has(g?.id||f.id))continue;represented.add(g?.id||f.id);if(f.practice_enabled===false||g&&!readable(g)){cards.push(unavailable(f.id));continue}cards.push('<article class="card" data-english-framework-native="'+esc(f.id)+'"><h2>'+esc(f.title||f.id)+'</h2><p class="pre-line">'+esc(f.body)+'</p><p class="fine">资料声明：'+esc(f.review_status||'未标注审校范围')+'；训练框架不视作官方范文，不代替逐题门禁。</p>'+sourceRefs(f.source_refs||g?.source_refs)+'</article>')}
 for(const g of groups){if(represented.has(g.id))continue;if(!readable(g)){cards.push(unavailable(g.id,ga.failures.find(f=>f.group_id===g.id)?.reason));continue}cards.push('<article class="card" data-english-framework-group="'+esc(g.id)+'"><h2>'+esc(g.title||'作文框架任务')+'</h2><p class="fine">稳定组号：'+esc(g.id)+' · 完整材料组与子题审校均通过 · 原创训练框架，非官方范文</p><section><h3>完整框架任务材料</h3><p class="pre-line">'+esc(g.original_text)+'</p></section>'+g.question_ids.map(id=>{const q=ga.byQuestion.get(id);return '<section data-framework-question="'+esc(id)+'"><h3>'+esc(q.title||q.prompt)+'</h3><p class="fine">稳定任务号：'+esc(id)+'</p><p class="pre-line">'+esc(q.prompt)+'</p>'+(typeof q.reference_answer==='string'?'<h4>参考功能框架</h4><p class="pre-line">'+esc(q.reference_answer)+'</p>':'')+'<h4>框架要点</h4>'+list(q.answer_points).map(p=>'<p>'+esc(typeof p==='string'?p:p.point||p.label||p.explanation)+'</p>').join('')+(q.explanation||q.plain_explanation?'<p class="pre-line">'+esc(q.explanation||q.plain_explanation)+'</p>':'')+'</section>'}).join('')+sourceRefs(g.source_refs)+'<a class="btn" data-framework-task-open="'+esc(g.id)+'" href="#english/'+encodeURIComponent(g.id)+'">进入原框架任务与草稿</a></article>')}
 return cards.length?cards.join(''):'<article class="card"><h2>作文框架资料尚未导入</h2><p>当前本科包既没有原生作文框架资料，也没有明确分类的框架任务组。其他作文不会推断为框架。</p><button class="btn" data-room-manage="english">导入本科资料</button></article>';
}
async function showEnglishTool(section){const stamp=++generation;hideStudies();home.hidden=true;tools.hidden=false;const title=section==='trend'?'趋势解读':'作文框架资料';tools.innerHTML='<header><h1>英语二 · '+title+'</h1></header><p class="notice">正在核验本人权限并读取本科资料…</p>';try{const bank=await api.getPrivateContent('english',()=>{},{validatePayload:EnglishGroups.validate});if(stamp!==generation)return;const qa=await SubjectPackage.auditQuestionReviews(bank),ga=await EnglishGroups.audit(bank,qa,SubjectPackage);if(stamp!==generation)return;tools.innerHTML='<header><h1>英语二 · '+title+'</h1></header>'+(section==='trend'?root.SubjectTrend.render(bank,'english'):englishFrameworks(bank,qa,ga))+'<button class="btn" data-room-manage="english">本科资料管理</button>'}catch(e){if(stamp!==generation)return;tools.innerHTML='<header><h1>英语二资料</h1></header><article class="card"><h2>本科资料尚未就绪</h2><p>'+esc(e.message)+'</p><button class="btn primary" data-room-manage="english">上传本科完整包</button></article>'}}
async function showManagedSources(){const subject=current,uid=owner,stamp=generation,box=document.getElementById('managerSourcesSection');if(!['politics','english'].includes(subject))return;box.innerHTML='<p class="notice">正在读取本科材料与来源…</p>';try{const bank=await api.getPrivateContent(subject,()=>{},{validatePayload:subject==='politics'?root.PoliticsStudy.validate:root.EnglishGroups.validate});if(stamp!==generation||current!==subject||owner!==uid)return;box.innerHTML='<article class="card"><h2>'+esc(courses[subject].name)+'材料与来源注册表</h2>'+bank.sources.map(source=>'<div class="reference">'+(typeof source.url==='string'&&/^https?:\/\//.test(source.url)?'<a href="'+esc(source.url)+'" target="_blank" rel="noopener noreferrer">'+esc(source.title||source.file_name||source.id)+'</a>':esc(source.title||source.file_name||source.id))+'<p class="fine">'+esc(source.id)+' · '+esc(source.identity||source.bounded_support||'原资料注册来源，不等同于官方试题答案')+'</p></div>').join('')+'</article>'}catch(e){if(stamp===generation&&owner===uid)box.innerHTML='<p class="notice">材料来源读取未完成：'+esc(e.message)+'</p>'}}
async function managerVersion(subject){const stamp=generation;let box=document.getElementById('roomManagerVersion');if(!box){box=document.createElement('p');box.id='roomManagerVersion';box.className='notice';document.getElementById('managerVersionSection').prepend(box)}box.hidden=subject==='psychology';if(document.getElementById('roomLoadLatest'))document.getElementById('roomLoadLatest').hidden=subject==='psychology';if(subject==='psychology')return;box.textContent=courses[subject].name+'：正在读取本科版本清单…';let update=document.getElementById('roomLoadLatest');if(!update){update=document.createElement('button');update.id='roomLoadLatest';update.className='btn';update.textContent='保存草稿并读取最新本科包';document.getElementById('managerVersionSection').append(update)}update.hidden=false;update.onclick=async()=>{update.disabled=true;try{await (subject==='politics'?root.PoliticsStudy:root.EnglishStudy).reload(true);await managerVersion(subject)}finally{update.disabled=false}};try{const m=await api.getPrivateContentManifest(subject);if(stamp!==generation||subject!==current)return;const loaded=(subject==='politics'?root.PoliticsStudy:root.EnglishStudy).getLoadedVersion();box.textContent='当前练习内容版本：'+(loaded||'尚未加载')+' · 服务端本科包：'+m.package_version+' · SHA '+m.sha256.slice(0,12)+'。练习页可保留已选旧版；显式读取新版后切换。'}catch(e){if(stamp===generation&&subject===current)box.textContent=courses[subject].name+'完整包尚未就绪，或版本读取未完成：'+e.message}}
function restoreRoute(){if(!owner)return false;const hash=location.hash.slice(1);if(/^politics\/(sources|overview|progress)$/.test(hash)){setCurrent('politics');navigate(hash.endsWith('/sources')?'#manage/sources':'#politics/memory',true);return true}if(/^english-tools\/(sources|progress)$/.test(hash)){setCurrent('english');navigate(hash.endsWith('/sources')?'#manage/sources':'#english/objective',true);return true}if(hash==='legacy'){showHome();home.innerHTML='<header><h1>遗留课程入口说明</h1></header><article class="card"><h2>高中政治 / 教资旧入口独立保留</h2><p>旧课程不属于考研政治。本页不把既有599道高中政治题转入考研题库，也不预置未导入内容。</p><p>旧公开链接当前仍返回登录入口；既有私有留存与学习记录保持原样，需单独迁移时再核对原课程。</p><a href="politics/index.html">旧链接（返回登录入口）</a><button class="btn" data-room-home>返回三科选择</button></article>';return true}if(hash==='subjects'||!hash){showHome();return true}if(hash==='english'||hash.startsWith('english/')){hideHomeTools();setCurrent('english');callbacks.english();remember();return true}if(hash.startsWith('english-tools/')){setCurrent('english');showEnglishTool(hash.split('/')[1]);remember();return true}if(hash==='politics'||hash.startsWith('politics/')){hideHomeTools();setCurrent('politics');hideStudies();let id=null;try{id=hash.split('/')[2]?decodeURIComponent(hash.split('/').slice(2).join('/')):null}catch{}root.PoliticsStudy.open(hash.split('/')[1]||'memory',id);remember();return true}if(hash==='manage'||hash.startsWith('manage/')||hash==='notes'){hideHomeTools();const subject=(history.state?.roomOwner===owner&&courses[history.state.roomSubject]?history.state.roomSubject:null)||current||store().last?.subject||'psychology';setCurrent(subject);callbacks.manager(hash==='notes'?'notes':hash.split('/')[1]||'bank');if(subject==='psychology')callbacks.ensurePsychology();managerVersion(subject);remember();return true}hideHomeTools();setCurrent('psychology');callbacks.psychology(hash);remember();return true}
function openManager(subject=current||'psychology',section='bank'){remember();setCurrent(subject);navigate('#manage'+(section==='bank'?'':'/'+section))}
async function openImported(subject){remember();setCurrent(subject);navigate(subject==='psychology'?'#memory':subject==='english'?'#english':'#politics/memory');if(subject==='psychology'){await callbacks.ensurePsychology();await root.reloadPrivateStudy?.({preferLatest:true})}else if(subject==='english'){await root.EnglishStudy.open();await root.EnglishStudy.reload(true)}else{await root.PoliticsStudy.open();await root.PoliticsStudy.reload(true)}}
function reset(){owner=null;current=null;generation++;if(tools){tools.replaceChildren();tools.hidden=true}if(home)home.hidden=true}
function initialize(options){api=options.api;callbacks=options.callbacks;host=options.host;home=document.createElement('main');home.id='subjectHome';home.hidden=true;tools=document.createElement('main');tools.id='subjectTools';tools.hidden=true;host.append(home,tools);document.addEventListener('click',e=>{if(e.target.closest('[data-room-legacy]')){e.preventDefault();remember();navigate('#legacy');return}if(e.target.closest('[data-room-home]')){e.preventDefault();remember();navigate('#subjects');return}const subject=e.target.closest('[data-study-subject]');if(subject){select(subject.dataset.studySubject);return}const manage=e.target.closest('[data-room-manage]');if(manage){openManager(manage.dataset.roomManage);return}const view=e.target.closest('[data-room-view]');if(view){const [subject,section]=view.dataset.roomView.split('/');setCurrent(subject);navigate(subject==='english'?(['practice','translation','writing'].includes(section)?'#english/'+({practice:'objective',translation:'translation',writing:'writing'}[section]):'#english-tools/'+section):'#politics/'+section)}});window.addEventListener('pagehide',()=>remember());window.addEventListener('popstate',restoreRoute)}
root.SubjectRoom={initialize,syncNavigation,showManagedSources,ownerChanged,restoreRoute,select,remember,setCurrent,openManager,openImported,hideHomeTools,reset,getSubject:()=>current,label:subject=>courses[subject]?.name||subject};
})(window);
